### ISSUE TITLE
Claymore Dual not respecting GPU Platfrom

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#101]
In a mixed AMD/NVIDIA GPU rig, Claymore Dual does not respect the GPU platform as defined in Config.txt.

Logic should be:
AMD only: _@@GPUPLATFORM_=0 (in Config.txt) --> use parameter '-platform 1' for ClaymoreDual
NVIDIA only: _@@GPUPLATFORM_=1 (in Config.txt) --> use parameter '-platform 2' for ClaymoreDual
AMD/NVIDIA mixed: _@@GPUPLATFORM_=?? (in Config.txt) --> use parameter '-platform 3' for ClaymoreDual

Alternatively, also the @@TYPE (in Config.txt) could be used. This would then give:
AMD only: _@@TYPE_ =AMD (in Config.txt) --> use parameter '-platform 1' for ClaymoreDual
NVIDIA only: _@@TYPE_ =NVIDIA (in Config.txt) --> use parameter '-platform 2' for ClaymoreDual
AMD/NVIDIA mixed: _@@TYPE_ =AMD,NVIDIA (in Config.txt) --> use parameter '-platform 3' for ClaymoreDual

**Comment by tutulino** [comment]
Test 5.0 release
