### ISSUE TITLE
Suggestion - make a configurable grouping of identical video cards

### ISSUE THREAD

**Issue by MonaxDK** [tutulino/Megaminer#102]
Is it possible to make a configurable grouping of identical video cards?
This would be very useful for mixed systems, for example 2x1070 and 2x1080, as on the screenshot.

![nice](https://user-images.githubusercontent.com/29005588/33241644-083796ba-d2d1-11e7-9bf0-a277f654146b.jpg)

At certain points, different algorithms are most profitable for different cards.
Ideally, it should be a parameter in the config, something like "GPU-Group1 gpu1, gpu2" "GPU-Group2 gpu3, gpu4".
Each group passes the benchmark separately. This will also be very helpful for mixed AMD / NVIDIA systems.
Dual algorithms have a different dcri-value for different cards, this would help them too.

**Comment by ydem** [comment]
There is a workaround but it's a bit tedious, you could duplicate the Megaminer folder, and edit each of the json files inside 'Miners' and for each group of algos you can add the appropriate parameter, for example for all ccminer files if you insert -d 0 1 (for device 0+1), and go to the other Megaminer folder and add -d 2 3 for the rest of the cards...

But each algo has a different parameter, for example EWBF has the parameter --cuda_devices 1,2 etc.

**Comment by tutulino** [comment]
I´m working on individualized card profit calc as Nicehash miner, but this one requires changes mayor parts of code and hard testing.

**Comment by MonaxDK** [comment]
I can help with testing on a rig with 2х1080ti and 2х1070, if you need it.

**Comment by tutulino** [comment]
test 5.0 release

**Comment by MonaxDK** [comment]
version 5.0 works just fine, thank you very much!
![viber image](https://user-images.githubusercontent.com/29005588/33795867-1223f620-dcf2-11e7-89ce-c7635dd58fce.jpg)
