### ISSUE TITLE
Suggestion - make a custom currency setting (usd / euro / gbp) instead of auto selection by region.

### ISSUE THREAD

**Issue by MonaxDK** [tutulino/Megaminer#103]
It would be great to make a custom currency setting (usd / euro / gbp) instead of auto selection by region.
Many people would be more comfortable to see the values in a more familiar currency instead of the auto selected by region.
It would also be great to be able to specify different BTC-wallets for different pools. This is necessary for Nicehash for example, if you use auto mode on many pools. In the case of using an conventional BTC-wallet you can wait a year for payout on Nicehash.  Instead, you can specify it's internal wallet for Nicehash, where payments occur much more often.

**Comment by madest13** [comment]
+1

**Comment by tutulino** [comment]
I will add it to next release
