### ISSUE TITLE
benchmarking of siacoin on MPH

### ISSUE THREAD

**Issue by szentigrad3** [tutulino/Megaminer#105]
so i get this everytime i start the miner it tries to bench siacoin on MPH

https://puu.sh/yv1UV/47f11b5986.png

**Comment by MonaxDK** [comment]
I have the same thing on all available miners. The only one that works is Claymore Dual, but it can not work with the SIA in a non-dual mode... Also tried the Excavator on nvidia cards, but I could not get it to work

**Comment by tutulino** [comment]
MPH has different stratum protocol for that pool, I have modified pool file to ignore this pool, you can pick new file from master.
