### ISSUE TITLE
ccminerAlexisHSR

### ISSUE THREAD

**Issue by szentigrad3** [tutulino/Megaminer#107]
having alot of issues with this miner, reject reason: low difficulty share and then it closes on Pool asked your stats, pic attached below
![zpool](https://user-images.githubusercontent.com/5462780/33524383-83125a88-d870-11e7-9bab-e6246ba0210f.png)

**Comment by MikeBuzz** [comment]
Remove the stats option from the pool file, I am sure they are removed from latest version, also it seems that with the rejects o let happen on zpool

**Comment by szentigrad3** [comment]
Removed the stats from the pool file seems its not removed on github as I checked, what do u mean about the rejects

**Comment by MikeBuzz** [comment]
If you run it against MPH you doing get the rejects, not sure what the issue is really maybe pool side problem

**Comment by czjlj** [comment]
Should be update the pools  file.Zpool often show "api not responding"

**Comment by tutulino** [comment]
I have removed stats option for pools files, rejected shares seems pool or miner problem.
