### ISSUE TITLE
Unimining shows no pools, unable to use

### ISSUE THREAD

**Issue by cjroepe** [tutulino/Megaminer#108]
When I select automatic 24 h and then unimining it will display "no pools wait 10 sec."
When I select manual, unimining, no coins show up to mine

**Comment by tutulino** [comment]
I´m testing now and works ok, maybe temporally pool problem. Can you test again?

**Comment by cjroepe** [comment]
I tried options 0,1&2 (auto vs manual) and then the unimining option.  For manual is says to select coin but there is nothing to select.  For the other options it just says no pools.  I am using the latest release.

**Comment by cjroepe** [comment]
![1882598e-c437-43a0-b144-898ee67a22ae](https://user-images.githubusercontent.com/24252766/33629565-7ee7c764-d9d2-11e7-8444-3dd58395b42b.jpeg)

**Comment by cjroepe** [comment]
![63107fe9-1dca-4a59-8191-a1c3f8105ed7](https://user-images.githubusercontent.com/24252766/33629705-051e32dc-d9d3-11e7-8884-0f0539e213cf.jpeg)
![062c2334-660b-4f90-81f7-0d9229dfaab1](https://user-images.githubusercontent.com/24252766/33629706-053692f0-d9d3-11e7-847a-cc9bc74e3e04.jpeg)

**Comment by tutulino** [comment]
Works well here, please try this URL on your browser, do you get response?

http://pool.unimining.net/api/currencies

**Comment by cjroepe** [comment]
i do, the api response shows up

all pools etc

**Comment by cjroepe** [comment]
![051c2789-cf4d-4173-be8d-797c7f64199e](https://user-images.githubusercontent.com/24252766/33679033-991b2d60-da8b-11e7-9642-dc59e2502f50.jpeg)

**Comment by tutulino** [comment]
I have no idea what is happening, I tested a lot of times two past days and always is responsive.

**Comment by yuzi-co** [comment]
Did you define a wallet in config.txt for a coin that is on that pool? They don't have any autoexchange?

**Comment by tutulino** [comment]
good point.

**Comment by cjroepe** [comment]
That was it!  Thank you so much guys.

This is a great feature because the individual neoscrypt coins are so profitable right now.

Should the profitability per coin be showing up when you mine unimining?

**Comment by cjroepe** [comment]
The 24h average doesn’t show but the current will
