### ISSUE TITLE
Latest version has broken Hash Refinery

### ISSUE THREAD

**Issue by MikeBuzz** [tutulino/Megaminer#11]
all coins report 0 btc/day

**Comment by MikeBuzz** [comment]
![image](https://user-images.githubusercontent.com/941624/29233824-2a2b4d46-7eeb-11e7-95a9-a8e95c4c3635.png)

**Comment by MikeBuzz** [comment]
Rolling back to https://github.com/tutulino/Megaminer/blob/e6f222ba42b352764ede508bf1f8aee312d99bbc/Pools/Hash_Refinery.ps1

![image](https://user-images.githubusercontent.com/941624/29233917-a5abd8b4-7eeb-11e7-97b2-dac6673396b8.png)

**Comment by tutulino** [comment]
Fixed in next release
