### ISSUE TITLE
Claymore Cryptonote Miner - 9.7?

### ISSUE THREAD

**Issue by imrecsoka** [tutulino/Megaminer#114]
Hi, i have a problem with Claymore Cryptonote miner 10.x as they rob me with my hash rate,
My 3rd AMD GPU does not get full speed of more or less 633 hashes/second
When 10.2 is being used i get 315 hashes/second for the 3rd GPU i dont understand why.
With prior version i get 633.

**Comment by tutulino** [comment]
Do you have screen connected to that GPU?

It´s better you ask on Claymore Cryptonote thread on Bitcoin talk.

Megaminer is only a launcher, while miner is running MM has no control over miner

**Comment by imrecsoka** [comment]
@tutulino thanks, i am asking you though, I have asked on forums about the Claymore 10.X and it is a problem everybody is having, so they prefer to use 9.7 as it gives full speed.
SGminer is still also better option for some people.
Can you please show me how to use SGminer for Cryptonite OR how to make your miner use version 9.7 of the NsGpuCNMiner.exe program.
I will appreciate it and remember , whoever uses this for you can always donate.
I will donate , i am not greedy.
I am a small fish , and i an not rich , BUT i am trying to mine nicely and not waste my time , so if i have questions or improvements or whatever i will like to help you and give suggestions.

**Comment by tutulino** [comment]
I have added Claymore Cryptonote 9.7

**Comment by imrecsoka** [comment]
HI, thank you , i still need to see what you mean about core.ps1, it looks complicated.
Not sure i understand hundred percent about what i must change the way you worded it...
I will check again.
Thanks for adding Claymore Cryptonote 9.7
