### ISSUE TITLE
Mining with CPU?

### ISSUE THREAD

**Issue by imrecsoka** [tutulino/Megaminer#115]
Hello, i see there is no CPU mining window?
Not sure why?
I could do with 60 cents extra per day and so can your donation to this project.

**Comment by MonaxDK** [comment]
+1
it does not really make much sense to mine on the CPU in our time, but it would be nice to have such an option, just in case.

**Comment by tutulino** [comment]
What are the best CPU miners?

**Comment by HildgenF** [comment]
JayDDee : https://github.com/JayDDee/cpuminer-opt
Best algo to mine lyra2z -> Zcoin

**Comment by mic4rd** [comment]
This! Only thing to keep me from using megaminer instead of multipoolminer. Just can't discard the additional 50 cent profit per day ;)

**Comment by mtbor** [comment]
Ryzen CPU's are said to be profitable on cryptonight.

**Comment by mtbor** [comment]
mic4rd, why not remove GPU settings from multipoolminer and just run both?

**Comment by imrecsoka** [comment]
True, CPU power not worth it.
BUT if u dont pay ELEC maybe , its fine.
I do pay electricity.
THEN if u have a power CPU like say a Ryzen or whatever, and u can make 1 USD + with power of say under 100 Watts then that good enough.

**Comment by imrecsoka** [comment]
@tutulino  I believe XMRig and XMR-STAK-CPU is the best for CPU mining against Cryptonite.
It is also Cryptonight-lite in those miners i believe for mining AEON.

@tutulino  I mine with CPU outside of your miner suite BUT i can see that my CPU rate is low...
I think it is something to do with the refreshing/checking that you do in the background... so it slows down the CPU.
Maybe you can change your settings to make it not 5 second but say 60 or 120 seconds?
Can you help with this?
I would like to help but i dont understand the Shell programming.

**Comment by imrecsoka** [comment]
@HildgenF  i dont know if i agree with : 

JayDDee : https://github.com/JayDDee/cpuminer-opt Best algo to mine lyra2z -> Zcoin

I have never liked any of the Minerd Cpuminer programs, Nicehash or Aarons Multipool miner never suggested to use it, so it could not have been great performance?
Are you sure?
Please show me which pool and coin to try for myself?
I have tried AMD and INTEL and really for me AND according to Nicehash Miner and Multipool Miner, they always chose XMR-STAK-CPU or XMRIG as the preferred miners.

**Comment by imrecsoka** [comment]
@mic4rd  tell me more, please i am also fussy about 50 cents.
Please let me know, would be happy to learn and give what i know also.

**Comment by imrecsoka** [comment]
@mtbor I tried that and it doesnt work well, there is something in the code of Megaminer which does a refresh or a check of some sort BUT it does it too frequently , so it slows down the CPU mining and u dont get the most out of it.
I have asked if Mega Tutulino can please change that setting to say 60-90-120 secondsof whatever it is doing, it will help a lot.
I also firmly believe that claymore 9.7 cryptonote , sgminer  for GPU , and XMR-STAK-CPU and XMRIG for CPU are the best options - FOR Cryptonight algorithm. I believe they support AEON also which is Cryptonight-light.

**Comment by mic4rd** [comment]
@imrecsoka sure,also curious why you think it's not profitable.
Mining lyra2z/Zcoin with CpuminerJayddeeAesavx2 gives me ~0.00006 BTC/day (~0.70 EUR/day). Power readout from my Energy Monitor 3000 increases by ~30 to 35 W when enabling CPU mining additionally to GPU mining. That is additional power cost of 0.035 kW * 24 h * 0.256 EUR/kwh = 0.21 EUR/day.
CPU is a 6600k @4.5 GHz @1.3 V. 
Mining CryptoNight/Monero with XMR-Stak or XMrig is currently slightly less profitable (~0.00004 BTC/day) but still worth it.
I've been experimenting a lot using nicehash over the months (stock speed+undervolting etc.) and found it has always been profitable (nicehash gave you a nice EUR/day, EUR/month view on individual algorithms, so after a day it was fairly easy to tell that the rates for Monero/Zcoin were real).

**Comment by tutulino** [comment]
Jaydee is working well now on my rig, Beta2 will include.

Next is to include  XMR-STAK-CPU and XMRIG 

Imrecsoka, for change refresh speed test to change in core.ps1 file  "NEW-TIMESPAN $Loopstart (get-date)).Seconds -lt 4" to "NEW-TIMESPAN $Loopstart (get-date)).Seconds -lt 20" 
This change refresh speed but MM continues running back for keyb response.

**Comment by HildgenF** [comment]
@imrecsoka 
"I have never liked any of the Minerd Cpuminer programs, Nicehash or Aarons Multipool miner never suggested to use it, so it could not have been great performance?
Are you sure?
Please show me which pool and coin to try for myself?"
Yes I am sure.

On a Skylake, I get around 600-640 kH/s, which gives 0.00008 BTC/day, more than 1$ a day for Lyra2z.
Mining XMR gives .00003 BTC a day.

**Comment by imrecsoka** [comment]
I dont understand this post then:
"JayDDee : https://github.com/JayDDee/cpuminer-opt
Best algo to mine lyra2z -> Zcoin"

Please also tell me with what miners you use for you skylake.
I was considering to upgrade my mobo and cpu to a newer generationBUT not sure what to buy, i dont know if i can afford what you bought, but i can try, maybe you can help suggest,

But Please come back to me on what miners you use and for what algorithm and then explain that quote as ui dont understand because there it says the other cpuminers , which are the ones i never likes or found profitable.
for me the ones i mentioned are the best miners i have found.
As for what to mine m, thats a different story.

Thanks

**Comment by imrecsoka** [comment]
Well im really confussed now, 
Multipool Miner and Megamine dont seem to use or call or even nicehashminer never called that CPUMiner tool which is why i believe it was not profitable.
Always on my side " XMR-STAK-CPU and XMRIG" are used.
Please help me here as i am clearly missing something if you guys say that Jaydee miner is good.

**Comment by imrecsoka** [comment]
@mic4rd Please explain or tell me then which miner suite i use that will call Jayddee miners then:
"@imrecsoka sure,also curious why you think it's not profitable.
Mining lyra2z/Zcoin with CpuminerJayddeeAesavx2 gives me ~0.00006 BTC/day"
Maybe my stuff is not benchmarked properly or setup properly ?

**Comment by HildgenF** [comment]
"I dont understand this post then:
"JayDDee : https://github.com/JayDDee/cpuminer-opt
Best algo to mine lyra2z -> Zcoin"
Please also tell me with what miners you use for you skylake."

JayDDee is compiled for different micro-architecture : SSE2, AES, AVX, AVX2
So depending on your CPU you have to select the right miner. On a Skylake, you need to run the AVX2 version.

As for the algorithm, the most profitable is lyra2z which will should give you Zcoin.

I came to use the CPU miner through Multipoolminer. I would suggest that you use it, you can configure it so it only mine on a CPU.

**Comment by imrecsoka** [comment]
Okay well  i will download Mutipool miner again fresh and let it run benchmarks for everything.
I normally used to delete the CPU/Miner miners and only leave XMR-STAK 
for reason also i seem to get so many warnings or exceptions or errors on the main launcher screen its irritating. Which is a stable version of Multipool miner to use

**Comment by tutulino** [comment]
XMRstak cannot be integrated, XMRig is working well

**Comment by HildgenF** [comment]
@imrecsoka
Latest version of multipoolminer seems fine. You need to edit the start.bat file to just leave cpu as a type, and it should start the benchmarking.

**Comment by imrecsoka** [comment]
oh u have integrate XMRIG? really, i dont know why i dont see it running.
it only runs GPU stuff :-(
Im talking about MEGA MINER now.
I would like to use MEGA MINER and donate and then chop and change when i want from MULTIPOOLMINER to MEGA MINER and donate both ways, i appreciate the help and i dont mind donating if i can to those that help me.
I just want to be able to use the stuff i have for what it is worth and try to get some income, thats all i with for . If u can help me thank you.

**Comment by mic4rd** [comment]
@imrecsoka MultiPoolMiner calls Jaydee just fine. That's what it shows for CPU on my sys:
![image](https://user-images.githubusercontent.com/13984586/33807033-100b905c-ddd1-11e7-9780-f5775554374f.png)
I only get like 450 kH/s with my 6600k, probably with i7 skylake or kaby lake/coffee lake CPUs it's even more profitable. Imho, buying a new mobo and CPU doesn't make any sense for mining. It's just like a small additional bonus to the GPU mining.

**Comment by tutulino** [comment]
I have integrated...in next release

2017-12-10 17:43 GMT+01:00 mic4rd <notifications@github.com>:

**Comment by mic4rd** [comment]
@tutulino awesome, can't wait, thanks a lot!

**Comment by HildgenF** [comment]
@mic4rd 
I get between 600 and 640 kH/s on a Skylake i7-6700K

Next Intel processors : i9 series should give a nice performance boost with 16 cores!!!

**Comment by imrecsoka** [comment]
have 2600k  Intel 7 which is old BUT it still performs well, twice as fast as my rubbish AMD X4 860k i bought ,cant believe i bought that rubbish, BUT the motherboard is a great 5 slot for PCI-E, so thats cool.
I only have 2 GTX 1060 cards though. so i am weak compared to most people,

My intel 2600k i7 i have RX470 x2 which is ssvery decent, just yah, it me forever to get what i have and i stillneed to get reward for it,  I used to use  MPM but it seemed to take forever to pay o i was not sure, and  also i am not sure how accurate it was. I then discovered Megaminer long ago an tried it but i was not sure how it worked because i needed to have accounts on the pools and stuff it was very new to me.
I actually delete the pools now and only keep the miningpoolhub there. Then i got lost and i tried SOLO mining and plain simple pool mining on stuff like BITSEND and i agg i thikn only 1 or 2 coins bt i was really wasting my time i got nothing from it,. Then i went back o Nicehashminer and itwas horrible an then one day i started it and the Cryptonite was through the roof, God knows why, so started using it.
And then after 5 weeks of mining, i lost 130 USD because they hacked it and i was going to get paid on Friday , im so sad and pissed off and i could have used that money for small christmas gift for my daughter and wife, fuck anyways.
So here I am again.
Wanting to find the right track and asking for guidance.

**Comment by HildgenF** [comment]
@imrecsoka 
Not sure about an i7-2600K being profitable with cpu mining if you look at the daily price, however if you look how the value of crypto coins keeps growing, then your earnings might be profitable in the future if the market keeps growing. CPU mining on a Skylake is worth it, previous gen is also profitable.

As for mining, I would suggest that you use Multipoolmining with auto-exchanges enabled and automatic payments, but you need to create an account. You have other pools available as well, where you just need to put your BTC address and you'll receive your earnings.
But be careful, pools can be hacked, like nicehash last week, but before it was working nicely, zpool and ahash work fine.

**Comment by Paul-Trasca** [comment]
Is there any bat file to start cpu mining?

**Comment by Paul-Trasca** [comment]
Any instructions to start cpu mining? Anyone? please?

**Comment by tutulino** [comment]
You must add a group on config.txt in @@gpugroups, read how in config.txt

**Comment by Paul-Trasca** [comment]
i already do that. Receive this beautiful:
![image](https://user-images.githubusercontent.com/30908920/33809633-cabc3fb0-de02-11e7-81a1-ff797d165aff.png)

**Comment by tutulino** [comment]
String must end with a ]

**Comment by Paul-Trasca** [comment]
@@GPUGROUPS=[{"GroupName" : "1080ti","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0"} , {"GroupName" : "CPU","Type":"CPU"}  ]

**Comment by Paul-Trasca** [comment]
can u write entire syntax?

**Comment by MonaxDK** [comment]
Just got the same error and understood what the problem is :) You have the character Enter before the square bracket at the end of the line.
