### ISSUE TITLE
Scam software is a scam

### ISSUE THREAD

**Issue by dinicthis** [tutulino/Megaminer#117]
If you modify ONE parameter, and only ONE, the Bitcoin address for payments, the software locks up and doesn't work, with a bunch of error crap in red type at top of mining window.

Scammer, dismissed.

**Comment by tutulino** [comment]
Feel free to use or not, but not for launch false acusations.

If you have a bug, report and wait response.

**Comment by dinicthis** [comment]
It isn't a false accusation. Your software only works if it is mining to YOUR bitcoin address, not MY bitcoin address, thus it is a scam.

I changed one thing, and one thing only, as instructed: the bitcoin address.

This caused your trojan horse to lock up and quit.

Nice try, but your software is just another in a long list of self-serving SCAMS.

**Comment by MikeBuzz** [comment]
What a load of crap, there are many people using this with out any issues, I have been using it for months and have it configured correctly to my address. I suggest you raise a ticket with the error details not just post false information

**Comment by tutulino** [comment]
If you label mining software as scam each time you get an error in your first run, you will have to mine with a pencil and paper....

**Comment by dinicthis** [comment]
Okay captain Shill, I posted all the information necessary. I replaced the
BTC address with my address and that caused it to not function

The "tons of people using it" are just mining for someone else, without
knowing it.

**Comment by dinicthis** [comment]
You tell me why YOUR software immediately does not function with the simple modification of MY bitcoin address in it instead of YOUR bitcoin address in it.

You can't explain it because it is designed specifically to mine away merrily to YOUR pocket.

Scam.

**Comment by dinicthis** [comment]
I have never seen a coin with so many scammer or an algo with so many scammers, I downloaded several version of CCminer, all of them locked up and quit, if you entered, for one of them, your Vertcoin where the scammer had HIS vertcoin address, and others for other reasons.

But, the Lyra2REV2 algo is the most scammed algo in history, thus far.

**Comment by tutulino** [comment]
Lost of time...use other software please



2017-12-09 16:57 GMT+01:00 dinicthis <notifications@github.com>:

**Comment by dinicthis** [comment]
Nah, I'll stick around here until you prove your software is not a lying
scam, for now.

**Comment by tutulino** [comment]
If you want to collaborate, open an issue with your error (what you change,
where, what program you used, error message, etc)  not with acusations or
conclusions.


2017-12-09 17:15 GMT+01:00 dinicthis <notifications@github.com>:

> Nah, I'll stick around here until you prove your software is not a lying
> scam, for now.
>

**Comment by Paul-Trasca** [comment]
The software work like a charm... easy to config...
