### ISSUE TITLE
config for gpu setting

### ISSUE THREAD

**Issue by Steality** [tutulino/Megaminer#119]
Hi there.
Perhaps I am setting it wrong, but..

**@@GPUGROUPS=[{"GroupName" : "1080ti","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0"} , {"GroupName" : "1060","Type":"NVIDIA","GpuPlatform":"0","Gpus":"1"} ]**
A default config setting is fine

**@@GPUGROUPS=[{"GroupName" : "1070","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0,1,2,3,4"}]**
change this setting shows error, its still benchmark and mining properly, but active miner and profits windows missing

I have 5x gtx1070

**Comment by tutulino** [comment]
if you want to run all your cards as one block put:
@@gpugroups=[{"GroupName" : "1070","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0,1,2,3,4"}]

if you want for example two groups (has no sense, all are same model)


@@gpugroups=[{"GroupName" : "1070_1","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0,1,2"},{"GroupName" : "1070_2","Type":"NVIDIA","GpuPlatform":"0","Gpus":"3,4"}]

**Comment by Steality** [comment]
Ah I see, its for pointer #DEVICES# for assigned gpu to each miner. 
Sorry Sir, wasting your time. :(
