### ISSUE TITLE
one question about functionality

### ISSUE THREAD

**Issue by danik-guitar** [tutulino/Megaminer#12]
is it possible to mine this coin which is depicted as the most profitable in auto.
for exemple : the most upper line (myr-gr  -  Aurora), but pool chooses different coins with the same algorithm Myriad and Verge.

![qip shot - screen 2017 08 12 12-08-28](https://user-images.githubusercontent.com/30734827/29239425-24261ac2-7f57-11e7-9820-5ac0723bcb90.jpg)
![qip shot - screen 2017 08 12 12-14-43](https://user-images.githubusercontent.com/30734827/29239458-d9d66250-7f57-11e7-9432-c88819d4ae6e.jpg)

**Comment by tutulino** [comment]
Zpool, MPH or HR not support you choose a coin to mine, only let you select an algorithm and they choose coin. 

I supose pool decides more profitable based on average statistics of hashrate, Megaminer does based on Pool´s api reporting and your exact benchmarked hashrate.

**Comment by tutulino** [comment]
Next release eliminates zpool coin info, not real info.
