### ISSUE TITLE
which miner on which algorithm to use

### ISSUE THREAD

**Issue by MonaxDK** [tutulino/Megaminer#120]
I did a lot of testing by trying all available algorithms on all miners. As a result, each of the miners includes all the algorithms that show a more or less high result and work stable.

What is it done for? For example, SKEIN algo hashrate.
GTX970
AlexisHSR - 323922374
Polytmos - 320816197
Alexis - 320289441
Palgin - 318443296

3x1080Ti
Polytmos - 2985150278
AlexisHSR - 2981166614
Alexis - 2970059964
Palgin - 2959687817

Benchmark time 300s.

As you can see, different miners are faster on different video cards. Default miner, Alexis is not the fastest on any card type.

Added:
Cryptonight miner from KlausT, it's the fastest. Unfortunately, as far as I understand, it does not have an API port, so it can not create a file with the result of the benchmark, it has to be created manually.
djm34 ccminer - fastest lyra2z miner

Tested on Nvidia GTX970, GTX1070, GTX1080Ti. 

Perhaps you can include my work in a new release? I'm just tired of remaking all the json files with every new release :)

[CustomJson.zip](https://github.com/tutulino/Megaminer/files/1544754/CustomJson.zip)

**Comment by tutulino** [comment]
Please give me a list with your fastest miner for 970, I will add to next release.

**Comment by MonaxDK** [comment]
![clipboard01](https://user-images.githubusercontent.com/29005588/33797486-5a74d632-dd11-11e7-8cdd-de1ef92b091a.png)
djm34 does not work on 970, its for 10-series cards only

**Comment by tutulino** [comment]
Added to next release

**Comment by MikeBuzz** [comment]
I will try and compile a list for the 1070 as it seems to differ to the 1080ti

**Comment by MikeBuzz** [comment]
@MonaxDK did you find the best miner for the 1070 was the same as the 1080?

also would checking out this fork as looks like they have spent lots of time tweaking intensity settings

https://github.com/livegpumining/Megaminer

**Comment by MonaxDK** [comment]
Often the best miner for 1070 and 1080 is the same, but not always. All depends on the ratio between the speed of memory and the GPU. Sometimes even cards on the same GPU but from different manufacturers, choose different miners. 
Here is an example of how different miners and algorithms are selected for 1080ti and 1070

![viber image](https://user-images.githubusercontent.com/29005588/33969483-431cda76-e076-11e7-9f12-82b835e2dcdf.png)

**Comment by livegpumining** [comment]
@MikeBuzz All those intensities are for a 1080ti, I have them set from the benchmarks on zpool which makes it easier to fine tune (knowing what it should be already).  If I could get particular miner files to work with particular groups I could continue this with a mixed rig which I might have to do soon.
