### ISSUE TITLE
Format-Table : The Label key has no value.

### ISSUE THREAD

**Issue by mtbor** [tutulino/Megaminer#122]
This may be innocuous as the mining script is still working on benchmarks and may resolve its null values upon completion, but having a resolved "issue" may be helpful to others, or I may have something wrong in my config... so here goes:

------------------------------------------------ACTIVE MINERS----------------------------------------------------------
Format-Table : The Label key has no value.
At C:\Users\***EDIT***\Downloads\Megaminer-master\Megaminer-master\core.ps1:709 char:84
+ ... ect Status -eq 'Running'| Sort-Object GroupId | Format-Table -Wrap  (
+                                                     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Format-Table], NotSupportedException
    + FullyQualifiedErrorId : DictionaryKeyMissingValue,Microsoft.PowerShell.Commands.FormatTableCommand
----------------------------------------------------PROFITS------------------------------------------------------------
                                                                                (B)est Miners/All       (T)op 25/All
Format-Table : The Label key has no value.
At C:\Users\***EDIT***\Downloads\Megaminer-master\Megaminer-master\core.ps1:767 char:96
+ ... t-Object -Descending GroupName,NeedBenchmark,Profits | Format-Table (
+                                                            ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Format-Table], NotSupportedException
    + FullyQualifiedErrorId : DictionaryKeyMissingValue,Microsoft.PowerShell.Commands.FormatTableCommand

**Comment by tutulino** [comment]
what value do you have on @@LocalCurrency in config.txt?

Must be DOLLAR/GBP/EURO

I have added code to always show dollar if @@LocalCurrency is not correct.

**Comment by mtbor** [comment]
Ah that's probably it..  I think I put USD

**Comment by mtbor** [comment]
Silly error on my part, thanks for the help, it's working good now.
