### ISSUE TITLE
Not using platform ID correctly

### ISSUE THREAD

**Issue by huangyihe** [tutulino/Megaminer#123]
It's great that I can set platform ID in the GPU groups now, but it doesn't seem to be used correctly in all the miners. Claymore and EWBF both have issues. It looks like in these miners only the CUDA IDs of devices are passed in, but they actually appear to accept either that with a platform ID (like in Claymore), or accept raw PCI IDs (which is definitely not CUDA ID).

**Comment by tutulino** [comment]
All NVIDIA exclusive miners (ccminer, ewbf, etc) ignore GPU platform, they search cuda platform.

Claymore seems dont need GPU platform, only opencl devices ID, but I´m not sure. I havent AMD cards here to test.

If you get a correct call to claymore tell me to analyze.

**Comment by huangyihe** [comment]
I think EWBF should be called with “--cuda_devices 0 1 2 3” (space
separated) instead of “--cuda_devices 0,1,2,3” (comma separated).

Claymore should be called with “--platform 2” to exclude AMD GPUs. Likewise
platform 1 should be selected to exclude NVIDIA GPUs.

**Comment by huangyihe** [comment]
Oh yes the same goes for dstm’s zcash miner (zm), device list should be
space separated not comma separated.

**Comment by tutulino** [comment]
For space separated change #DEVICES# in miner file for #DEVICESETHMODE#

I´m fixing in source code



2017-12-10 9:27 GMT+01:00 Yihe (William) Huang <notifications@github.com>:

**Comment by tutulino** [comment]
I´m testing, dtsm and ewbf seems works with coma or space separated devices list. I get same result.

**Comment by tutulino** [comment]
Claymore Platform parameter is a grouping parameter, MM is passing opencl devices directly, it must not be necessary use this parameter

**Comment by huangyihe** [comment]
I'm pretty sure comma vs. space makes a difference on my machine. For EWBF if I only use `--cuda_devices 0,1,2,3`, then only CUDA GPU 0 will be selected. Same goes for DSTM. It won't generate any errors from the miner but it will only select the first device in that (comma separated) list.

For Claymore, I'm pretty sure the `-platform` parameter is needed to separate GPUs from different vendors (NVIDIA/AMD). I've made the changes myself and it's now working perfectly for me. I can create a pull request later for you to review the changes.

**Comment by tutulino** [comment]
try beta 2 and tell me

**Comment by huangyihe** [comment]
Claymore still won't work for me without the `-platform` option.

**Comment by tutulino** [comment]
Seems like -di #DEVICESCLAYMODE# was not working....

**Comment by huangyihe** [comment]
I think it has a lot to do with different meanings of device IDs in different miners. For things like ccminer, it expects CUDA IDs only, so say I have 4 NVIDIA GPUs and 4 AMD ones, regardless of the actual OpenCL IDs of these devices I only pass 0,1,2,3 to ccminer. Things are different for Claymore since uses global OpenCL IDs of all GPUs. The reason I have to pass `-platform` parameter to Claymore is so that I can use the same device IDs across the board (and I don't believe the script currently does the translation for me, unless it's just been fixed).

**Comment by tutulino** [comment]
If I understand, when a group is Nvidia Type you must write cudaId on Gpus
field, if is AMD type you must write OpenCl global ID, this dont work?

2017-12-13 19:14 GMT+01:00 Yihe (William) Huang <notifications@github.com>:

**Comment by huangyihe** [comment]
Nope it doesn't work. sgminer actually recognizes my AMD GPUs as devices 0,1,2,3 although their OpenCL IDs are actually 5,6,7,8.

**Comment by tutulino** [comment]
It is working well for people with mixed rigs, i think your rig is failing because your amd platform is after nvdia platform and this makes global opencl ids distincts than valid for sgminer.

I think i know how to solve it with your info, give me one or two days, also i have bought a rx580 to make my development rig mixed, this way it will be easier for me to test.

**Comment by huangyihe** [comment]
Yes it's true. Actually after a recent Windows Update all my AMD devices moved to the back. Take your time.

But I do want to point out that if you use Claymore without the `-plaform` option then everything should be OpenCL device IDs, including for NVIDIA.

**Comment by tutulino** [comment]
Please, test beta4

**Comment by huangyihe** [comment]
Yes it appears to work now. Thanks!
