### ISSUE TITLE
Config.txt confussing

### ISSUE THREAD

**Issue by imrecsoka** [tutulino/Megaminer#124]
@@GPUGROUPS=[{"GroupName" : "1080ti","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0"} , {"GroupName" : "1060","Type":"NVIDIA","GpuPlatform":"0","Gpus":"1"} ]

I dont understand what  i am supposed to do here?
I have 1 computer with RX470
I have another computer with GTX1060

There was also a section about API keys, i deleted this, i dont need it.
I am only using mulipoolhub mining pools.

![image](https://user-images.githubusercontent.com/25494601/33807465-0a23d03c-dde0-11e7-8b92-811c27c807e5.png)

**Comment by tutulino** [comment]
if your rig only has one card not grouping possible 


for Nvidia computer
[{"GroupName" : "1060","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0"} ]

for Amd computer
[{"GroupName" : "RX","Type":"AMD","GpuPlatform":"0","Gpus":"0"} ]
or
[{"GroupName" : "RX","Type":"AMD","GpuPlatform":"1","Gpus":"0"} ]

**Comment by imrecsoka** [comment]
So i am using my intel now, which has 3 RX470
So i have put:
@@GPUGROUPS=[{"GroupName" : "RX470PC","Type":"AMD","GpuPlatform":"1","Gpus":"0,1,2"}]

I dont know what the hell the platform means.
is it 0 or 1

I guessing for my GTX1060 i will use platform 0 as you have already and then say 0,1,2

Is this grouping needed? what does it do for me?
I mean what will hapen if i just delete the section?

**Comment by imrecsoka** [comment]
![image](https://user-images.githubusercontent.com/25494601/33807668-020d9c5e-dde3-11e7-90e0-f6e5c7982c4c.png)

Also getting alot of these, also in version 4.8

![image](https://user-images.githubusercontent.com/25494601/33807676-0dce59c0-dde3-11e7-9c40-5977ece406b6.png)

**Comment by tutulino** [comment]
I have added automatic gpu platform detection on next release.

All gpus are compatibles with opencl (cuda is only nvidia compatible), so you can tell miner with platform must use.

In mixed rigs you can have 3 opencl platforms (Intel, AMD, NVIDIA)

**Comment by tutulino** [comment]
Is better than each issue has own thread, but dont mind.

I can not hep you with that error, I have not idea
