### ISSUE TITLE
CCMiner Alexis hsr 1.0 label:enhancement 

### ISSUE THREAD

**Issue by cjroepe** [tutulino/Megaminer#129]
If you put stats in the -p this will cause alexis 1.0 to crash.  I reccomend removing it until Alexis removes this issue.

**Comment by tutulino** [comment]
I  think is removed for all pools, if you see one, pls tell me

**Comment by cjroepe** [comment]
It isn't removed.  Just verified
![image](https://user-images.githubusercontent.com/24252766/33900572-824937aa-df34-11e7-951d-1058813a4e0c.png)
This will cause the miner to crash every 5 minutes.  need to remove the variable "stats"

**Comment by tutulino** [comment]
I check last release has removed.

If you are using previous version must edit pool file and delete ",stats" from pass field at end of script
