### ISSUE TITLE
ccminer-Klaust. Not benchmarking, because group names are leaking into command line.

### ISSUE THREAD

**Issue by PeKlim** [tutulino/Megaminer#130]
5b3 - ccminer-Klaust. Not benchmarking, because my group names are leaking into command line.

@@GPUGROUPS=[ {"GroupName" : "1080Ti","Type":"NVIDIA","Gpus":"1,2"} , {"GroupName" : "1080","Type":"NVIDIA","Gpus":"0"} ]

When benchmarking, I get - ccminer.exe: unsupported non-option argument '_1080Ti'
other ccminer task (second group) gets unsupported argument _1080, of course.

When i edit miners json, to make tpruvot support algorithms and klaust to unsupport algorithms. tpruvot is able to benchmark those, but it warn with same error about unsupported argument, but tpruvot is not stopping on this.

**Comment by tutulino** [comment]
post command launched (you can see it on history screen)

**Comment by tutulino** [comment]
ugly space after Blabla... check your @@workername

**Comment by PeKlim** [comment]
Great! You are exactly right. I found and deleted something invisible after workername. Now all is working Right. Thank You.

**Comment by tutulino** [comment]
I will add trim spaces to some variables to prevent this
