### ISSUE TITLE
Miner is blocking on stratum disconnect

### ISSUE THREAD

**Issue by Paul-Trasca** [tutulino/Megaminer#131]
Hi... today megaminer stuck on nist5 after nist5 zpool stratum disconnect. After profitability nidt5 rate drop under next profitable algo, the megaminer do nothing. After manually hit E(nd interval) the miner start.

**Comment by mtbor** [comment]
Does there need to be some sort of keep alive or health check routine?

**Comment by MonaxDK** [comment]
It seems I've seen this behavior on another pool (hash refinery). At some point I saw an open megaminer and no running miner. After restarting the mega - everything works as it should.

**Comment by tutulino** [comment]
fixed last release
