### ISSUE TITLE
Think there is an issue with the devices getting passed to ngsminer & NsGpuCNMiner.exe

### ISSUE THREAD

**Issue by MikeBuzz** [tutulino/Megaminer#132]
Status: Failed

  Speed Active                      Launched Command
  ----- ------                      -------- -------
0.0 phs 00 Days 00 Hours 00 Minutes 3 Times  laymore CryptoNote\NsGpuCNMiner.exe -xpool stratum+tcp://europe.cryptonight-hub.miningpoolhub.com:20580 -xwal MikeBuzz.AMDRig -xpsw x -allpools 1  -di 012345 -mport 4060
0.0 phs 00 Days 00 Hours 00 Minutes 3 Times  win64-0.9.3\nsgminer.exe --api-listen -o stratum+tcp://yiimp.eu:4233 -u 6mQLVT2MeqW1rHRWTBoUBJWH8ipXb1Y5C1 -p c=FTC,ID=AMDRig --device 0,1,2,3,4,5 --api-port 5720 --gpu-platform 1
0.0 phs 00 Days 00 Hours 00 Minutes 3 Times  win64-0.9.3\nsgminer.exe --api-listen -o stratum+tcp://yiimp.eu:4233 -u GNWvpLEsuggx4LcdJpX8uauDQNRPTaRER5 -p c=GBX,ID=AMDRig --device 0,1,2,3,4,5 --api-port 5720 --gpu-platform 1
0.0 phs 00 Days 00 Hours 00 Minutes 3 Times  win64-0.9.3\nsgminer.exe --api-listen -o stratum+tcp://europe.hub.miningpoolhub.com:20510 -u MikeBuzz.AMDRig -p x --device 0,1,2,3,4,5 --api-port 5720 --gpu-platform 1
0.0 phs 00 Days 00 Hours 00 Minutes 3 Times  win64-0.9.3\nsgminer.exe --api-listen -o stratum+tcp://neoscrypt.mine.ahashpool.com:4233 -u 39hpJhfk5iVr97ouFFggK4k6zW5NerymxV -p c=BTC,AMDRig --device 0,1,2,3,4,5 --api-port 5720
                                             --gpu-platform 1
0.0 phs 00 Days 00 Hours 00 Minutes 3 Times  win64-0.9.3\nsgminer.exe --api-listen -o stratum+tcp://neoscrypt.us.hashrefinery.com:4233 -u 39hpJhfk5iVr97ouFFggK4k6zW5NerymxV -p c=BTC,AMDRig --device 0,1,2,3,4,5 --api-port 5720
                                             --gpu-platform 1

**Comment by MikeBuzz** [comment]
nsgminer.exe --api-listen -o stratum+tcp://yiimp.eu:4233 -u 6mQLVT2MeqW1rHRWTBoUBJWH8ipXb1Y5C1 -p c=FTC,ID=AMDRig --device 0,1,2,3,4,5 --api-port 5720 --gpu-platform 1

Returns
[2017-12-11 20:01:35] nsgminer.exe: -d: Invalid device number

**Comment by MikeBuzz** [comment]
NsGpuCNMiner.exe -xpool stratum+tcp://europe.cryptonight-hub.miningpoolhub.com:20580 -xwal MikeBuzz.AMDRig -xpsw x -allpools 1 -di 012345 -mport 4060

Returns
UNKNOWN OPTION -xpool
UNKNOWN OPTION stratum+tcp://europe.cryptonight-hub.miningpoolhub.com:20580
UNKNOWN OPTION -xwal
UNKNOWN OPTION MikeBuzz.AMDRig
UNKNOWN OPTION -xpsw
UNKNOWN OPTION x

╔════════════════════════════════════════════════════════════════╗
║            Claymore CryptoNote GPU Miner  v9.7 Beta            ║
╚════════════════════════════════════════════════════════════════╝
No pools specified! Specify at least one pool in "epools.txt" file or in "-o" parameter.

**Comment by MikeBuzz** [comment]
#133 fixed the claymore error

**Comment by MikeBuzz** [comment]
nsgminer seems to want --device 1 --device 2 and so on or -d1 -d2 etc

**Comment by tutulino** [comment]
Solved, try master brach core.ps1 and nsgminer.ps1 files

**Comment by MikeBuzz** [comment]
Devices are being reported but still seems to have issue with nsgminer, will look in to the errors later today

**Comment by MikeBuzz** [comment]
#151
