### ISSUE TITLE
MemberAlreadyExists

### ISSUE THREAD

**Issue by uprise88** [tutulino/Megaminer#134]
When starting Megaminer and at every interval switch i get this error.
What i have to do?
Thx for your work

Trascrizione avviata. File di output: .\Logs\2017-12-12_11-25-00.txt
Add-Member : Impossibile aggiungere un membro con nome "GpuPlatform" perché esiste già un membro con tale nome. Per 
sovrascrivere il membro, aggiungere il parametro Force al comando.
In C:\Users\Upris\Desktop\mining\Megaminer-master\core.ps1:175 car:50
+ ...                $_ | Add-Member GpuPlatform (Get-Gpu-Platform $_.Type)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{GroupName=107...pusETHMode=0 1}:PSObject) [Add-Member], 
InvalidOperationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand
Add-Member : Impossibile aggiungere un membro con nome "GpuPlatform" perché esiste già un membro con tale nome. Per
sovrascrivere il membro, aggiungere il parametro Force al comando.
In C:\Users\Upris\Desktop\mining\Megaminer-master\core.ps1:175 car:50
+ ...                $_ | Add-Member GpuPlatform (Get-Gpu-Platform $_.Type)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{GroupName=107...pusETHMode=0 1}:PSObject) [Add-Member], InvalidOper
   ationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

**Comment by tutulino** [comment]
You are using beta2 config.txt file on beta3.

You must remove ",Gpuplatform=n" for each group at @@gpugroups variable in config.txt

**Comment by uprise88** [comment]
Fixed thx. I forget to format the config.txt when updated to beta 3 XD
