### ISSUE TITLE
Megaminer 5.04.b selector - ahashpool

### ISSUE THREAD

**Issue by Paul-Trasca** [tutulino/Megaminer#135]
Hi. Just update do 5.04
after first menu, automatic, auto24 etc, second menu, all selections redirect to ahashpool
I just tried every option. 0,1,2,3,4,5,6,7,8 - all redirect to ahashpool

**Comment by tutulino** [comment]
Sorry, I uploaded without deletion of forced option used for development.

Download core.ps1 now, solved.
