### ISSUE TITLE
Some fun error referencing include.ps1.

### ISSUE THREAD

**Issue by mtbor** [tutulino/Megaminer#137]
Lots of this going on in logs.

Add-Member : Cannot add a member with the name "Name" because a member with that name already exists. To overwrite the 
member anyway, add the Force parameter to your command.
At C:\Users\**EDIT**\Downloads\Megaminer-master\Megaminer-master\Include.ps1:380 char:95
+ ... ent -ne $null) {$_.Content | Add-Member @{Name = $_.Name} -PassThru}}
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Algorithm=gro...Name=AHASHPOOL}:PSObject) [Add-Member], 
InvalidOperationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

**Comment by bompus** [comment]
I see this too from time to time. Tried disabling certain pools and didn't seem to make a difference.

**Comment by tutulino** [comment]
What pool/s what you running?

**Comment by mtbor** [comment]
Ahashpool, hash refinery, and multipoolhub

**Comment by tutulino** [comment]
I can not reproduce error on my machine, please test latest code from master branch and tell me if you get that error yet.

**Comment by mtbor** [comment]
It's possible this tidbit might help.  After updating to the newest version, the error changed from "Name" to "GPUPLATFORM"    I'm running nvidia cards, but in my config file I had the GPUPLATFORM bit, which I see is listed as irrelevant for nvidia.  I removed that bit, and am waiting to see if the error still occurs.

**Comment by tutulino** [comment]
use last release config.txt or delete ",gpuplatform: n" from each group on your actual config.txt

**Comment by mtbor** [comment]
Seems to be resolved by deleting GPUPLATFORM.

**Comment by mtbor** [comment]
I will try to update to the latest of everything before posting.  Seems like development is moving along quickly.

**Comment by MonaxDK** [comment]
Oh, I see such errors (Cannot add a member with the name "Name") almost every day, this happens when one or more of the pools fall off. I thought that's the way it should be :) I use MPH, hash_refinery and zpool.

**Comment by mtbor** [comment]
I looked through some logs and I do see this right before it reverted to
multipoolhub...  Now is it the pools going down, or the miner dumping the
pools?

**Comment by tutulino** [comment]
check last release please

**Comment by mtbor** [comment]
Seems to be fixed from my testing

**Comment by mtbor** [comment]
I take it back, I'm still seeing this.
