### ISSUE TITLE
Some other fun in the logs.

### ISSUE THREAD

**Issue by mtbor** [tutulino/Megaminer#138]
This bit is repeated frequently, something wrong with what's happening at the interval...  I don't see the harm it's causing, other than red text..  Any ideas?

You cannot call a method on a null-valued expression.
At C:\Users\Dean Thomson\Downloads\Megaminer-master\Megaminer-master\core.ps1:331 char:49
+ ...                              $PoolWorkers = $_.Poolworkers.tostring()
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by mtbor** [comment]
Multipoolhub, ahashpool, and hashrefinery

**Comment by vapor99** [comment]
I switched to MPH only because of these big red errors.  :)

**Comment by tutulino** [comment]
solved in last release
