### ISSUE TITLE
Some help please

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#14]
I am trying to add a new miner so I can mine skunk on AMD.
Heres what I have so far. When I run it I get "no miners"
Can you help with this? Thanks

[TPSgminer.json.txt](https://github.com/tutulino/Megaminer/files/1222752/TPSgminer.json.txt)
I had to make it an txt to paste it here. On the rig it's a .json file

**Comment by tutulino** [comment]
Where say "sgt" must say "skunk" , use real algo names else join between pools and miners can not be done

**Comment by Imaminer** [comment]
I tweaked it slightly and using your help it is now working.
This is new json
-I d was too little for me so on my rig I set it to -I 21. Depends on your cards and stuff...
{
"Path" : ".\\Bin\\TP-sgminer\\sgminer-x64.exe",
"Uri" : "https://github.com/tpruvot/sgminer/releases/download/5.3.4-eth/sgminer-x64-5.3.4-eth.7z",
"Types" : ["AMD"],
"Arguments" : "-o #PROTOCOL#://#SERVER#:#PORT# -u #LOGIN# -p #PASSWORD# --gpu-platform #GPUPLATFORM#",
"API" : "Xgminer",
"APIPort" : 4028,
"Wrap" : false,
"Dualmining":false,

"Algorithms": [
                
{"skunk":"-k skunk -I d"}        
          
]

}

THANK YOU

**Comment by Imaminer** [comment]
Ok your info did work fine but it turns out this build for Windows does not have the Skunk algo in it. I have to figure out how to build the newest version for Windows. 
I'll let ya know if I can figure this out
