### ISSUE TITLE
Groups and Api Keys and some stuff in the config.txt file

### ISSUE THREAD

**Issue by imrecsoka** [tutulino/Megaminer#140]
Hi i want to know, do i need to use groups? or can i just delete the lines completely?
Also Api keys? i dont believe i need those items?

I normally delete all the pool files and keep the miningpoolhub file only, is this find also?

**Comment by tutulino** [comment]
you must define at least one group to indicate MM number of cards.

ApiKeys can delete, but no wallet info if you use MPH or Suprnova

Not necessary delete pools files, you can run only what you want in your batch file.
