### ISSUE TITLE
Miner fails to resume mining after donation interval. 

### ISSUE THREAD

**Issue by mtbor** [tutulino/Megaminer#145]
I check on my miner and it was idle, when I looked through the logs, the last mining it had done was the donation interval.

**Comment by tutulino** [comment]
I just test donation mechanism and seems to work well. Idle is closed? no miners opened?

**Comment by caxep23** [comment]
no miner opened

**Comment by caxep23** [comment]
Next Interval:  180 secs
-------------------------------------------Miner 5.0--------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
  (E)nd Interval   (P)rofits    (C)urrent    (H)istory    (W)allets                       |
-----------------------------------------------------------------------------------------------------------------------
--------------------------------------------------HISTORY------------------------------------------------------------
Running Mode: Automatic


   Status: Idle

               Speed Active                      Launched Command
               ----- ------                      -------- -------

**Comment by caxep23** [comment]
problem solved
    $DonationInterval = $true
                $UserName = "tutulino"
                $WorkerName = "Megaminer"
                $CoinsWallets=@{} 
                $CoinsWallets.add("BTC","1AVMHnFgc6SW33cwqrDyy2Fug9CsS8u6TM")
                

                $NextInterval=$DonateTime *60

                $Algorithm=$null
                $PoolsName="mining_pool_hub" ---------need delete
                $CoinsName=$null
                $MiningMode="Automatic"
