### ISSUE TITLE
claymore eth miner error time

### ISSUE THREAD

**Issue by ghost** [tutulino/Megaminer#146]
error benchmark  fo timer in claymore eth miner,work interval script in freezes

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.447 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.447 Mh/s
 SC - Total Speed: 404.037 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 404.037 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 17.128 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.465 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.465 Mh/s
 SC - Total Speed: 404.366 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 404.366 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 17.302 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.446 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.446 Mh/s
 SC - Total Speed: 404.020 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 404.020 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 17.418 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.448 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.448 Mh/s
 SC - Total Speed: 404.063 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 404.063 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 17.482 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.444 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.444 Mh/s
 SC - Total Speed: 403.995 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 403.995 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 17.534 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.462 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.462 Mh/s
 SC - Total Speed: 404.323 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 404.323 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 17.881 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.439 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.439 Mh/s
 SC - Total Speed: 403.893 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 403.893 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 18.021 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

ETH: 12/14/17-13:22:02 - New job from europe.ethash-hub.miningpoolhub.com:20585
ETH - Total Speed: 22.443 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.443 Mh/s
 SC - Total Speed: 403.982 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 403.982 Mh/s

GPU #0: Ellesmere, 4096 MB available, 32 compute units
ETH - Total Speed: 22.455 Mh/s, Total Shares: 1, Rejected: 0, Time: 00:03
ETH: GPU0 22.455 Mh/s
 SC - Total Speed: 404.195 Mh/s, Total Shares: 4, Rejected: 0
 SC: GPU0 404.195 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 18.551 Mh/s
Pool switches: ETH - 0, SC - 0
Current ETH share target: 0x00000000ffb24c4e (diff: 4300MH), epoch 53(1.41GB)
Current SC share target: 0x0000000012533fe6 (diff: 60GH)
GPU0 t=75C fan=100%

**Comment by tutulino** [comment]
Please, test master branch code, I thik i found bug source.
