### ISSUE TITLE
Bad math calculating profit for Keccak on ITALYIIMP

### ISSUE THREAD

**Issue by bompus** [tutulino/Megaminer#149]
If I enable ITY on Automatic mode, I am seeing KECCAK show up at 0.00670 BTC/Day ( $111/day as of right now ).

However, after leaving it running for 10 hours, then checking my stats on ITALYIIMP, I've made almost 100x less than expected. I have 0.00004293 BTC.

Could you check on this. Perhaps keccak needs a divisor of 100, or maybe only on this pool?

**Comment by MikeBuzz** [comment]
this is also happening on yiimp, so think it must be something changed their site or exchange

**Comment by MikeBuzz** [comment]
sorry it was keccakc on yiimp

**Comment by cjroepe** [comment]
Also seeing that here...

**Comment by tutulino** [comment]
If it happens on distinct pools smells like exchanges are reporting pools high value for any coin of keccak algo, all pools use that exchange rate and send us bad data.
