### ISSUE TITLE
Pool is dropped on API failure

### ISSUE THREAD

**Issue by mtbor** [tutulino/Megaminer#152]
Once a pool API fails to respond, it's out, and only a restart will get it working again..  I run ahashpool, hashrefinery, and multipoolhub...  I frequently come back to only multipoolhub working because at some point the miner did not get a response from the API (yes I know my interval is stupid short, I'm lengthening it out to see if that helps)
Here's what I see in the logs:

PS>TerminatingError(Invoke-WebRequest): "The operation has timed out."
PS>TerminatingError(Invoke-WebRequest): "The operation has timed out."
AHASHPOOL API NOT RESPONDING...ABORTING
Next Interval:  59 secs
^^^^^ This signaled the death of ahashpool....

Oddly enough the below signaled the death of hash_refinery, even though it isn't mentioned in the error...  I'm submitting the surroundings for reference:

GroupName Pool   Algorithm Miner         Command
--------- ----   --------- -----         -------
Rig1070   H.RFRY NEOSCRYPT CcminerKlaust Bin\NVIDIA-CcminerKlaust\ccminer.exe -o
                                         stratum+tcp://neoscrypt.us.hashrefinery.com:4233 -u
                                         **edit** -p c=BTC,1 -R 10 -r 4 -b 2500 -d 0 -a
                                         Neoscrypt
GpuId Gpu              Gpu%  Mem%  Temp FanSpeed Power                pstate ClockGpu  ClockMem
----- ---              ----  ----  ---- -------- -----                ------ --------  --------
    0 GeForce GTX 1070  99 %  91 %  63   85 %     200.00 W / 207.20 W  P2     2062 MHz  4176 MHz

PS>TerminatingError(Invoke-WebRequest): "The operation has timed out."
PS>TerminatingError(Invoke-WebRequest): "The operation has timed out."
AHASHPOOL API NOT RESPONDING...ABORTING
PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (524) Origin Time-out."
Next Interval:  59 secs
-------------------------------------------   MegaMiner 5.0 beta 4   --------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
  (E)nd Interval   (P)rofits    (C)urrent    (H)istory    (W)allets                       |
-----------------------------------------------------------------------------------------------------------------------
GroupName    Speed BTC/Day USD/Day Algorithm Coin  Miner        Pool Location PoolWorkers
---------    ----- ------- ------- --------- ----  -----        ---- -------- -----------
Rig1070   0.0 ph/s 0.00000    0.00 LYRA2Z    zcoin ccminerDjm34 MPH  US

**Comment by MikeBuzz** [comment]
am seeing the same issue with ahash and nanopool

**Comment by Cryptominer937** [comment]
I have only had this happen with zpool and it only happens if more than one rig tries to get api data less than 30 sec apart. Easy solution would be the ability to enable farm mode were one master pc can fetch the api data for all rigs once every 5 Min.

**Comment by tutulino** [comment]
Great clue, is a api saturation limit, not necessary something
sophisticated, only that after wait MM gets alive again

2017-12-15 21:28 GMT+01:00 Cryptominer937 <notifications@github.com>:

**Comment by tutulino** [comment]
Please, test master branch code, I thik i found bug source.

**Comment by tutulino** [comment]
fixed last release
