### ISSUE TITLE
lyra2re2 excavator

### ISSUE THREAD

**Issue by ghost** [tutulino/Megaminer#156]
please add  latest excavator, algo lyra2v2 faster 20-30%  nvidia

**Comment by tutulino** [comment]
I´m testing lyra2v2 with excavator and It dont want to work against zpool or ahaspool.

Perhaps only works against NH?

**Comment by caxep23** [comment]
testin latest excavator multipoolminer  pool ahash gtx 1060 3gb

**Comment by tutulino** [comment]
I always get "conection lost message" please post your json file

**Comment by caxep23** [comment]
using module ..\Include.psm1

$Threads = 2

$Path = ".\Bin\Excavator\excavator.exe"
$Uri = "https://github.com/nicehash/excavator/releases/"

$Commands = [PSCustomObject]@{
    "lyra2rev2" = @() #Lyra2RE2
    "sia" = @() #sia
}

$Name = Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName
$Port = 3456 + (2 * 10000)

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | ForEach-Object {
    try {
        if ((Get-Algorithm $_) -ne "Decred" -and (Get-Algorithm $_) -ne "Sia") {
            if ((Test-Path (Split-Path $Path)) -and $Pools.$(Get-Algorithm $_).Host -and (Get-Command "Resolve-DnsName" -ErrorAction Ignore)) {
                [PSCustomObject]@{time = 0; commands = @([PSCustomObject]@{id = 1; method = "algorithm.add"; params = @("$_", "$((Resolve-DnsName $Pools.$(Get-Algorithm $_).Host -ErrorAction Stop).IPAddress | Select-Object -First 1):$($Pools.$(Get-Algorithm $_).Port)", "$($Pools.$(Get-Algorithm $_).User):$($Pools.$(Get-Algorithm $_).Pass)")})},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "0") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "1") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "2") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "3") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "4") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "5") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 10; loop = 10; commands = @([PSCustomObject]@{id = 1; method = "algorithm.print.speeds"; params = @("0")})} | ConvertTo-Json -Depth 10 | Set-Content "$(Split-Path $Path)\$($Pools.$(Get-Algorithm $_).Name)_$(Get-Algorithm $_)_$($Threads)_Nvidia.json" -Force -ErrorAction Stop
            }

            [PSCustomObject]@{
                Type = "NVIDIA"
                Path = $Path
                Arguments = "-p $Port -c $($Pools.$(Get-Algorithm $_).Name)_$(Get-Algorithm $_)_$($Threads)_Nvidia.json -na"
                HashRates = [PSCustomObject]@{$(Get-Algorithm $_) = $Stats."$($Name)_$(Get-Algorithm $_)_HashRate".Week}
                API = "NiceHash"
                Port = $Port
                Wrap = $false
                URI = $Uri
            }
        }
        else {
            if ((Test-Path (Split-Path $Path)) -and $Pools."$(Get-Algorithm $_)NiceHash".Host -and (Get-Command "Resolve-DnsName" -ErrorAction Ignore)) {
                [PSCustomObject]@{time = 0; commands = @([PSCustomObject]@{id = 1; method = "algorithm.add"; params = @("$_", "$((Resolve-DnsName $Pools."$(Get-Algorithm $_)NiceHash".Host -ErrorAction Stop).IPAddress | Select-Object -First 1):$($Pools."$(Get-Algorithm $_)NiceHash".Port)", "$($Pools."$(Get-Algorithm $_)NiceHash".User):$($Pools."$(Get-Algorithm $_)NiceHash".Pass)")})},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "0") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "1") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "2") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "3") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "4") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "5") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 10; loop = 10; commands = @([PSCustomObject]@{id = 1; method = "algorithm.print.speeds"; params = @("0")})} | ConvertTo-Json -Depth 10 | Set-Content "$(Split-Path $Path)\$($Pools."$(Get-Algorithm $_)NiceHash".Name)_$(Get-Algorithm $_)_$($Threads)_Nvidia.json" -Force -ErrorAction Stop
            }

            [PSCustomObject]@{
                Type = "NVIDIA"
                Path = $Path
                Arguments = "-p $Port -c $($Pools."$(Get-Algorithm $_)NiceHash".Name)_$(Get-Algorithm $_)_$($Threads)_Nvidia.json -na"
                HashRates = [PSCustomObject]@{"$(Get-Algorithm $_)NiceHash" = $Stats."$($Name)_$(Get-Algorithm $_)NiceHash_HashRate".Week}
                API = "NiceHash"
                Port = $Port
                Wrap = $false
                URI = $Uri
            }
        }
    }
    catch {
    }
}

**Comment by caxep23** [comment]
x4 10603gb 143 mh

**Comment by tutulino** [comment]
This is miner file, I´m talking about json generated as input for excavator, its name must be like "Algorithm_nvidia.json" and is content in MPM root or excavator folder

**Comment by tutulino** [comment]
This is mine
[
	{"time":1,"commands":[
		{"id":1,"method":"algorithm.add","params":["lyra2rev2","lyra2v2.mine.ahashpool.com:4533","1AVMHnFgc6SW33cwqrDyy2Fug9CsS8u6TM:x"]}
	]},
	{"time":2,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","1"]}
	]},
	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
	
]

**Comment by caxep23** [comment]
[
    {
        "time":  0,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "algorithm.add",
                             "params":  [
                                            "lyra2rev2",
                                            "13.228.127.224:4533",
                                            "1LjWtLA4TCqzHNZXmGBQLqcsBAYXYPYsB9:1060dom3,c=BTC"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "0"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "0"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "1"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "1"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "2"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "2"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "3"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "3"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "4"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "4"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "5"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "5"
                                        ]
                         }
                     ]
    },
    {
        "time":  10,
        "loop":  10,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "algorithm.print.speeds",
                             "params":  [
                                            "0"
                                        ]
                         }
                     ]
    }
]

**Comment by caxep23** [comment]
[ahash_Lyra2RE2_2_Nvidia.json.txt](https://github.com/tutulino/Megaminer/files/1564029/ahash_Lyra2RE2_2_Nvidia.json.txt)

**Comment by tutulino** [comment]
Thanks, I see now where problem is

2017-12-15 22:11 GMT+01:00 caxep23 <notifications@github.com>:

**Comment by caxep23** [comment]
I also could not run megaminertherefore I wrote to you

**Comment by caxep23** [comment]
and problem Donation.ctr= 0 all time = 0

**Comment by tutulino** [comment]
sorry, I dont understand

2017-12-15 22:34 GMT+01:00 caxep23 <notifications@github.com>:

**Comment by caxep23** [comment]
the value in the file Donation.ctr is always 0

**Comment by tutulino** [comment]
Fixed, thx a lot

2017-12-15 22:40 GMT+01:00 caxep23 <notifications@github.com>:
