### ISSUE TITLE
Unknown error message

### ISSUE THREAD

**Issue by cjroepe** [tutulino/Megaminer#158]
Tutulino,

Not sure what is happening here but I get it often.  Everything still works but I'm sure this will scare a lot of folks away

![image](https://user-images.githubusercontent.com/24252766/34023360-1d0fcf34-e10a-11e7-8918-2764d2b60471.png)

**Comment by tutulino** [comment]
You are using an old config.txt file format, delete ",gpuplatform=n" for each @@gpugroup

**Comment by cjroepe** [comment]
@@GPUGROUPS=[{"GroupName" : "1070ti","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0,3,4,5"} , {"GroupName" : "1070","Type":"NVIDIA","GpuPlatform":"0","Gpus":"1,2"} ]

I'm using the exact code from your 5.0b4 version

**Comment by tutulino** [comment]
set this:

@@gpugroups=[{"GroupName" : "1070ti","Type":"NVIDIA","Gpus":"0,3,4,5"} , {"GroupName" : "1070","Type":"NVIDIA","Gpus":"1,2"} ]

**Comment by cjroepe** [comment]
Awesome, works, thanks...

You may want to update the examples in the config file so others get it correct.
