### ISSUE TITLE
faster phi miner

### ISSUE THREAD

**Issue by ghost** [tutulino/Megaminer#164]
[CcminerSpModLux.zip](https://github.com/tutulino/Megaminer/files/1564717/CcminerSpModLux.zip)

**Comment by tutulino** [comment]
Need download URL

**Comment by caxep23** [comment]
5 minuts

**Comment by caxep23** [comment]
{
"Path" : ".\\Bin\\NVIDIA-CcminerXevan\\ccminer_x86.exe",
"ExtractionPath" : ".\\Bin\\NVIDIA-CcminerXevan\\",
"Uri" : "https://github.com/krnlx/ccminer-xevan/releases/download/0.1/ccminer_x86.exe",
"Types" : ["NVIDIA"],
"Arguments" : "-o #PROTOCOL#://#SERVER#:#PORT# -u #LOGIN# -p #PASSWORD# -R 10 -r 4 -b #APIPORT# -d #DEVICES# #ALGORITHMPARAMETERS# ",
"API" : "Ccminer",
"Wrap" : false,
"Dualmining":false,
"PrelaunchCommand":"",
"Algorithms": [
                {"xevan":"-a xevan"}
                
              ]
}

**Comment by tutulino** [comment]
Sorry, I dont see before, I suspect this is one of spmod sold miners, I disagree with spmod reselling free code, but I can not publish this miner.
If it is free miner, I need creator source or info.

**Comment by caxep23** [comment]
i don know creator source or info (

**Comment by tutulino** [comment]
As you can understand its a little risky add unknown source miners....
