### ISSUE TITLE
log problemm

### ISSUE THREAD

**Issue by ghost** [tutulino/Megaminer#166]
Add-Member : Не удается добавить элемент с именем "Name", так как элемент с таким именем уже существует. Чтобы все равно
 перезаписать этот элемент, добавьте в команду параметр Force.
C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1:721 знак:95
+ ... ent -ne $null) {$_.Content | Add-Member @{Name = $_.Name} -PassThru}}
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Algorithm=Qub...ining_Pool_Hub}:PSObject) [Add-Member], InvalidOperat
ionException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand
Add-Member : Не удается добавить элемент с именем "Name", так как элемент с таким именем уже существует. Чтобы все равн
о перезаписать этот элемент, добавьте в команду параметр Force.
C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1:721 знак:95
+ ... ent -ne $null) {$_.Content | Add-Member @{Name = $_.Name} -PassThru}}

**Comment by tutulino** [comment]
What pools and release?
