### ISSUE TITLE
KECCAK                          CcminerKlaust     2,5 gh/s             0,03325  653,82   2,00%          ZPOOL     US

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#172]
KECCAK                          CcminerKlaust     2,5 gh/s             0,03325  653,82   2,00%          ZPOOL     US

**Comment by tutulino** [comment]
repeat benchmark deleting stats folder file

**Comment by uprise88** [comment]
i have same issue, deleted stats for keccak, repeated bench and there we go....

<blockquote class="imgur-embed-pub" lang="en" data-id="a/AdKEV"><a href="//imgur.com/AdKEV"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by uprise88** [comment]
i think ive found the issue

https://bitcointalk.org/index.php?topic=1751272.msg26485785#msg26485785

**Comment by tutulino** [comment]
Fixed next release

Add bold text to zpool.ps1 file

switch ($Zpool_Algo){
    "X11"{$Divisor *= 1000}
    "qubit"{$Divisor *= 1000}
    "quark"{$Divisor *= 1000}
    *"keccak"{$Divisor *= 1000}*
}


2017-12-17 17:01 GMT+01:00 uprise88 <notifications@github.com>:
