### ISSUE TITLE
Keccak algo: BTC per GH instead of MH

### ISSUE THREAD

**Issue by Borridaph** [tutulino/Megaminer#174]
:)
Keccak is best profit now: https://bitcointalk.org/index.php?topic=1751272.3260

**Comment by tutulino** [comment]
Fixed next release

Add bold text to zpool.ps1 file

switch ($Zpool_Algo){
    "X11"{$Divisor *= 1000}
    "qubit"{$Divisor *= 1000}
    "quark"{$Divisor *= 1000}
    **"keccak"{$Divisor *= 1000}***
}

**Comment by Borridaph** [comment]
OK
you lost «*»
