### ISSUE TITLE
latest mster release speed 0

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#175]
GroupName    Speed BTC/Day USD/Day Algorithm Coin Miner            Pool  Location PoolWorkers
---------    ----- ------- ------- --------- ---- -----            ----  -------- -----------
NVIDIA    0,0 ph/s 0,00000    0,00 NIST5          ccminerAlexisHSR AHASH US       897

----------------------------------------------------PROFITS------------------------------------------------------------
                                                                                (B)est Miners/All       (T)op 25/All

   GroupName: NVIDIA

Algorithm         Coin             Miner             Speed              BTC/Day USD/Day PoolFee MinerFee Pool      Loca
                                                                                                                   tion
---------         ----             -----             -----              ------- ------- ------- -------- ----      ----
NIST5                              ccminerAlexisHSR  118,9 mh/s         0,00112   21,33   1,00%          AHASH     US

**Comment by ALLMINER** [comment]
1 interval normal  2,3,4 interval speed=  0

**Comment by tutulino** [comment]
Always get that?, I can nto reproduce in my machine

**Comment by ALLMINER** [comment]
if there is a change in the miner, then the speed is displayed ok, else 0

**Comment by ALLMINER** [comment]
and after press "E"

**Comment by tutulino** [comment]
Test master branch code, it seems api port problem, last code has changed this one

**Comment by ALLMINER** [comment]
all ok
