### ISSUE TITLE
CCminer Polytimos Observation:  Add Nanashi 2.2

### ISSUE THREAD

**Issue by cjroepe** [tutulino/Megaminer#181]
Lyra2v2 is a popular algo at the moment and my 1070ti rig prefers the benchmark it obtained using the ccminer Plytimos fork.

I've noticed that the Polytimos version does not produce the hashrate it says it is running at.  It typically will achieve half of the actual rate.

I think that the Nanashi 2.2 r2 ccminer is much more robust ccminer for lyra2v2 and other algos and would be an excellent add.

**Comment by tutulino** [comment]
Uploaded to master branch.
