### ISSUE TITLE
donate

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#182]
$DonationInterval = $true
                $UserName = "tutulino"
                $WorkerName = "Megaminer"
                $CoinsWallets=@{} 
                $CoinsWallets.add("BTC","1AVMHnFgc6SW33cwqrDyy2Fug9CsS8u6TM")

do not work replace username and workername

**Comment by tutulino** [comment]
seems to work well for me

**Comment by ALLMINER** [comment]
$DonationInterval = $true
            $NextInterval=$DonateTime *60
            
            $UserName = "tutulino"
            $WorkerName = "Megaminer"
            $CoinsWallets=@{}
            $Algorithm=$null
            $PoolsName="mining_pool_hub"
            $CoinsName=$null
            $MiningMode="Automatic"

**Comment by ALLMINER** [comment]
work normally
