### ISSUE TITLE
Issue after interval expires

### ISSUE THREAD

**Issue by MikeBuzz** [tutulino/Megaminer#183]
![image](https://user-images.githubusercontent.com/941624/34119215-43526ec4-e419-11e7-8778-7c994115f521.png)

As you can see the details are all 0 this only happens, whne the interval ends and the algo being mined is not changed, this has only happened since the APIPORT setting changed, i am guessing that when the internal expires its trying to connect using different port

**Comment by MikeBuzz** [comment]
then at the end of the 2nd interval the miner is closed and started again

**Comment by tutulino** [comment]
I can´t get that error, I have uploaded core.ps1 with some changes for api port asignation.

**Comment by Borridaph** [comment]
At me the miner each time is restarted after the termination of an interval.
In the previous version of MegaMiner, the miner worked continuously if the profit did not change.

**Comment by MikeBuzz** [comment]
I can replicated this issue

set the interval to something like 60
then chose a pool, i am using nanopool, then chose a coin using -coinsname in the batch file

after the 1st 60sec you will stop getting the stats updating at the top of the page, after the second 60 the miner will restart every 60 sec,

will update to latest master and test again

**Comment by MikeBuzz** [comment]
Just tested with latest master, issue seems to be resolved

Keep up the great work, this project is awesome
