### ISSUE TITLE
Wrong set of data displayed if Multiple GPU Groups are using same miner

### ISSUE THREAD

**Issue by mplachter** [tutulino/Megaminer#184]
https://github.com/tutulino/Megaminer/blob/08041120c935aab1bf04349b0b2f6e2ee9f640e7/Miners/N-CcminerPolytmos.json#L8

This is caused when hardcoding `APIPort` setting in the miner json objects.

**Comment by tutulino** [comment]
Upsss, solved next release

Thx

**Comment by mplachter** [comment]
thanks keep up the good work
