### ISSUE TITLE
"OpenCl error -1: DeviceNotFound." fo amd

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#186]
Исключение при вызове "GetDeviceIDs" с "2" аргументами: "OpenCl error -1: DeviceNotFound."
C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1:317 знак:54
+ ... ngth;$i++) {$OCLDevices+=([OpenCl.Device]::GetDeviceIDs($OCLPlatforms ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : OpenClException

**Comment by tutulino** [comment]
post gpulist result

**Comment by ALLMINER** [comment]
puId Type   Name
----- ----   ----
    0 NVIDIA NVIDIA-SMI couldn't find nvml.dll library in your system. Please make sure that the NVIDIA Display Driver
             is properly installed and present in your system.
    1 NVIDIA Please also try adding directory that contains nvml.dll to your system PATH.


./OverdriveN : Имя "./OverdriveN" не распознано как имя командлета, функции, файла сценария или выполняемой программы.
Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:1 знак:1
+ ./OverdriveN
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./OverdriveN:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


GpuId Type Name      Gpu% Temp FanSpeed ClockGpu ClockMem
----- ---- ----      ---- ---- -------- -------- --------
    0 AMD  Ellesmere


Для продолжения нажмите любую клавишу . . .

**Comment by tutulino** [comment]
nvml.dll seems problem of driver installation, have you tried reinstalling nvidia drivers?

**Comment by scavern** [comment]
I am having the exact same issue as above. I have AMD RX 480 installed (Ellesmere) and there are no Nvidia GPUS in this rig.

**Comment by tutulino** [comment]
try last release
