### ISSUE TITLE
Continuous Benchmarking

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#189]
The current process of Benchmarking is just a snapshot of the performance measured at the time of running the Benchmark. However, hashrate seems to change over time.
Suggestion: use the standard mining process as a Benchmark. Specifically, after an initial benchmark run MM as usual but compare the average hashrate with the numbers from the benchmark. If the two differ (by a specific %), then replace the benchmark number by the average hashrate from the last run.

To prevent this would favor specific algo's too much over time, older Stats also need to be deleted (e.g. when not used for more than one month, set as parameter?). This will force MM to run the Benchmark again for those algo's.

This approach has as main advantage that there's no need for Benchmarking again after: GPU driver upgrade, change of clock speeds, new miner software, etc...

**Comment by tutulino** [comment]
Incorporated in last release

**Comment by 1001rapid** [comment]
What about the fact that I use manual input of the benchmark in order to exclude algorithms and miners that lead to a driver reboot or do not some graphics cards support?

**Comment by MikeBuzz** [comment]
If you want to exclude a miner remove the file from the miners folder, if you want to exclude an algorithm then use the algorithm switch in your batch file

**Comment by 1001rapid** [comment]
Yes, it only works if you do not use more than one GPU-group

**Comment by 1001rapid** [comment]
In any case, I'll try, maybe in the new version, my way of disabling the miners for a separate group of video cards will also work

**Comment by tutulino** [comment]
Stats file is more complicated than before, but you can write manually taking another one as pattern.

Speeds/ power  are average of all reads in file having timerunning>100 (avoid starting speed penalization)

 {
        "Speed":  25956000,
        "SpeedDual":  0,
        "Power":  122,
        "Date":  "lunes, 15 de enero de 2018 12:25:30",
        "Benchmarking":  true,
        "TimeRunning":  101
    }

**Comment by eMTee72** [comment]
Sorry to come back on an old & closed topic. The Continuous benchmarking seems to have improved things (more realistic numbers), but I've 2 additional questions:

1. Not sure if this has been implemented too: "To prevent this would favor specific algo's too much over time, older Stats also need to be deleted (e.g. when not used for more than one month, set as parameter?). This will force MM to run the Benchmark again for those algo's."
2. When a miner runs into problems, the speed all of a sudden increases to an unrealistic value. (e.g. normally 23 MH/s --> 4 PH/s). In those cases, the unrealistic value should not be used as the new benchmark value...
