### ISSUE TITLE
Issues with new version - Window cannot be taller

### ISSUE THREAD

**Issue by MikeBuzz** [tutulino/Megaminer#19]
Window cannot be taller than 63.
Parameter name: value.Height
Actual value was 80."
At ..\Megaminer-master\Include.ps1:721 char:5
+     $psWindow.WindowSize= $newSize
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by tutulino** [comment]
Fixed in next released
