### ISSUE TITLE
Show for each algo only the best combination

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#191]
My profits screen shows EQUIHASH twice. Why would I be interested in seeing the same algo multiple times (even when it's with a different coin)? Aren't we all interested to see the top-performer for each algo?

Algorithm  Coin    Miner              Speed      BTC/Day EUR/Day PoolFee MinerFee Pool  Location
---------  ----    -----              -----      ------- ------- ------- -------- ----  --------
TRIBUS             N-CcminerTpruvot   67.6 mh/s  0.00063    9.01   1.00%    0.00% AHASH US
LYRA2V2            N-CcminerPolytmos  45.6 mh/s  0.00047    6.66   1.00%          AHASH US
NIST5              N-ccminerAlexis    51.3 mh/s  0.00046    6.57   1.00%    0.00% AHASH US
HSR                N-ccminerAlexisHSR 13.7 mh/s  0.00044    6.24   1.00%    0.00% AHASH US
VELTOR             N-ccminerAlexisHSR 39.4 mh/s  0.00039    5.52   2.00%    0.00% ZPOOL US
PHI                N-CcminerTpruvot   20.9 mh/s  0.00038    5.50   1.00%    0.00% AHASH US
X17                N-ccminerPalgin    8.4 mh/s   0.00038    5.42   1.00%          AHASH US
NEOSCRYPT          N-CcminerKlaust    1.2 mh/s   0.00035    4.96   1.00%          AHASH US
EQUIHASH   zencash N-Dtsm             579.0 h/s  0.00034    4.92   0.90%    2.00% MPH   Europe
EQUIHASH   zcash   N-Dtsm             579.0 h/s  0.00034    4.91   0.90%    2.00% MPH   Europe
TIMETRAVEL         N-ccminer-2.2      29.1 mh/s  0.00034    4.89   1.00%    0.00% AHASH US
LBRY               N-Excavator        333.1 mh/s 0.00034    4.86   1.00%    0.00% AHASH US

**Comment by tutulino** [comment]
Fixed Next Release

thx

**Comment by eMTee72** [comment]
Just wanted to let you know I really appreciate all the work you put in Megaminer!
