### ISSUE TITLE
testing 5.1

### ISSUE THREAD

**Issue by gregfromo** [tutulino/Megaminer#194]
hi,

great job tutulino!

the ccminer palgin is no longer on github, download fails. I can upload it somewhere, if you want. I also build 2.2.4 from cuda-9 branch against all cuda from 6.5 on in x64 and x86, I can also upload somewhere, if you want.

I get sometimes erros and only AHASH is available with this startup.bat

`
powershell -version 5.0 -noexit -executionpolicy bypass -command "&.\core.ps1   -Miningmode Automatic -PoolsName HASH_REFINERY,AHASHPOOL -Algorithm nist5,phi,neoscrypt,tribus,skunk,x11gost,groestl `

**Comment by MonaxDK** [comment]
Faced a similar problem, HashRefinery did not want to run in auto24h mode. Apparently the problem is in writing the name of the pool. 
"-PoolsName hash_refinery" didnt work, but "-PoolsName Hash_Refinery" is working

**Comment by gregfromo** [comment]
thx for tips. I tried with space and casesensitve, but both don't work. It would surprise if it should work this way, I copied the names from 4.8 sample bat with all pools. 
the 1st benchmark run on new install with empty stats folder is ok, on 2ns the quick scrolling powershell errors appear, then only ahash in the list of pools. what else info is needed to find the bug?

**Comment by tutulino** [comment]
I think it is fixed, test master branch code

YOU MUST ADD THIS VARIABLES TO CONFIG.TXT (see changelog/new config.txt)

@@PERCENTTOSWITCH=10
@@DELAYCLOSEMINERS=20

**Comment by gregfromo** [comment]
the fix worked, but now we have problem #211 see my info there. 

may I suggest to add to gatelessgate nist5 config "--intensity 20", then it's much faster.

Isn't it possible to reduce the needed miners, e.g. 5.6.1-phi could replace "normal" sgminer, or did I miss something about this?
 
skunk-prospector is not working with my AMD rig in new version, maybe usefull to replace it with sgminer-polytimos and lose some % speed? I didn't test sofar, just loud thinking ;)

also it would be nice to have a "-nologs" in startup, instead to change it every time manually.

when is the devfee mined, is it possible to force it?

**Comment by tutulino** [comment]
Please open a issue for each question/problem, so is easy for all to follow.
