### ISSUE TITLE
zpool - equihash

### ISSUE THREAD

**Issue by uprise88** [tutulino/Megaminer#195]
Hi, can u help me pls? I cant figure out how to mine equihash algo whit zpool....

**Comment by tutulino** [comment]
you want ONLY mine equihash on zpool?

**Comment by uprise88** [comment]
sorry tutilino for pestering, i was wondering why the miner dont switch for equihash when current estimate is high when i went read * values in mBTC/MH/day, per PH for sha256 & GH for scrypt, blake, decred, x11, quark, qubit, kS for equihash.

im sorry for botherig.

**Comment by uprise88** [comment]
i think i have to add "equihash" {$Divisor /= 1000} to Zpool.ps1

am i wrong?
