### ISSUE TITLE
Add-Member: Cannot add member with name already ...  because already exists (not solved).

### ISSUE THREAD

**Issue by mtbor** [tutulino/Megaminer#196]
I told you wrong, this isn't solved yet.

Add-Member : Cannot add a member with the name "Name" because a member with that name already exists. To overwrite the
member anyway, add the Force parameter to your command.
At C:\Users\*EDIT*\Downloads\Megaminer-master(12212017)\Megaminer-master\Include.ps1:878 char:95
+ ... ent -ne $null) {$_.Content | Add-Member @{Name = $_.Name} -PassThru}}
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Algorithm=Myr...ining_Pool_Hub}:PSObject) [Add-Member], InvalidOper
   ationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

**Comment by mtbor** [comment]
Mining_pool_hub, ahashpool, hash_refinery.....  Running release from today (5.1?)  Copied stats folder, config.txt, and start.bat....  As well as the BIN directory as my upgrade procedure...

Not sure what other information would be helpful...

**Comment by gregfromo** [comment]
hi,
now I can confirm that this is the same error that I have from my reported issue #194

**Comment by mtbor** [comment]
I see your thread there..  One thing we have in common is we are both
mining to miningpoolhub, unsure if that is coincidence or a clue.

**Comment by tutulino** [comment]
I think it is fixed, test master branch code

YOU MUST ADD THIS VARIABLES TO CONFIG.TXT (see changelog/new config.txt)

@@PERCENTTOSWITCH=10
@@DELAYCLOSEMINERS=20
