### ISSUE TITLE
NiceHash is come back

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#197]
Hi!
I did not pay attention to this earlier, but now I saw that there is no file NiсeHash.pc1 in the folder "Pools".
Can you add it?

**Comment by mtbor** [comment]
Nicehash, Ugh.

**Comment by eMTee72** [comment]
See #193 for the same.

**Comment by 1001rapid** [comment]
@eMTee72 I saw it and don't find this file. I took the file from another fork (MikeBuzz) and and tried use NiceHash.pc1 from MultiPoolMiner. It's not working. And I do not understand why I have to look for spare parts somewhere else.

**Comment by eMTee72** [comment]
It still exists under v4.8 of MegaMiner. Look over here: https://github.com/tutulino/Megaminer/tree/18a3d27086ea038606f95bbd265d3cb3e3f80a5a/Pools

**Comment by 1001rapid** [comment]
@eMTee72 Thank you. I really tried to find previous releases, but did not understand how it's done. I'll try this file in the evening, I hope it works.

**Comment by MikeBuzz** [comment]
There is a change needed for it to work, will submit a pr in 2 mins

**Comment by MikeBuzz** [comment]
#199
