### ISSUE TITLE
False donation

### ISSUE THREAD

**Issue by czjlj** [tutulino/Megaminer#198]
The account cant switch in the donation time.Take care codes pls.

**Comment by tutulino** [comment]
It seems to work well here, whats the problem?

**Comment by czjlj** [comment]
It used my address not yours in the time donation.

**Comment by tutulino** [comment]
various releases ago was a problem but last one seems work well, I have tested minutes ago and can´t find any bug, donation interval is activated and username is changed to specified inside code for donation (I have changed to other different to test).

Are you in 5.X release?

**Comment by ALLMINER** [comment]
I was helped to remove $CoinsWallets=@{}

**Comment by czjlj** [comment]
Have you tested on zpool?Unable to work normally.The latest version 5.1.

**Comment by tutulino** [comment]
Test and test and all seems to work

**Comment by podlbo** [comment]
How the donation metod works - Is value 0 means donation is disabled, or 
it meens theat in this case MM activate deafult value (dont know 5 min?)...

**Comment by czjlj** [comment]
I would like donate to your address,but the megaminer is always use my.So I have no idea :)

**Comment by gregfromo** [comment]
I changed to donate=1440 to see if it works, but it's till mining to the pools I configured in my start.bat and to my BTC address.
what is wrong?

**Comment by tutulino** [comment]
Please, check last code from master, if you want to force donation interval edit donation.ctf file and put 1440 or greater (this are minutes without donating)

**Comment by czjlj** [comment]
Should not limit the pool for donation.I delete the pool files except miningpoolhub and zpool,so it is unsuccessful.

**Comment by tutulino** [comment]
That is the problem, for short interval like donation is better to mine in no PPLS pool like nicehash, also if donation goes to different pools minimum pay threshold is never reached (there is few donators).

I will make some changes to solve this.

Thanks all.
