### ISSUE TITLE
Server Location

### ISSUE THREAD

**Issue by Nebiforever** [tutulino/Megaminer#2]
Thanks for the nice sum up for nvidia rigs. Works good but for benchmarking, in claymore it connects to usa servers even i setup europe in config.txt.  havent seen the normal run mode yet.

and besides in read me file, i read the 100 secs swap time suggestion for benchmarking. make it at least 200 secs because some algoritms takes time to speed up and some times 100 secs isnt enough for that

**Comment by Gothic860** [comment]
y same here.

**Comment by Gothic860** [comment]
V 2.0 im getting connected to Asia....

**Comment by tutulino** [comment]
What pool and algo?

**Comment by tutulino** [comment]
Ok, I am see, MPH, fix in minutes

**Comment by tutulino** [comment]
Can you try again?, I´m triying again and now conect to europe as must.

Perhaps MPH api was not responding well for a while.

**Comment by Gothic860** [comment]
Now its working. Thank you!
