### ISSUE TITLE
I have added a new miner to version 3

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#20]
Tested working with version 3 and AMD
Gatelessgate.json
Implement if you want

{
"Path" : ".\\Bin\\GatelessGate\\GatelessGate.exe",

"Uri" : "https://github.com/zawawawa/gatelessgate/releases/download/v0.1.3-pre6b/gatelessgate-0.1.3-pre6b-win64.zip",

"Types" : ["AMD"],

"Arguments" : "-o #PROTOCOL#://#SERVER#:#PORT# -u #LOGIN# -p #PASSWORD# ",

"API" : "Xgminer",

"APIPort" : 4028,

"Wrap" : false,

"Dualmining":false,

"Algorithms": [
  
	        {"neoscrypt":"-k neoscrypt --gpu-threads 1 --worksize 256 --intensity 13"},
                {"ethash":"-k ethash-new --gpu-threads 2 --worksize 192 --xintensity 4608"},

                {"cryptonight":"-k cryptonight --gpu-threads 1 --worksize 4 --rawintensity 720"},

                {"equihash":"-k equihash --gpu-threads 2 --worksize 256"}
		 ]

}

**Comment by tutulino** [comment]
ok, next release will include it
