### ISSUE TITLE
When running with two groups for different cards...

### ISSUE THREAD

**Issue by dethknite** [tutulino/Megaminer#201]
It appears to me that the issue might be if/when it runs the same algo/miner for both groups at the same time...?

Here is the groups line from my config:
@@GPUGROUPS=[{"GroupName" : "1050ti","Type":"NVIDIA","GpuPlatform":"0","Gpus":"0"}, {"GroupName" : "1070","Type":"NVIDIA","GpuPlatform":"0","Gpus":"1"} ]

PowerShell Errors:
--------------------------------------

Add-Member : Cannot add a member with the name "GpuPlatform" because a member with that name already exists. To overwrite the member anyway, add the Force
parameter to your command.
At C:\Digital Coin Mining\Megaminer\Include.ps1:220 char:46
+ ...                $_ | Add-Member GpuPlatform (Get-Gpu-Platform $_.Type)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{GroupName=105...usNsgMode=-d 0}:PSObject) [Add-Member], InvalidOperationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

Add-Member : Cannot add a member with the name "GpuPlatform" because a member with that name already exists. To overwrite the member anyway, add the Force
parameter to your command.
At C:\Digital Coin Mining\Megaminer\Include.ps1:220 char:46
+ ...                $_ | Add-Member GpuPlatform (Get-Gpu-Platform $_.Type)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{GroupName=107...usNsgMode=-d 1}:PSObject) [Add-Member], InvalidOperationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

**Comment by tutulino** [comment]
You must delete ,"GpuPlatform":"X" from your config.txt file, new config.txt format dont need that variable, now is automatically calculated.
