### ISSUE TITLE
ITALYIIMP and keccak

### ISSUE THREAD

**Issue by podlbo** [tutulino/Megaminer#202]
Seems theat ITALYIIMP  has also problem with keccak algo... using this algo reporth realy high profits (if i remember correctly there was same problem on zpool in the past...)... Is there a way to correct this?

**Comment by tutulino** [comment]
Same way than zpool, edit Italyiimp.ps1 file and add  bold text


switch ($_){
                                                "X11"{$Divisor *= 1000}
                                                "qubit"{$Divisor *= 1000}
                                                "quark"{$Divisor *= 1000}
                                                "blakecoin"{$Divisor *= 1000}
                                                **"keccak"{$Divisor *= 1000}**
                                                }


It will be solved next release
