### ISSUE TITLE
Palginpav ccminer binary does not exist at URL provided

### ISSUE THREAD

**Issue by scavern** [tutulino/Megaminer#203]
This is incorrect... "Uri" : "https://github.com/palginpav/ccminer/releases/download/1.1.1/palginmod_1.1_x64.zip",

**Comment by tutulino** [comment]
Pagin has deleted file, I have upload it to github.

https://github.com/tutulino/Software/releases/download/0/NVIDIA-Palgin.rar

You can change Uri value on N-ccminerpagin.json for automatic download
