### ISSUE TITLE
mkxminer 30 mh rx 480 lyra2re2

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#205]
https://bitcointalk.org/index.php?topic=2360168.220

**Comment by tutulino** [comment]
I´m testing and get "mxkminer stopped to work" message.

**Comment by ALLMINER** [comment]
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100

FOR /F "tokens=4 delims= " %%i in ('route print ^| find " 0.0.0.0"') do set localIp=%%i

Set PCNAME=%localIp%
Set PCNAME=%PCNAME:192.168.1.=000%
Set PCNAME=%PCNAME:~-3%
Set PCID=%PCNAME:~1,1%

:RUNAGAIN
mkxminer.exe   -o stratum+tls://stak.suprnova.cc:7710 -u WinMKX.%PCNAME% -p x -I 23 --platform 0
GOTO RUNAGAIN


pause

**Comment by ALLMINER** [comment]
version 300 --asm  does not work on all. and need --platform 0 parammetr

**Comment by ALLMINER** [comment]
If you are getting errors about unsupported videocard or if you have an Intel CPU and AMD GPUs, try running example2platforms.cmd.

**Comment by tutulino** [comment]
Allways crack on my machine (rx580). I will add to additional miners folder if you want to add manually to miners folders.
