### ISSUE TITLE
Cant run manual

### ISSUE THREAD

**Issue by uprise88** [tutulino/Megaminer#206]
Hi i tried last commit, fresh configuration. I get this when trying to use manual.

<a href="https://ibb.co/h20hH6"><img src="https://thumb.ibb.co/h20hH6/Immagine.png" alt="Immagine" border="0"></a>

Assumin i want to manual mine with Mining pool hub i left this alone in the pool foolder but cant view coins
<a href="https://ibb.co/cSTSH6"><img src="https://thumb.ibb.co/cSTSH6/Immagine.png" alt="Immagine" border="0"></a>

**Comment by podlbo** [comment]
I notice same thing whent testing latest version avalible - i did revert back to stable realease.

**Comment by tutulino** [comment]
Fixed in master branch
