### ISSUE TITLE
DONATE DO NOT REPLACE PARAMETR

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#209]
------------------------------------------------   MegaMiner 5.1  -----------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
  (E)nd Interval   (P)rofits    (C)urrent    (H)istory    (W)allets                       | Next Interval:  72 secs...
 THIS INTERVAL YOU ARE DONATING, YOU CAN INCREASE OR DECREASE DONATION ON CONFIG.TXT, THANK YOU FOR YOUR SUPPORT !!!!
-----------------------------------------------------------------------------------------------------------------------

GroupName    Speed BTC/Day USD/Day Algorithm Coin  Miner          Pool Location PoolWorkers
---------    ----- ------- ------- --------- ----  -----          ---- -------- -----------
NVIDIA    2,0 mh/s 0,00046    6,92 LYRA2Z    zcoin CCminerNanashi MPH  US

--------------------------------------------------HISTORY------------------------------------------------------------
Running Mode: Automatic

   Status: Running

  Speed Active                      Launched Command
  ----- ------                      -------- -------
2,0 mhs 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-Nanashi\ccminer-2.2-mod-r2-CUDA9\ccminer.exe -o stratum+tcp://u
                                             s-east.lyra2z-hub.miningpoolhub.com:20581 -u mineralnov23.1060dom -p x -R
                                             10 -r 4 -b 23550 -d 0,1,2,3 -a lyra2z

**Comment by czjlj** [comment]
Yes,it is.

**Comment by tutulino** [comment]
Please, check last code from master, if you want to force donation interval edit donation.ctf file and put 1440 or greater (this are minutes without donating)
