### ISSUE TITLE
myr-gr is missing

### ISSUE THREAD

**Issue by danik-guitar** [tutulino/Megaminer#21]
![qip shot - screen 2017 08 15 16-48-05](https://user-images.githubusercontent.com/30734827/29318611-8c9e974e-81d9-11e7-8a7a-c10ea9031281.jpg)
![qip shot - screen 2017 08 15 16-47-15](https://user-images.githubusercontent.com/30734827/29318612-8ca4bd68-81d9-11e7-8760-8b52261b9215.jpg)

**Comment by danik-guitar** [comment]
and lyra2z is missing too

**Comment by tutulino** [comment]
I´m testing and see My-gr on alexis78, check miner file, (name is "Myriad-groestl")

Zpool haven´t lira2z, I see lyra2z on ccminer-tpruvot

**Comment by danik-guitar** [comment]
lira2z  on  miningpoolhub

**Comment by tutulino** [comment]
I get lyra2z on MPH with tpruvot, not need to add to ccminer2.2

**Comment by danik-guitar** [comment]
![image](https://user-images.githubusercontent.com/30734827/29324858-4553a464-81ee-11e7-8feb-1a2b14709183.png)

its ok !
