### ISSUE TITLE
P8 state

### ISSUE THREAD

**Issue by Paul-Trasca** [tutulino/Megaminer#210]
Hi guys. Just install another 2 cards in my rig. Inno3d 1080ti. 
In this conf, (gigabyte aorux extreme+2x inno 3d) i receive only in megaminer p8 state on inno 3d. Aorus stays in p2 state. Single card test returning p2 state on every card.
In nicehash (with p0 forced test all cards is working)
Any ideas?
Ps. Watercooled all cards with ekwb waterblocks (35 degree celsius on every card - p0 nicehash forced)
FOR DEV.
In nicehash there is an exe file nvidiap0state.exe. Can u include that file in megaminer?

**Comment by 1001rapid** [comment]
try to use
`nvidiaInspector.exe -forcePState:0,2 -forcePState:1,2`
Force P2 state for GPU0 and GPU1

**Comment by tutulino** [comment]
If you are using gpu groups in config.txt check all cards id are selected.

I try nicehash setp0 and dont work for me, nvidia-smi dont work, only way i can get P0 state is by nvdiaprofileinspector and I dont get any performance growth.
