### ISSUE TITLE
Hash Refinery not working (v.5.1)

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#211]
I try to use one pool "-PoolsName Hash_Refinery" and error message: no one pool selected
http://pool.hashrefinery.com/ - work
btc wallet in config are exist

**Comment by gregfromo** [comment]
I confirm this. With two pools in start.bat it works and h.ref is also choosen to mine to.

**Comment by 1001rapid** [comment]
I use "core.ps1 -MiningMode AUTOMATIC -PoolsName NICEHASH,Hash_Refinery,Mining_Pool_Hub" and in Profits screen only NiceHash listening. In which case I could use the NiceHashMiner. This is not quite what I wanted from the MM.
In v.5.0b2 HashRefinery works fine at the same time (in another rig)

**Comment by tutulino** [comment]
![image](https://user-images.githubusercontent.com/29943663/34357467-b8c45ab2-ea47-11e7-8006-5b1864bf22d0.png)

**Comment by geckah** [comment]
I have the same problem with hash refinery. Sometimes i will get "hash refinery api not responding" and it will drop out

**Comment by gregfromo** [comment]
I tried again today and I confirm that if the start.bat has only HR in it, it's most of the time responds "api not..".

**Comment by tutulino** [comment]
HR api is unstable, when you get that message, check if you reach this url

http://pool.hashrefinery.com/api/status

If not, is HR api problem

**Comment by geckah** [comment]
does the api request try a few times before giving up?

**Comment by tutulino** [comment]
Yes and No

For each interval

*Call Api with 10 sec timeout
*If no response...message is show
*If only one pool is selected wait 10 seconds and start again else go with other pools info until next interval

**Comment by 1001rapid** [comment]
-PoolsName Hash_Refinery,Mining_Pool_Hub
![20180103-poolsname hash_refinery mining_pool_hub](https://user-images.githubusercontent.com/34758417/34526134-88407ca6-f0b2-11e7-8b03-14262dd90a1a.JPG)

-PoolsName NICEHASH,Hash_Refinery,Mining_Pool_Hub
![20180103-poolsname nicehash hash_refinery mining_pool_hub](https://user-images.githubusercontent.com/34758417/34526171-aaee7032-f0b2-11e7-8ba8-ac4515cc9da9.JPG)

**Comment by xfactor8383** [comment]
Hey guys.. I was having the same issue with MPM and HR timing out on the API. Increase the timeout period to 30 or 60 seconds and it should resolve. The HR has also made improvments to the webpage API.

**Comment by 1001rapid** [comment]
@xfactor8383 in which file is it located? In pools file I find only
`$MiningPoolHub_Request = Invoke-WebRequest $http -UseBasicParsing -timeoutsec 10 `

**Comment by 1001rapid** [comment]
all works
