### ISSUE TITLE
excavator issues with Lyra2v2 0.0000

### ISSUE THREAD

**Issue by Ruber249** [tutulino/Megaminer#212]
When it comes to excavator for Lyra2v2 I am getting 0.0000 and it loops and will not complete the benchmark,  I have tried updating excavator with no luck also.   What Am i doing wrong?   This is with a 1070ti. Any help would be great

**Comment by Ruber249** [comment]
also I am using mining pool hub

**Comment by ALLMINER** [comment]
delete excavator.json

**Comment by tutulino** [comment]
Excavator is a "mistery", works flawless on some machines, others not, due to this I have moved to "Additional miners" folder.
