### ISSUE TITLE
Command prompt shows blinking cursor

### ISSUE THREAD

**Issue by scavern** [tutulino/Megaminer#215]
I am finding that every now and then all I see in the command prompt that MegamIner launches in is a blinking cursor at the top right. The mining software is still running.

None of the commands seem to do anything. What is interesting is that if I restart MegaMiner it starts fine, but is immediately mining a different algo, which makes me think that it couldn't query some API and just promptly gives up.

Are there any logs that I should be looking at to troubleshoot this?

**Comment by tutulino** [comment]
try last release
