### ISSUE TITLE
5.1 - Prospector (skunk), not working

### ISSUE THREAD

**Issue by gregfromo** [tutulino/Megaminer#216]
I wanted to have prospector in again, but it won't run, getting cuda error, but only AMD in the rig.

this is the log and generated toml file. maybe it helps debugging.

`10:51:21 - INFO   prospector 0.0.13-ALPHA starting
10:51:21 - ERROR  Could not load CUDA: Unknown error - Unknown error
10:51:21 - INFO   OpenCL Initialized
10:51:21 - ERROR  Could not parse configuration , please regenerate it using prospector.exe gen-config - Error { inner: ErrorInner { kind: Wanted { expected: "a right bracket", found: "a comment" }, line: Some(7), col: 8, message: "", key: [] } }

[general]
gpu-coin = "sigt" 
[pools.sigt]
url = "stratum+tcp://skunk.mine.zpool.ca:8433"
username = "3.....W" 
password = "c=BTC,amd-1"  
#FOR_EACH_GPU# 
[gpus.0-#GPUID#]
enabled = true
#END_FOR_EACH_GPU#
[cpu]
enabled = false
`

**Comment by tutulino** [comment]
how many @@gpugroups do you have in config.txt?

**Comment by gregfromo** [comment]
I have no groups configured in config.txt and only AMD in the rig, everything default.

**Comment by gregfromo** [comment]
now I copied back the old pattern file for rospector and it started, then I saw that the onboard igpu from the celeron was also mining, may thats why I have more then 1 group?
`17:31:10 - INFO   prospector 0.0.13-ALPHA starting
17:31:10 - ERROR  Could not load CUDA: Unknown error - Unknown error
17:31:11 - INFO   OpenCL Initialized
17:31:11 - INFO   Configuration successfuly loaded from AMD.toml
17:31:11 - INFO   Not launching CPU miner
17:31:11 - INFO   Miner starting on gpu 0-0 - Ellesmere
17:31:11 - INFO   Miner starting on gpu 0-1 - Ellesmere
17:31:11 - INFO   Miner starting on gpu 0-2 - Ellesmere
17:31:11 - INFO   Miner starting on gpu 0-3 - Ellesmere
17:31:11 - INFO   Miner starting on gpu 0-4 - Ellesmere
17:31:11 - INFO   Miner starting on gpu 0-5 - Ellesmere
17:31:11 - INFO   Miner starting on gpu 0-6 - Intel(R) Celeron(R) CPU G1820 @ 2.70GHz
17:31:11 - INFO   Device 1-0 disabled
17:31:11 - INFO   Device 1-1 disabled
17:31:11 - INFO   Starting api server on localhost:42000/api/v0/
17:31:11 - INFO   Signatum: Subscribed, waiting for jobs
17:31:11 - INFO   Signatum: Miner received subscription response
17:31:11 - INFO   Signatum: Authorized  by the pool
17:31:11 - INFO   Signatum: Miner changed difficulty
17:31:17 - INFO   Signatum: Shares    0 accepted / 0 total
`
