### ISSUE TITLE
How can I work with custom difficulty per algo?

### ISSUE THREAD

**Issue by delonbh** [tutulino/Megaminer#218]
Hi,
Is there a way to config difficulty even at single pool?

Normally is c=XXX,d=x

c=XXX its ok by "@@CURRENCY=BTC", but how can I try custom difficulty?

**Comment by tutulino** [comment]
For all pool or one coin of that pool?

**Comment by delonbh** [comment]
Hi.
Starting with one pool at time.

But The goal in The future  is multipool for fine difficulty tunning.

Em 28/12/2017 06:02, "tutulino" <notifications@github.com> escreveu:

**Comment by tutulino** [comment]
sorry, my question was wrong formulated

For all coins of one pool or for one coin of that pool only?

**Comment by delonbh** [comment]
All Algos on that pool.
The difficulty will be the  same to  all Coins on a especific algo.
Like NeoScrypt =X and X17 = Y, ie

Em 28/12/2017 07:25, "tutulino" <notifications@github.com> escreveu:

**Comment by tutulino** [comment]
You can edit password file at end of pool file and add what you want, but this is for all algos of that pool

Also

You can edit miner file and play with #AlgorithmParameters#, in running time is replaced by text you add for that algo in that miner file.

**Comment by delonbh** [comment]
Forgot  to  say.... The difficulty is seted at password like "-p
c=BTC,d=xxx".

Will it work adding -p settings at #AlgorithmParameters#?

By The way Ill try it.


Em 28/12/2017 08:28, "Warley" <delonbh@gmail.com> escreveu:

Ok.
Ill try it. After next payment.

Em 28/12/2017 08:19, "tutulino" <notifications@github.com> escreveu:

**Comment by tutulino** [comment]
you must set something like #PASSWORD##ADDITIONALPARAMETERS#, this way in running time your pass will be like you want

**Comment by delonbh** [comment]
Ill try it.
Thank You.

Em 28/12/2017 08:42, "tutulino" <notifications@github.com> escreveu:

**Comment by delonbh** [comment]
Worked !
You can closet this ticket.

Thank You a lot.

Em 28/12/2017 08:45, "Warley" <delonbh@gmail.com> escreveu:
