### ISSUE TITLE
adding sgminer PHI?

### ISSUE THREAD

**Issue by gregfromo** [tutulino/Megaminer#219]
https://github.com/216k155/sgminer-phi1612-Implemented/releases

as replacement for the nicehash 5.6.1

**Comment by tutulino** [comment]
Has any improvement over actual?

Files are password protected....??????

**Comment by mo35** [comment]
The password file was the only un-encrypted file in the zip... password: elbandiminer

**Comment by tutulino** [comment]
I tried that password but no work.....

Has any improvement over actual?

**Comment by gregfromo** [comment]
I just use this latest version, unfortunatly the dev didn't bother to make such good changelog like you always do. please continue your great work tutulino! This replaced for me the normal sgminer.
I uploaded the version without password here:

http://www114.zippyshare.com/v/ZhO5aouc/file.html

**Comment by tutulino** [comment]
I don´t get any improvement, actual is tested and work
