### ISSUE TITLE
Benchmarking not working

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#22]
I have now tested all variations of this and after 2 hours have never once moved past the initial benchmark.
I cannot proceed until benchmarking has completed.
Not sure what to do now.....

**Comment by tutulino** [comment]
I think I know what happening, I´m trying to solve (without amd card to test....arggg)

**Comment by Imaminer** [comment]
Do you want to teamview into my rig?

**Comment by Imaminer** [comment]
You can if you want. TV is already on it.

**Comment by tutulino** [comment]
I´m atonished, I just discover a trick to run sgminer...XD

Problem is solved, next release in minutes will solve it, while you can change arguments of miner file by

"--api-listen -o #PROTOCOL#://#SERVER#:#PORT# -u #LOGIN# -p #PASSWORD# --gpu-platform #GPUPLATFORM#"

**Comment by Imaminer** [comment]
Cool I will test again when I see new code. Thanks

**Comment by Imaminer** [comment]
Ok I switched but sgminer hung on neo. Just removed it. Gateless will do neo just fine. testing again

**Comment by Imaminer** [comment]
Confirmed benchmarking is working on AMD. Closing this one. Thanks!
