### ISSUE TITLE
wattomine coin json

### ISSUE THREAD

**Issue by bagaut** [tutulino/Megaminer#220]
hello, how add json like this (http://whattomine.com/coins/204.json) to WHATTOMINE_VIRTUAL.ps1? thank you

**Comment by tutulino** [comment]
What do you want to do?

**Comment by bagaut** [comment]
EXAMPLE: http://whattomine.com/coins.json have not smartcash coin (and some another coins) , but whattomine have json for smartcash (http://whattomine.com/coins/197.json). I want add in WHATTOMINE_VIRTUAL.ps1 smartcash json .  :( thx

**Comment by tutulino** [comment]
Easy if you know Powershell, not easy if not....

**Comment by bagaut** [comment]
i dnt knw :( ok, thank you anyway

**Comment by tutulino** [comment]
How do you get that id?, if I know what id is missing on main file I cand
add, but I cant make 300 api call to search all non existant ids....

2017-12-28 16:44 GMT+01:00 bagaut <notifications@github.com>:

**Comment by bagaut** [comment]
http://whattomine.com/coins/197-smart-keccak here , right top corner *json*.

**Comment by MikeBuzz** [comment]
Check out this

https://github.com/yuzi-co/Megaminer/commit/d1aa56e861ceb57e086bc65330566912301afff8

**Comment by bagaut** [comment]
thank you mike.

**Comment by tutulino** [comment]
Finally i can make this work. All coins are now in WTM pool
