### ISSUE TITLE
Adding pools 

### ISSUE THREAD

**Issue by Twente-Mining** [tutulino/Megaminer#221]
Hello Tutulino,

Thanks for the great software package you are providing! Great work!
I just forked it because I want to add more pools to the miner, 
For this i made a copy of suprnova.ps and hoped it would be as easy as adding right coin, algo and server details but sadly it won't start a miner.

Could you explain in short what I might be doing wrong?

Regards

**Comment by podlbo** [comment]
I can sugesst to add to MM http://blockmunch.club/ or maby https://dwarfpool.com/

**Comment by tutulino** [comment]
Imposible to know, a new pool is not difficult but not trivial....

tell me what pool are you adding
