### ISSUE TITLE
5.2 - logging

### ISSUE THREAD

**Issue by gregfromo** [tutulino/Megaminer#222]
I started to test the latest master, the new looging is a good improvment!
Should I see somehwere the donation phase? I set to 60min, what should I look for to see if it's working?

**Comment by gregfromo** [comment]
update:
I found the donation in the logs (using nicehash server), but it's mining only 5 min, not the 60 I configured.
any idea why?

**Comment by tutulino** [comment]
I found "bug", solved next release.

Thanks
