### ISSUE TITLE
Unable to run 9XX series with the miner

### ISSUE THREAD

**Issue by Mooglee** [tutulino/Megaminer#224]
All 10 series GPU for nvidia run fine, but there appears to be an issue with ccminers MegaMiner uses, they are lacking the sm3 flag, so its unable to use any 9XX series GPUs.

**Comment by gregfromo** [comment]
what 9xx do you have exactly? missing sm30 is not the problem. 
usually if exe is build with "compute_52,sm52" it works.
more details here:
http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
