### ISSUE TITLE
Configuration options for autoexchange pools when a coin is not supported

### ISSUE THREAD

**Issue by jalapeno777** [tutulino/Megaminer#226]
I would love an option to specify a different autoexchange coin on a per pool basis in the configs as some pools mine/support different coins.  One example is if I want to autoexchange to feathercoin...yiimp supports it, zpool does not.  So I would love to have an alternative configured for zpool without having to simpy leave zpool out of the mix.

**Comment by firrae** [comment]
Something else to add to this is Zpool is rejecting my connections when the miner tries to connect with an exchange currency it does not support. This left me with an hour of head scratching today as I played with the config file.

**Comment by tutulino** [comment]
Available in master branch code
