### ISSUE TITLE
Coin info in wallet for MPH and History info for mining on MPH

### ISSUE THREAD

**Issue by podlbo** [tutulino/Megaminer#227]
I notice with latest MM master that is NO coin info in wallet section for MPH... I start MM on all 4 automatic pools (MPH, ahash, hashrefinery and zpool) and on other 3 pools info for BTC status is correct, for MPH i get only numbers information without text which coin it is...

Also if i start MM with same described startin conifiguration (auto mode on 4 anonymous pools) in history section there is no information for mining on MPH (specialy i notice this if MM uses "SKEIN" algo... p....lyra2v2 is reported correctly). In LOG folder there is correct info about mining on MPH it is just not presend in MM.

**Comment by podlbo** [comment]
![slika](https://user-images.githubusercontent.com/33230718/34981633-5a64a42e-faa8-11e7-8339-4e91703755a4.png)

**Comment by tutulino** [comment]
try last release

**Comment by podlbo** [comment]
I did... picture is from latest release (downloade 1hr ago...).

**Comment by dr3mro** [comment]
Same issue here 
And coin names not visible in dual miner list 
No coin name https://imgur.com/gallery/ufZN3
