### ISSUE TITLE
Skein - profit calculation wrong?

### ISSUE THREAD

**Issue by gregfromo** [tutulino/Megaminer#228]
There seems to be something wrong wit profit calculation.
I have 2 gh/s but this equals only 0,18 € per day. Where are too many zeros somewhere ;)

**Comment by tutulino** [comment]
I see there is /10 profit error but no more.

Skein seems very low profit now, but a lot of miners on it...strange

**Comment by yuzi-co** [comment]
because of this:
                        "skein"{$Divisor *= 100}

no pools use 100 divisor

**Comment by tutulino** [comment]
Yes, this was I see , I have changed to 
"skein"{$Divisor *= 1000}
