### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#232]
"Arguments":  "--api-listen -o stratum+tcp://us-east.hub.miningpoolhub.com:20527 -u mineralnov23.1470 -p x --device 0 --api-port 32756 --gpu-platform 0 -k skeincoin --gpu-threads 2 --worksize 256 --intensity d "
}
01/12/2018 10:06:07...... ###### ERROR ##### Невозможно разрешить удаленное имя: 'digibyte.miningpoolhub.com' в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\pools\Mining_Pool_Hub.ps1: строка 94
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1: строка 979
в Get_Pools, C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1: строка 972
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\core.ps1: строка 935
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\core.ps1: строка 926
в <ScriptBlock>, <Нет файла>: строка 1
01/12/2018 10:06:07...... ###### ERROR ##### Попытка деления на нуль. в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1: строка 199
в <ScriptBlock>, <Нет файла>: строка 1
в get_gpu_information, C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1: строка 174
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\core.ps1: строка 787
в <ScriptBlock>, <Нет файла>: строка 1
01/12/2018 10:06:07...... ###### ERROR ##### Попытка деления на нуль. в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1: строка 199
в <ScriptBlock>, <Нет файла>: строка 1
в get_gpu_information, C:\Users\аагнрошло\Desktop\Megaminer-master\Include.ps1: строка 174
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-master\core.ps1: строка 787
в <ScriptBlock>, <Нет файла>: строка 1

**Comment by tutulino** [comment]
I cant  read russian
