### ISSUE TITLE
Add disable/enable miner programs and algorithms in config

### ISSUE THREAD

**Issue by vapor99** [tutulino/Megaminer#233]
As a nice enhancement I wouldn't mind seeing config options for selecting which algorithms to mine and the ability to disable unstable programs for the benchmark.

**Comment by AZ-Ronin** [comment]
I absolutely agree. Especially when certain algo's will cause system instability.

**Comment by tutulino** [comment]
Available (algorithms only) in master branch code

**Comment by vapor99** [comment]
Wonderful! Thank you!

**Comment by AZ-Ronin** [comment]
Awesome! Thank you!
