### ISSUE TITLE
Nvidia SMI 'Not Supported' 

### ISSUE THREAD

**Issue by SamJongenelen** [tutulino/Megaminer#235]
When using NVidia setup GTX770 the _nvidia-SMI.exe_ call made from the  _GPUlist.ps1_ errors.
The tool returns _Not Supported_ for a lot of properties. Some properties are queried though.

MegaMinder tries to parse this string to int and fails. 

command: 
`./nvidia-smi.exe --query-gpu=gpu_name,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,pstate,clocks.current.graphics,clocks.current.memory,power.max_limit,power.default_limit --format=csv,noheader`

nvidia-SMI.exe output:
`GeForce GTX 770, [Not Supported], [Not Supported], 52, [Not Supported], [Not Supported], 52 %, P0, [Not Supported], [Not Supported], [Not Supported], [Not Supported]`

**Comment by SamJongenelen** [comment]
[workaround](https://devtalk.nvidia.com/default/topic/563056/how-to-get-nvidia-smi-working-/)

**Comment by SamJongenelen** [comment]
Why did you close this? It needs better exception handling, which is my request. Any comment?

**Comment by 1001rapid** [comment]
because "Tested on nvidia pascal 10X0 and AMD RX580"

**Comment by 1001rapid** [comment]
and this - https://github.com/tutulino/Megaminer/issues/241
