### ISSUE TITLE
No equihash on Miningpoolhub

### ISSUE THREAD

**Issue by xtremetr** [tutulino/Megaminer#236]
First of all thanks for amazing tool. 

It dont benchmark and check profitability for Equihash algo on MPH . I couldnt find a way to add algo to MPH .

Regards

**Comment by xtremetr** [comment]
I've 6 Nvidia 1070's on my rig. Running W10 x64 . 

Re checked \bin and \miner directorys. DTSM and EWBF jsons and miner BIN's are ok . Also there is equihash algo in json files. It's still not benchmark and list on MPH .  Can somebody help me to add this algo to MPH.

  "Path": ".\\Bin\\zm_0.5.7_win\\zm.exe",
  "ExtractionPath": ".\\Bin\\",
  "Uri": "https://github.com/tutulino/Software/releases/download/0/zm_0.5.7_win.zip",
  "Types": ["NVIDIA"],
  "Arguments":  "--server #SERVER# --port #PORT# --user #LOGIN# --pass #PASSWORD# --dev #DEVICESETHMODE# --telemetry=127.0.0.1:#APIPORT# #ALGORITHMPARAMETERS# ",
  "API":  "DTSM",
  "Wrap":  false,
  "Dualmining":false,
  "Fee":"0.02",
  "PrelaunchCommand":"",
  "Algorithms": [
                     {"Equihash":""}
                   ]

}

**Comment by tutulino** [comment]
try last release

**Comment by xtremetr** [comment]
Still no equihash in 5.2 . If i manually select any equihash coin in MPH gives error “No miners”. Everything works brilliant except equihash.

**Comment by tutulino** [comment]
Is working well for me, check that bin folder contains downloaded miner, sometimes antivirus delete.

**Comment by xtremetr** [comment]
i found very weird solution. Changed algo name “equihash” to “EQUIHASH” (all caps on)  and now it works as it should be. I think its a character set problem .
