### ISSUE TITLE
wrapper

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#237]
wrapper api work ?

**Comment by tutulino** [comment]
yes

2018-01-14 18:18 GMT+01:00 ALLMINER <notifications@github.com>:

**Comment by ALLMINER** [comment]
maybe you run ... I do not have api wrapper and xgminer

**Comment by tutulino** [comment]
Sgminer forks must work via api, not wrapper.

If that fork has no api, wrapper is not valid for any miner, it search some patterns in miner output, you can see inside wrapper.ps1 file
