### ISSUE TITLE
unimining is Anonymous?

### ISSUE THREAD

**Issue by podlbo** [tutulino/Megaminer#238]
Ok -- i know MM suports Unimining - but informations on web and on MM are not the same. 
"UNIMINING -- No registration, No autoexchange, need wallet for each coin on config.txt"

And on https://www.unimining.net/
"No registration is required, we do payouts in the currency you mine. Use your wallet address as the username."

So if i get this right unimining is now Anonymous pool which make  autoexchange to selected coin... So it needs some adjustments - or did i mixed up with diferend unimining pool?

**Comment by tutulino** [comment]
No, "we do payouts in the currency you mine" means autoexchange is off, if you mine one coin you only can be paid on that coin

**Comment by podlbo** [comment]
Ok - true i did check it again ;) My bad - im raly sorry.
