### ISSUE TITLE
some errors with Nanopool 5.2

### ISSUE THREAD

**Issue by mo35** [tutulino/Megaminer#240]
its working eth/dcr dual with claymore ,but getting spammed with following

01/16/2018 15:17:36...... ###### ERROR ##### Cannot index into a null array. at <ScriptBlock>, C:\Megaminer-5.2\pools\NANOPOOL.ps1: line 50
at <ScriptBlock>, C:\Megaminer-5.2\Include.ps1: line 1014
at Get_Pools, C:\Megaminer-5.2\Include.ps1: line 1007
at <ScriptBlock>, C:\Megaminer-5.2\core.ps1: line 977
at <ScriptBlock>, C:\Megaminer-5.2\core.ps1: line 968
at <ScriptBlock>, <No file>: line 1

**Comment by tutulino** [comment]
Fixed next release / master code upload.

Thanks
