### ISSUE TITLE
Power cost currency

### ISSUE THREAD

**Issue by pivlusleptis** [tutulino/Megaminer#243]
Not really a code issue there, but I believe the power cost per kWh should be based on fiat and not on bitcoin because of btc's price volatility.

**Comment by tutulino** [comment]
True, next release will be fiat.

**Comment by Steality** [comment]
Versify fiat currency is good too other than dollar,euro

**Comment by SerpentDrago** [comment]
I was just about to Post this , Yes with the fact we pay for power mostly in Fiat . it should be based in Fiat . 

For now , How can i disable power cost from getting factored in ? i'd rather it go though a couple more releases before enabling it

**Comment by uprise88** [comment]
Just set it to 0 utili Fiat gestire comes out

**Comment by tutulino** [comment]
Added to 6.0 release
