### ISSUE TITLE
Afterburner Profiles

### ISSUE THREAD

**Issue by GillyTheGhillie2** [tutulino/Megaminer#244]
Hi, it would be nice to be able to set one afterburner profile for mining and when the script is killed it automatically switches back to the original profile, for those who use their rig for mining and as a general computer, currently I have to do this semi manually using ""C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" -profile2" on launch and then killing the program using a separate batch file that resets the profile to profile1

**Comment by 1001rapid** [comment]
use .bat (or .cmd) file for check program is working
`@echo off
:check
TaskList /fi "WINDOWTITLE eq Mega*" 2>nul | Find /I "cmd.exe">nul || (
Start  MSIAfterburnerProfile1.lnk & exit
)
ping -n 10 127.0.0.1 > nul
goto chek
`
You must run Megaminer from batch file use command
start "Megaminer (Title Window)" Megaminer.bat
