### ISSUE TITLE
Would like to add pool

### ISSUE THREAD

**Issue by jjude80** [tutulino/Megaminer#245]
I would like to add my pool https://cryptotastic.net to the script.  I have already created a working ps1 file, and would like to commit it to the git. 
thank you,
jjude80@gmail.com
[CryptoTastic.zip](https://github.com/tutulino/Megaminer/files/1657795/CryptoTastic.zip)

**Comment by tutulino** [comment]
Sorry, too small pool. Each pool requires manteinance effort and I think few people will use this with MM.
