### ISSUE TITLE
Cannot download ccminer-alexis78-ms2013-cuda7.5

### ISSUE THREAD

**Issue by podlbo** [tutulino/Megaminer#249]
Seems theat link is not any more correct for Alexsis78

Cannot download .\Bin\NVIDIA-Alexis78\ccminer-alexis78-ms2013-cuda7.5\ccminer.exe distributed at https://github.com/nemosminer/ccminer-Alexis78/releases/download/ccminer-alexis78/ccminer-alexis78-ms2013-cuda7.5.7z.

**Comment by tutulino** [comment]
Yes, change uri in miner file to:
https://github.com/tutulino/Software/releases/download/0/ccminer-alexis78-ms2013-cuda7.5.zip

**Comment by podlbo** [comment]
Great :) Link works ;)
But im having trubles with this miner.... 
[2018-01-26 16:07:20] GPU#0:result for 00000000 does not validate on CPU!
[2018-01-26 16:07:20] GPU#0:an illegal memory access was encountered

Im using latest nvidia drivers and win 10.... 2x 1080ti (on 85%)

**Comment by tutulino** [comment]
Ccminer Alexis is a little unstable at default intensities, try lower intensities for problematic algos editing miner file and playing with -i parameter at end of algo name

**Comment by podlbo** [comment]
works great ;) Thanks, i did lower from 20 -> 15 + i did increese virtual memory (i dont know if this hellps)
