### ISSUE TITLE
ccminer-alexis78-ms2013-cuda7.5.7z. error

### ISSUE THREAD

**Issue by rinkal26783** [tutulino/Megaminer#251]
01/27/2018 11:47:39...... New interval starting.............
01/27/2018 11:47:40...... "AverageCpu = 17 % | MemoryUsage = 56.05 % | VirtualMemoryUsage = 21.35 % |  PercentCFree = 63.99 % | Processes = 130 | Connections = 73"
01/27/2018 11:47:41...... Loading Pools Information.............
01/27/2018 11:47:41...... Pool Zpool was responsive....
01/27/2018 11:47:43...... Miners detected: 50.........
01/27/2018 11:47:43...... Downloading....https://github.com/nemosminer/ccminer-Alexis78/releases/download/ccminer-alexis78/ccminer-alexis78-ms2013-cuda7.5.7z
01/27/2018 11:47:44...... Cannot download .\Bin\NVIDIA-Alexis78\ccminer-alexis78-ms2013-cuda7.5\ccminer.exe distributed at https://github.com/nemosminer/ccminer-Alexis78/releases/download/ccminer-alexis78/ccminer-alexis78-ms2013-cuda7.5.7z. 
01/27/2018 11:47:44...... Cannot find .\Bin\NVIDIA-Alexis78\ccminer-alexis78-ms2013-cuda7.5\ccminer.exe distributed at https://github.com/nemosminer/ccminer-Alexis78/releases/download/ccminer-alexis78/ccminer-alexis78-ms2013-cuda7.5.7z. 
01/27/2018 11:47:44...... ###### ERROR ##### The request was aborted: The connection was closed unexpectedly. at Expand_WebRequest, C:\Users\JP\Desktop\Megaminer zpool\Megaminer-5.2\Include.ps1: line 959
at Start_Downloader, C:\Users\JP\Desktop\Megaminer zpool\Megaminer-5.2\Include.ps1: line 1341
at <ScriptBlock>, C:\Users\JP\Desktop\Megaminer zpool\Megaminer-5.2\core.ps1: line 491
at <ScriptBlock>, C:\Users\JP\Desktop\Megaminer zpool\Megaminer-5.2\core.ps1: line 490
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\JP\Desktop\Megaminer zpool\Megaminer-5.2\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1

**Comment by podlbo** [comment]
https://github.com/tutulino/Software/releases/download/0/ccminer-alexis78-ms2013-cuda7.5.zip

**Comment by kimswe** [comment]
also change the bin path, 
"Path" : ".\\Bin\\NVIDIA-Alexis78\\ccminer.exe",
