### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by moysatos** [tutulino/Megaminer#252]
Hello having problems had a spare rig with 2 cards rx480 and rx580 stopped benchmarking because nothing worked claymorezec no mining and watchdog restarts changed from 1 to 0 but same problem.
Gatlessgate same problem not starting all sgminer forks belive it is GPU platform issues on my PC it's 0.
Claymorezec gatlelesgate and sgminer i have been using without problems mining manually.

Thnaks

**Comment by tutulino** [comment]
are you using @@GPUPLATFORM variable?

**Comment by moysatos** [comment]
Ok did not use GPU platform variable thanks and sorry but for zec and ethash claymore had problem with miner did not recognize 8192 mb memory and always restarts changed setx force GPU 64bit to 1 and running smoothly.


Thanks and great work
