### ISSUE TITLE
add new miner for HSR and Neoscrypt

### ISSUE THREAD

**Issue by rinkal26783** [tutulino/Megaminer#253]
hsrminer has better performance with neoscrypt and HSR. It gives 15% more speed compare to ccminer.
Are you going to add it in your next release?
Is it possible to add this miner with current version of megaminer?

**Comment by tutulino** [comment]
It will be included in next release, need main files changes

**Comment by rinkal26783** [comment]
thanks. I look forward to it.

**Comment by imrecsoka** [comment]
I cant get this miner to work, mine starts and then goes to the prompt, no idea why.
I also noticed that NSGMiner is not going past 14 intensity , really do not understand this.
So overall CCminer and variants are fine for me.
However , i would love for this miner to work properly in Megaminer tweaks/settings.
I am sure these European guys know their solutions :)
Please take note of that.
My machine, windows 10 pro x64 and 2 GTX1060 3GB graphics cards 8 GB ram.
