### ISSUE TITLE
add http://zergpool.com/

### ISSUE THREAD

**Issue by zuhair01** [tutulino/Megaminer#255]
I would like to add my pool http://zergpool.com/  this pool 0 fee
thank you,

**Comment by Steality** [comment]
Since zergpool is yiimp based setup, simply copypaste ahashpool.ps1, edit and find everything under name "ahashpool" and convert it to "zergpool"  then "ahash" and convert it to "zerg"

**Comment by zuhair01** [comment]
i don't know how to edit the code

**Comment by tutulino** [comment]
I like your pool, is the only want I know  new coins+autoexchange+coin selection, right?

If I understand your main page instructions you can pass a wallet of any coin with c= and select one coin to mine with mc=.

If is correct I will add to next release with its own stats and inside whattomine virtual pool.

**Comment by zuhair01** [comment]
Actually this website is not ours this is my friend recommended this very low mining prayers i think why not you are a add

**Comment by zuhair01** [comment]
next release Every restart I will go manually select the automatic pool why not you Automatic all 
add Start ALL AUTOS

**Comment by tutulino** [comment]
I Don´t understand your last message

**Comment by zuhair01** [comment]
i am talking about auto start

**Comment by reset77** [comment]
ZergPool looks good... very different good coins there... this will be better replacement to Altminer

**Comment by reset77** [comment]
Hey man talking about new pools... http://blockmunch.club/ 
has some good coins too, they have GRLC this coin is most profitable right now by far...
are you considering other pools for next release?
too bad Altminer restricted their API

Thanks!!
