### ISSUE TITLE
Windows sizes and printing of text

### ISSUE THREAD

**Issue by imrecsoka** [tutulino/Megaminer#256]
I do not know why, but version 4.8 always wants to benchmark a coin , before it start to mine.
5.2 seems better but i have a text problem where active miners status is duplicating in text.
I dont understand this.
Its it possible to automatically size the windows in code in the new version?
Its really irritating.
The height and the width of the window.

4.8:
![image](https://user-images.githubusercontent.com/25494601/35480772-4e85e7d8-041e-11e8-8292-3e199c380aee.png)

5.2:

For some reason not showing currency unit.
text seems to be random, it looks fine in this screen shot:

![image](https://user-images.githubusercontent.com/25494601/35480779-96345632-041e-11e8-980a-6f98f5db9293.png)

But again , can you enforce window sizes maybe?

**Comment by tutulino** [comment]
Windows is automatically resized, but sometimes terminal or teamviewer has low resolutions. Use key "X" to force screen resize/repaint.
