### ISSUE TITLE
Expose ccminer api via `--api-remote --api-allow=0/0`

### ISSUE THREAD

**Issue by caesarmine** [tutulino/Megaminer#257]
I'd like to run Megaminer on my mining computers, then have an Awesome Miner dashboard monitoring all of them.

If ccminer exposes its API as port 4068, I could run Megaminer on my rig, then have AwesomeMiner monitor everything on my master rig. Awesome Miner could even do nice things like restart the miner on crash in this case.

**Comment by caesarmine** [comment]
Actually, it looks like this is already done via the APIPORT variable. Nevermind. 

Thanks for the great tool. :+1:

**Comment by caesarmine** [comment]
Reopening -- I realized what is needed is just the `--api-allow` flag on all miners.

**Comment by tutulino** [comment]
are you sure this is necessary?, API is enabled by default.
