### ISSUE TITLE
Strange errors (MpPreference, NetTCPConnection)

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#260]
benchmark on 980 Ti (if this is important)
```
01/30/2018 05:55:33...... ###### ERROR ##### The term 'Get-MpPreference' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. at <ScriptBlock>, D:\Mining\Megaminer\core.ps1: line 64
at <ScriptBlock>, <No file>: line 1
01/30/2018 05:55:33...... ###### ERROR ##### The specified module 'PSReadline' was not loaded because no valid module file was found in any module directory. 
01/30/2018 05:55:33...... Starting Parameters:  //Algorithm:  //PoolsName: Mining_Pool_Hub,Hash_Refinery,YIIMP,NANOPOOL,NICEHASH //CoinsName:  //MiningMode: AUTOMATIC //Groupnames:  //PercentToSwitch: 
01/30/2018 05:55:33...... New interval starting.............
01/30/2018 05:55:37...... "AverageCpu = 19 % | MemoryUsage = 47.16 % | VirtualMemoryUsage = 3.53 % |  PercentCFree = 32.15 % | Processes = 48 | Connections = "
01/30/2018 05:55:41...... ###### ERROR ##### The term 'Get-NetTCPConnection' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. at Get_ComputerStats, D:\Mining\Megaminer\Include.ps1: line 51
at <ScriptBlock>, D:\Mining\Megaminer\core.ps1: line 185
at <ScriptBlock>, <No file>: line 1
01/30/2018 05:55:41...... Loading Pools Information.............
01/30/2018 05:55:46...... Pool Hash_Refinery was responsive....
01/30/2018 05:55:46...... Pool Mining_Pool_Hub was responsive....
01/30/2018 05:55:46...... Pool NICEHASH was responsive....
01/30/2018 05:55:46...... Pool NANOPOOL was responsive....
01/30/2018 05:55:54...... Miners detected: 127.........

```

**Comment by 1001rapid** [comment]
In 1050 Ti the picture is even more strange
No support Power. But recognized "Power Limit 70%"
![20180131_mm_1050](https://user-images.githubusercontent.com/34758417/35600050-f3464e14-063c-11e8-8b9e-1fea2dc92034.PNG)

**Comment by 1001rapid** [comment]
Yes! With old driver looks better
![20180131_mm_1050_old_drv](https://user-images.githubusercontent.com/34758417/35605072-2fb59e58-0657-11e8-95a4-05c02bea2ef9.PNG)

**Comment by 1001rapid** [comment]
In 6.0 the same errors and not support "Power Limit" for 980Ti
![20180203_mm60](https://user-images.githubusercontent.com/34758417/35774067-186521c0-0976-11e8-9257-9a6f1a5d8265.PNG)

**Comment by tutulino** [comment]
Please, test last master branch code (not last release)

**Comment by 1001rapid** [comment]
all broken .(
![20180204_new_include1](https://user-images.githubusercontent.com/34758417/35781716-b2de9d02-09fe-11e8-94d4-d0638872f8ba.PNG)
![20180204_new_include2](https://user-images.githubusercontent.com/34758417/35781719-b759cbe0-09fe-11e8-922a-bbfc5697ab47.PNG)
[20180204_new_include1_log.txt](https://github.com/tutulino/Megaminer/files/1693257/20180204_new_include1_log.txt)

**Comment by 1001rapid** [comment]
v.6.0b2
Everything works, but errors still exist
[2018-02-05_18-59-43.txt](https://github.com/tutulino/Megaminer/files/1695809/2018-02-05_18-59-43.txt)
