### ISSUE TITLE
Cant use Altminer pool

### ISSUE THREAD

**Issue by delonbh** [tutulino/Megaminer#261]
New interval starting.............
Loading Pools Information.............
ALTMINER API NOT RESPONDING...ABORTING
NO POOLS!....retry in 10 sec --- REMEMBER, IF YOUR ARE MINING ON ANONYMOUS WITHOUT AUTOEXCHANGE POOLS LIKE YIIMP, NANOPOOL, ETC. YOU MUST SET WALLET FOR AT LEAST ONE POOL COIN IN CONFIG.TXT

Setted up:

AT Batch:
powershell -version 5.0 -noexit -executionpolicy bypass -command "&.\core.ps1 -MiningMode Automatic -PoolsName ALTMINER - Algorithm Neoscrypt -Coinsname TrezarCoin,Vivo,CrowdCoin,GoByte,Innova,Sparks,Cerberus,QBIC,Desire

AT Config.txt

@@CURRENCY=QBIC  and already tried @@CURRENCY=BTC....  

@@WALLET_TZC=my wallet
@@WALLET_VIVO=my wallet
@@WALLET_CRC=my wallet
@@WALLET_GBX=my wallet
@@WALLET_INN=my wallet
@@WALLET_SPK=my wallet
@@WALLET_CBS=my wallet
@@WALLET_QBIC=my wallet
@@WALLET_DSR=my wallet
@@WALLET_ONEX=my wallet

**Comment by reset77** [comment]
ALTMINER has good coins, but they have serious problems with their API, Tutulino just said Altminer will be discontinued on the next release... so forget about cerberus and the other good coins... its a problem from the pool not MegaMiner

**Comment by delonbh** [comment]
Thank you so much for clarifying me.





*Warley Roverse*

**Comment by delonbh** [comment]
Thank you...
Closing it.

**Comment by reset77** [comment]
sorry to bring the bad news i was hoping for this pool to work, very good coins there, maybe Tutulino find other good pools in the future

**Comment by delonbh** [comment]
No problem.

We will managed to mine in another option.

thank you again.



*Warley Roverse*
