### ISSUE TITLE
sgminerPhi password won't work

### ISSUE THREAD

**Issue by Deeferdawg** [tutulino/Megaminer#262]
I have tried every solution presented in the other issue thread relating to this and the password still won't work. Megaminer is in an endless loop and won't benchmark. How can I either get it to work, remove it or usea different miner so it goes through the benchmarking process and finally work. Thanks.

**Comment by tutulino** [comment]
There is an error on download url, change uri field in miner file to https://github.com/tutulino/Software/releases/download/0/SgminerPhi.rar

**Comment by Deeferdawg** [comment]
I think it worked but getting this error now
[06:31:44] Started sgminer 5.5.0-nicehash-1

"C:\Users\GARAGE\AppData\Local\Temp\OCL6844T2.cl", line 821: warning: goto
          statement may cause irreducible control flow
        if(flag) goto end;
                 ^

"C:\Users\GARAGE\AppData\Local\Temp\OCL6844T2.cl", line 833: warning: goto
          statement may cause irreducible control flow
        goto compress;
        ^

12 errors detected in the compilation of "C:\Users\GARAGE\AppData\Local\Temp\OCL6844T2.cl".
Frontend phase failed compilation.

[06:31:47] Failed to init GPU thread 0, disabling device 0
[06:31:47] Restarting the GPU from the menu will not fix this.
[06:31:47] Re-check your configuration and try restarting.
Press enter to continue:
