### ISSUE TITLE
Log file not support interactive NET monitoring

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#263]
If I open the file for viewing from network, it is blocked and the MegaMiner displays an error message

> Add-Content: The cannot access the file FILEPATH because it is being used in another process

In previous versions I could use log file as a remote monitoring rigs.

Only because of this I returned to the previous version. Just wasted two days on the passage of benchmarks.

**Comment by tutulino** [comment]
are you opening file in read only mode from .net?

**Comment by 1001rapid** [comment]
I use FAR Manager for this.  In previous versions I open file for Read (F3) frome remote maschine and his viewing and refresh automaticly, when I scroll to end of file (press "End" button). It's very convenient, fast and takes up less resources.

**Comment by 1001rapid** [comment]
In new version the log file is no longer a copy of the program window... So sad (
Can you make a separate log file for this?

**Comment by tutulino** [comment]
Please, test again, now I´m locking file at MM start.

**Comment by 1001rapid** [comment]
Well, yes, you can view, no errors are output. But in the current form, the log file is no longer important.
In any case, thanks)
