### ISSUE TITLE
Benchmark/miner fail time period v6 beta

### ISSUE THREAD

**Issue by xtremetr** [tutulino/Megaminer#269]
Hi, 

How can i change time period of watchdog to tag miner as fail? 

My rig starts with 3 gpu and other 3 gpu starts in a 2-3 minutes. New watchdog mechanism think its failing but its not. I think if i can change time period of "fail" tag , i can solve my issue.

**Comment by tutulino** [comment]
Search this line in core.ps1, last number (100) is time in seconds from interval´s start when watchdog starts to run, number before (70) is average  usage percent to mark a group as "dead"

 if ($ActiveMiners[$_.IdF].Process -eq $null -or $ActiveMiners[$_.IdF].Process.HasExited -or ($GpuActivityAverage -le 70 -and $TimeSinceStartInterval -gt 100) ) {

**Comment by xtremetr** [comment]
Yes, it worked! 👍 
Thanks for tip.
