### ISSUE TITLE
Zpool !

### ISSUE THREAD

**Issue by danik-guitar** [tutulino/Megaminer#27]
if the pool has fallen off it is not restored

**Comment by tutulino** [comment]
This must happens only on cold start, true?

**Comment by danik-guitar** [comment]
working 5 -15 minuts and  off

**Comment by tutulino** [comment]
Zpool api is very unstable, each interval MM tries 3 times api, is posible one interval not zpool available but next interval must be available.

**Comment by danik-guitar** [comment]
then api Zpool dont run again.
I restart manually and its ok.

**Comment by coderasm** [comment]
Same here. During benchmarking miners ran against it twice, then benchmarking stopped against zpool.
