### ISSUE TITLE
AMD neverending benchmarking , weird behaviour

### ISSUE THREAD

**Issue by mo35** [tutulino/Megaminer#271]
Clean setup , new variables correctly set , benchmarking for each algo goes for 100 secs (its set on 600 in config) , when full cycle is done... nothing happens , not a single miner is picked for mining. Closing and reopening megaminer starts another benchmarking cycle, even tho all stats&hashrate files are present. Used pools NP, MPH , Yiimp.  Not observed such behaviour in previous versions. Unfortuantely unusable version on AMD , rolling back to 5.2

**Comment by mo35** [comment]
can we have option to exclude/disable power efficiency calculations altogether, something is wonky with it, at least on AMD setups

**Comment by tutulino** [comment]
please activate debuglog option, run and post log file.

**Comment by mo35** [comment]
solved infinite benchmark by changing $TimeSinceStartInterval -gt "same value of benchmark interval time"

**Comment by tutulino** [comment]
I´m looking for other solution, this as workaroud works, but you are disabling power based watchdog for first N seconds of each interval.
