### ISSUE TITLE
v.6.0 PowerLimit error (980Ti)

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#272]
Can make it possible to manually specify it?
PowerLimit Error screen scroll (many screens):
![20180203_mm60_plerror](https://user-images.githubusercontent.com/34758417/35774128-14aa74ca-0978-11e8-9e79-ac1b0b53a73f.PNG)

User account is Admin and UAC is desabled for let's MM start normaly (it's not good!)

MMPowLmt is empty 
![20180203_mm60_plstat2](https://user-images.githubusercontent.com/34758417/35774352-bfe6f4da-097d-11e8-9e6a-6db7f4feb972.PNG)

But in CURRENT screen NVIDIA monitoring we see correct PowLmt (!)
This is strange.

By the way, for OC my cards and set PowerLimit I use NVIDIA Inspector 1.9.6.5. This version **does not require admin rights** for this.

**Comment by tutulino** [comment]
Please post a log file

Changing power limit is made via NVIDIA-SMI and requires admin rights, I have tested low level NVML and also requires admin rights

**Comment by 1001rapid** [comment]
[2018-02-04_06-33-06.txt](https://github.com/tutulino/Megaminer/files/1693259/2018-02-04_06-33-06.txt)

Maybe the earlier version of this program (nvidia-smi) does not require admin rights? As well as Nvidia Inspector, the new version of which also requires admin rights.

**Comment by tutulino** [comment]
I think admin right are required by NVIDIA drivers releases ago, it´s no nvidia-smi, MM, nvdia inspector problem.

Test last master code, please

**Comment by 1001rapid** [comment]
I apologize, did not see that a new parameter was added to the GPUGROUPS section.
When I set the parameter "PowerLimits":"0", the benchmark switched to new algorithms
