### ISSUE TITLE
error cannot convert value

### ISSUE THREAD

**Issue by reuben12** [tutulino/Megaminer#273]
Hello,

Not sure if anyone can help me on this.  It's a bit of a glitch that popped up in version 5.2.  I was hoping it would disappear in newest version.  Instead of just throwing 1 error, it seems to have started 4 errors every time it refreshes though :D.  On the screen it shows the following errors every time it refreshes, plus 2 more that have scrolled off the screen that are similar but lines 232 and 233 both replace W.

Cannot convert value " [Not Supported]" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1:227 char:97
+ ... "[Not Supported]") {[int]($SMIresultSplit[5] -replace 'W','')} else { ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger

Cannot convert value " [Not Supported]" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1:229 char:97
+ ... "[Not Supported]") {[int]($SMIresultSplit[6] -replace '%','')} else { ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In the logs it is showing as 

02/04/2018 00:06:02...... ###### ERROR ##### Cannot convert value " [Not Supported]" to type "System.Int32". Error: "Input string was not in a correct format." at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 233
at <ScriptBlock>, <No file>: line 1
at get_gpu_information, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 212
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\core.ps1: line 84
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1
02/04/2018 00:06:02...... ###### ERROR ##### Cannot convert value " [Not Supported]" to type "System.Int32". Error: "Input string was not in a correct format." at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 232
at <ScriptBlock>, <No file>: line 1
at get_gpu_information, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 212
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\core.ps1: line 84
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1
02/04/2018 00:06:02...... ###### ERROR ##### Cannot convert value " [Not Supported]" to type "System.Int32". Error: "Input string was not in a correct format." at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 229
at <ScriptBlock>, <No file>: line 1
at get_gpu_information, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 212
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\core.ps1: line 84
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1
02/04/2018 00:06:02...... ###### ERROR ##### Cannot convert value " [Not Supported]" to type "System.Int32". Error: "Input string was not in a correct format." at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 227
at <ScriptBlock>, <No file>: line 1
at get_gpu_information, C:\Users\Reuben\Desktop\Megaminer-master\Include.ps1: line 212
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\core.ps1: line 84
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Reuben\Desktop\Megaminer-master\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1

Honestly everything seems to run fine.  It's just my whole screen is taken up my red error messages now.  I've gone through with a brand new config file and pulled out everything that I thought might be causing an issue, but no luck...

Any ideas?

**Comment by tutulino** [comment]
Please, download include.ps1 file from master branch and replace your copy, test again.

**Comment by reuben12** [comment]
[2018-02-04_03-49-45.txt](https://github.com/tutulino/Megaminer/files/1692700/2018-02-04_03-49-45.txt)
Thanks,

Still getting the error.  I've included the latest log file in case that helps.

**Comment by tutulino** [comment]
I have uploaded some changes to include.ps1 file, please download and test again
