### ISSUE TITLE
MM 6.0 - Some Bugs and Fixes

### ISSUE THREAD

**Issue by reset77** [tutulino/Megaminer#274]
Thanks again Tutulino for this software, Cool new features

There are some problems and some solutions here:

#1 - Excavator fails almost every Benchmark.... This made Benchmark Extremely long, Excavator had to be deleted from miners folder.

#2 - Problems with Bitcore, Timetravel, Lyra2z 
Watchdog keeps killing this Algos miners cause they fall below 70 GPU Usage, but this is normal for this miners.... this caused problems in benchmark

FIX: Change Watchdog in Core.ps1 line 950 $GpuActivityAverage -le 
change value from 70 to 20

Bitcore and Timetravel will work good

But Lyra2z had to be disabled.... problem persist because this algo fall to 0 in GPU Usage for about 2 seconds so the watchdog always kills it... possible solution maybe ad at least 3 seconds delay to the watchdog? just guessing here i`m still noob

#3 - Remove LBRY and DECRED from Suprnova.ps1 Line 108 - 113 .... ASICS Territory now

After fixing this... Benchmarks runs good and the new version works great with new features
Thanks!!

**Comment by Fedeparma74** [comment]
I solved the problem changing in the same line $TimeSinceStartInterval -gt "same value of benchmark interval time"

**Comment by tutulino** [comment]
It´s  a workaround, you are disabling watchdog, if miner hangs MM will not detect, I´m looking solutions.

Thanks

**Comment by reset77** [comment]
Thanks man...

I noticed the only Lyra2z miner that have this problem is DJM34 miner... others work good, so if you set the watchdog in 20, everything will work good and i guess watchdog still works when miner go down its usually below 20, thanks!!
