### ISSUE TITLE
New Megaminer-Master keeps benchmarking every coin per algo instead of just the main algo ???

### ISSUE THREAD

**Issue by jrafaelmdo** [tutulino/Megaminer#275]
The new megaminer 6b1 "ages" (sarcasm) to finish the benchmarks as it keeps benchmarking all the different coins mined by pool under the same algorithm ?

Why all coins need to be benchmarked ? instead of just the main algo ?

Every time a pool adds a new coin under an existing aldo do I need to run the benchmark again ?

BTW: Zergepool have servers in US and EU

![capture](https://user-images.githubusercontent.com/35340377/35782130-59e0641e-09eb-11e8-9840-cc9f50d18b44.PNG)

**Comment by Fedeparma74** [comment]
FIX: Change Watchdog in Core.ps1 line 950 $GpuActivityAverage -le
change value from 70 to 20 and $TimeSinceStartInterval -gt "same value of benchmark interval time"

**Comment by 1001rapid** [comment]
confirm
After 1.5 days of benchmarking, the statistics folder is almost empty
![20180205-stats-folder](https://user-images.githubusercontent.com/34758417/35786861-39d98f42-0a3b-11e8-8857-43ebf7fa8da6.PNG)
But I use PL70 in NVI
I'll try to use the fix specified above.

**Comment by tutulino** [comment]
It is visual defect, MM shows all coins as benchmark pending  but only will benchmark one (most priced).

**Comment by 1001rapid** [comment]
I apologize, did not see that a new parameter was added to the GPUGROUPS section.
When I set the parameter "PowerLimits":"0", the benchmark switched to new algorithms
