### ISSUE TITLE
extra layer of pool / coin selection config (wishlist)

### ISSUE THREAD

**Issue by mo35** [tutulino/Megaminer#276]
At the moment when you pull data from yiimp or altminer api you have no control on which pool particular coin is mined. would be nice if we could have another config layer , where we can define for example coin/pool preferences , for example to mine Lux only on Yiimp etc and ignore particular coin/algo on Altminer. At least i couldnt find way to control this aspect.

**Comment by tutulino** [comment]
This feature will not be available, for this you can create a pool file with coin/pools you want (use flypool as pattern for example).
