### ISSUE TITLE
ver.6.0 UAC desabled requires

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#278]
MM ver. 6.0b2
Win7 x64 sp1
Admin user account
"PowerLimits":"0" in GPUGROUPS
UAC Settings is minimum
![20180205_mm6_uac0](https://user-images.githubusercontent.com/34758417/35806729-950b90bc-0a91-11e8-8d03-eb05ed08b7bb.PNG)
The program starts and issues a request, waiting for the user's response:
![20180205_mm6_uac1](https://user-images.githubusercontent.com/34758417/35806918-361ef87c-0a92-11e8-9f10-79b5eb1d5578.PNG)
If you click "No", you get an error and start working.
![20180205_mm6_uac2](https://user-images.githubusercontent.com/34758417/35807004-7289a9a6-0a92-11e8-9bcf-3bbd8800bc73.PNG)
log file (@@DEBUGLOG=ENABLED)
[20180205_mm6_uac-2018-02-05_16-12-16.txt](https://github.com/tutulino/Megaminer/files/1695266/20180205_mm6_uac-2018-02-05_16-12-16.txt)

If I use "PowerLimit" features, MM also receive a request
![20180205_mm6_uac3](https://user-images.githubusercontent.com/34758417/35808410-b9a02244-0a96-11e8-9b6d-17d6521d262e.PNG)

If start "As Admin" - all fine, but it need UAC desabled too (for autostart)

I believe that there is a version of the program that does not require administrator rights to set the power limit. Because the Nvidia Inspector 1.9.6.5 does not require this.

**Comment by tutulino** [comment]
First request MM is adding path to windows defender excluded paths. Always ask you or only first run?

I could search if exists an old smi release but we would be slaves of that release, and new cards or drivers could not work.

I have readed admin right is  a driver requeriment

**Comment by 1001rapid** [comment]
>Always ask you or only first run?
Alwayas. I now noticed that in the window that is being called, also red there are inscriptions (errors).

>I could search if exists an old smi release but we would be slaves
)) The current version of the program is also not the freshest.
I tried to find and could not. In the installer (path) it does not exist. It turns out, you need to download the old drivers (they can be found on the official site), install them and try.

Okay, I'll disabled the UAC for now.

**Comment by 1001rapid** [comment]
I caught this window! It was not easy.)
![20180205_mm6_uac4_windowsdefender](https://user-images.githubusercontent.com/34758417/35814935-67f6a4ce-0aa8-11e8-839c-0fb605e6b1ec.PNG)
logfile:
[2018-02-05_19-07-01.txt](https://github.com/tutulino/Megaminer/files/1695859/2018-02-05_19-07-01.txt)

**Comment by tutulino** [comment]
do you have windows defender installed?

I see in log you windows 7 has powershell 5.0, my machines are windows 10 with 5.1. You can donwload this version and test.

**Comment by 1001rapid** [comment]
I did not install it. It was with Windows. I just installed Windows with minimal updates. And turned off everything I could.
Now I also turned off Windows Defender.
![20180206_mm6_uac_windowsdefender](https://user-images.githubusercontent.com/34758417/35862962-846a9c8a-0b5e-11e8-85e3-57ec0329435d.PNG)

The situation has not changed.
Log file: 
[2018-02-06_16-45-56.txt](https://github.com/tutulino/Megaminer/files/1699295/2018-02-06_16-45-56.txt)

**Comment by tutulino** [comment]
I see you have now powershell 5.1.

I have found this, but in windows 10 specified path dont exist, can you test?

https://stackoverflow.com/questions/43881583/add-mppreference-is-not-recognized-as-a-name

**Comment by 1001rapid** [comment]
In answer - http://www.madwithpowershell.com/2015/06/64-bit-vs-32-bit-powershell.html
I tried to start 32-bit version of PowerShell, but nothing has changed.
Log file:
[2018-02-07_04-03-47.txt](https://github.com/tutulino/Megaminer/files/1701357/2018-02-07_04-03-47.txt)
Your Windows 10 is x64 or x86?
If you use x86, I may still try to replace environment variables in PATH from "system32" to ""SysWOW64"

**Comment by tutulino** [comment]
All  my windows are X64,

Also you can delete that two lines from core.ps1....XD

**Comment by 1001rapid** [comment]
Works, and well. Does not bother me.
