### ISSUE TITLE
Q: "NVIDIA Automatic Gpu Power limit" - How does it work?

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#279]
Does the setting PERCENTTOSWITCH affect the choice of the PowerLimit mode?

**Comment by tutulino** [comment]
No relationship

**Comment by 1001rapid** [comment]
Then how does it work?
For example, if the profit difference is small, then I would prefer to use settings with less power consumption. The amount of electricity bills is also an important detail.

**Comment by tutulino** [comment]
@@PERCENTTOSWITCH is used to decide if a miner **that is running** must be replaced for other with best profit, only when new candidate profit is greater than actual in X percent actual is replaced.

What you want can be reached (aprox.) playing with pools profit factor. Lower profit factors increases differences between power limits profits

**Comment by 1001rapid** [comment]
I don't care how MM switch between pools. I am concerned that on one algorithm, on one pool, the program can switch to a higher Power Limit even if the difference is minimal. Let's say 0.001. I would like to be able to set a difference limit when choosing which Power Limit the program will work with.

It would be logical to associate this limit with @@percenttoswitch parameter.

**Comment by 1001rapid** [comment]
Now I see, that several miners on a certain algorithm, normally work at one Power Limit, and at another, higher - are unstable.
Can I use file "..._stats.txt" to control the choice of which Power Limit to use?
For example, parametrs "BestTimes", "BenchmarkedTimes", ActivatedTimes" and "FailedTimes" look as if, depending on them, the choice is made.

**Comment by 1001rapid** [comment]
No. Did not work out. I do not understand how this works.
Algorithm X is unstable at a power limit of 95%. I put an understated hashed (13000) in the statistics file, but it still includes the algorithms in the profitability list, algorithm X with a power limit of 95%. While there are statistics on power limits of 85%, 70%, 60% and it is much larger (PL60 - 7788100).
![20180209_plselect](https://user-images.githubusercontent.com/34758417/36006350-643480ac-0d4d-11e8-9a4a-75e26bb111d8.PNG)
Something I'm tired of studying ways to configure the program by searching options. But I liked it so much in versions 5.0-5.1. . (

**Comment by tutulino** [comment]
Profit list includes always all combinations, when you put a low hashrate in file you make position in that list goes down and it will never be selected as "best".

I´m thinking config options to exclude combinations (miner/algo/pool/powerlimit) like you want.

**Comment by 1001rapid** [comment]
It would be normal if the same algorithm was present on the list, but with a large hash and a lower power limit. Maybe inside the program, the power selection is fine, but the list makes me worry.)
