### ISSUE TITLE
Added yet another miner for AMD - Ethminer

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#28]
Ok this was a tough one lol (for me)
Most likely will work on Nvidia too. Havent test yet.

This is as fast or faster then Claymore for ETH and NO FEES. Can't dual mine but seriously who still does that? No profit in dual mining anymore (at least not for me at .14 / KW)

[EthMiner.json.txt](https://github.com/tutulino/Megaminer/files/1226572/EthMiner.json.txt)

@tutulino Darn it. This one is not benchmarking! Can you take a look at it please. Great miner for ETH. Would love to use it

**Comment by tutulino** [comment]
I get it, not easy (not api available) but now benchmark works.
Included in next release, cannot send you file because I have to mod a lot of files

**Comment by Imaminer** [comment]
OK for now I forced benchmark to work my manually creating the stats file lol...
