### ISSUE TITLE
issue with yiimp api after dcr/lbry removal

### ISSUE THREAD

**Issue by mo35** [tutulino/Megaminer#280]
something changed and i cant pinpoint issue , but megaminer cant connect to yiimp api (tho api is connectable via browser)

**Comment by tutulino** [comment]
You must check this url, not yiimp.eu/api

http://api.yiimp.eu/api/currencies

I have uploaded to master branch a new pool file with a delay between two internal api call, try it.

**Comment by mo35** [comment]
nope , log spew out bunch of red regarding yiimp

02/06/2018 12:46:38...... ###### ERROR ##### At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:258 char:234
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:304 char:297
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:339 char:92
+ ... ss="description">Be notified when participating or @mentioned.</span>
+                                                                   ~
Missing property name after reference operator.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:339 char:92
+ ... ss="description">Be notified when participating or @mentioned.</span>
+                                                                   ~
The '<' operator is reserved for future use.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:399 char:256
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:413 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:933 char:296
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:1758 char:227
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:1761 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.

At C:\_minershit_\Megaminer-6.0b1\pools\YIIMP.ps1:1777 char:24
+       <li class="mr-3">&copy; 2018 <span title="0.23418s from unicorn ...
+                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.

Not all parse errors were reported.  Correct the reported errors and try again. at <ScriptBlock>,

so on...

**Comment by tutulino** [comment]
There is something strange in your file, is returning an error in lines number too high, yiimp.ps1 file has only 185 lines.

I think it has downloaded with bad enconding..

**Comment by mo35** [comment]
well guess there is some ip ban or something on yiimp end , i can mine on yiimp.eu , i can access api url from one location , but not from IP my rigs located , so scratch that , its yiimp issue.
