### ISSUE TITLE
6.0 Nanopool Eth , disapears from list after few cycles

### ISSUE THREAD

**Issue by mo35** [tutulino/Megaminer#281]
tested on 2 amd rigs , just with Nanopool (3 algos) , after a while eth disapears only zec and etn remains , ending cycle doesnt bring eth back , full miner restart is needed. Something releated with error message "Detected more than 3 fails, cancelling combination ..." , not noticed any mining errors tho

**Comment by tutulino** [comment]
Please test last master branch code, I have uploaded a modification for watchdog.

**Comment by mo35** [comment]
took and replaced core from master , still after two cycles nanopool eth was gone from list

**Comment by tutulino** [comment]
It´s strage, now watchdog only mark a miner as "dead" is no speed over 40% in 20 reads (100 secs aprox)

I have uploaded a core.ps1 file with enhaced log for help to discover what is happening, please download, run and upload log when you get that fail.

**Comment by AbuHeissam** [comment]
i have same issue with all coin/miner combinations on MPH. 
full log:
[2018-02-10_10-15-05.txt](https://github.com/tutulino/Megaminer/files/1713227/2018-02-10_10-15-05.txt)

used latest MM version from here

**Comment by AbuHeissam** [comment]
here another log from a full runthroough until no minersßcoins left... last message in log:
02/10/2018 11:57:06...... No detected any valid candidate for gpu group RX580
[2018-02-10_10-47-41.txt](https://github.com/tutulino/Megaminer/files/1713288/2018-02-10_10-47-41.txt)

**Comment by tutulino** [comment]
Please check last master code, if you get error activate @@debuglog option in config and upload log.
