### ISSUE TITLE
Minimize mining window

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#282]
where can this be configured?
I want to turn it off. Want to see more details ))

**Comment by tutulino** [comment]
minimize or change size?

**Comment by 1001rapid** [comment]
Mining window start in minimize. I have to click on window tile in taskbar for restore it.

**Comment by tutulino** [comment]
You can play with this parameter in start .bat file

-WindowStyle normal/maximized/minimized/hidden

Default is -WindowStyle normal,

**Comment by 1001rapid** [comment]
This affects only the main MM window. Miners still running in minimized mode.  
Forget. If the program does not have special settings for this, perhaps this happens because it starts from under the Power Shell.
