### ISSUE TITLE
FYI: Power reporting not working with latest Nvidia Drivers 390.77

### ISSUE THREAD

**Issue by jrafaelmdo** [tutulino/Megaminer#283]
I have 4 rigs total

2 rigs ( 8 x 1060, 8x 1070ti) are using Nvidia drivers 390.65
2 rigs ( 8x 1050ti, 8 x 1050ti) using Nvidia drivers 390.77

The 2 rigs running 390.65 report power usage details correctly (fixed tdp at "0")

The 2 rigs running 390.77 reports 0 for power usage (fixed tdp at "0") I know its just cosmetic, but I will be downgrading to 390.65.

I have UAC in all my systems. so I dont think its related to windows but an actual change in the drivers.

Thanks

**Comment by jrafaelmdo** [comment]
@tutulino 

You are right, I found this someone reporting similar issue at nvidia forums.

https://devtalk.nvidia.com/default/topic/1024744/linux/nvidia-387-12-breaks-power-reading-in-nvidia-smi-/2

**Comment by tutulino** [comment]
if you find an old NVIDIA-SMI file that works with 1050ti you can replace it on MM folder.

**Comment by 1001rapid** [comment]
@jrafaelmdo 1050Ti - the most capricious graphics card. You need to carefully select the driver. The last of those that we know work - 384.94. But it CUDA 9.0

**Comment by 1001rapid** [comment]
@jrafaelmdo I checked drivers of version 390.65. At 1050 Ti they support the set of a Power Limit, but do not support power monitoring
