### ISSUE TITLE
OverdriveN issues (AMD)

### ISSUE THREAD

**Issue by yuzi-co** [tutulino/Megaminer#284]
1. OverdriveN.exe compiled as debug and requires debug dlls that are only available with installed Visual Studio
2. AMD Blockchain beta drivers (from August23) aren't supported by OverdriveN
There is an alternative, but gives less information about the GPU
https://github.com/emminer/adli
3. when nvidia-smi is executed on AMD systems it complains about missing nvml.dll and the error is 2 lines, which results in 2 fake nvidia cards showing.
I believe it should not be executed when there are no NVIDIA devices and messages from nvidia-smi can be skipped when they match "*nvml.dll*"

**Comment by tutulino** [comment]
I have uploaded new release of OverdriveN compiled as release.

Point 2 has difficult solution, code from overdriveN is taken from AMD ADL sdk examples. I´m using latest drivers with compute mode, I think there is no performance lost.

**Comment by yuzi-co** [comment]
There are a few miners that benefit from Blockchain drivers:
Cast XMR miner and MkxMiner (--asm mode)
All others show similar performance, but for MkxMiner, the --asm switch shows a significant improvement and there are plenty lyra2v2 coins out there worth mining

**Comment by yuzi-co** [comment]
"ADL2_OverdriveN_Capabilities_Get is failed" is the error

**Comment by tutulino** [comment]
I think that drivers has no implementation of ADL protocol, I can do nothing, sorry
