### ISSUE TITLE
How to exclude miner for one of the GPUgroups?

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#285]
In version 5.0 and 5.1, I manually put down an understated hashrate in the statistics files for one of the GPU groups. This allowed us to exclude some of the miners that were unstable in this group. How can this be done in the current version of the program? MM v.6.0b2

**Comment by tutulino** [comment]
Stats file is filled always while benchmarking and while minning if @@LIVESTATSUPDATE is enabled (zero speeds are not recorded)

You can fill file manually, but for a "speed" be valid must have "timesinceinterval" field greater than "BenchmarkintervalTime"*0.65.  This is to considerate valid only speed reads for last third of benchmarktime.

Hashrate is average of all speed in file that follow this.

**Comment by 1001rapid** [comment]
Do I understand correctly that if I want the miner was not included, I need to turn off the new function @@livestatsupdate, otherwise the program will still try to periodically run the miner? Or low hashrate will eliminate the miner of choice, as it was before?

**Comment by tutulino** [comment]
It´s not necessary to turn off but safer, if sometime that miner reach first profit position for that group and option is not disabled MM would start to record live speed and your manual speed would be one of X in stats file.

**Comment by 1001rapid** [comment]
I don't understand. That is, I can't disable any unstable miner GPU for a specific group? 
You've added so many new fields to the statistics files, why not add the top available - not available flag?

**Comment by 1001rapid** [comment]
It seems to help if you rewrite all the lines indicating the speed in the file with a Hashrate on the understated hashrate. But it's very, very uncomfortable.
I already made myself a sticker with the inscription "Find an analog MM"))

**Comment by tutulino** [comment]
I´m thinking config options to exclude combinations (miner/algo/pool/powerlimit) like you want.

**Comment by 1001rapid** [comment]
It seems to me that it will be too cumbersome in the configuration file. It's easier to do this in the Statistics files (in the Stats folder), since they are all there - by GPU groups, miners, algorithms and Power Limit.

Here, for example, a new @@ALGORITHMS option. I think it is convenient only for solo miners. I do not understand what they did not like the -Coinsname option in the baht file. Oh yes. These are coins, not algorithms. But still, I'm looking at this option and it scares me. I now need to watch her constantly, that she would be relevant.
And, if it is necessary to exclude only one algorithm? Or a few? And, if you need to check, are all included? Well, I need to know them all. Why do I need it? And look in the solid list of one name, not convenient.
But this is so, by the way. Not to remove it. Perhaps it was someone who is vitally important. I just would not want to have something like that at my request.
