### ISSUE TITLE
Feature request: Please add setting to ignore/exclude algos from config file.

### ISSUE THREAD

**Issue by jrafaelmdo** [tutulino/Megaminer#286]
Hello Sir,

Would it be possible to implement something like this in the config file ?

@@ExcludeAlgorithm= blake2s, etc...

MPM already have this feature can you look if you can ported to Megaminer ?

Thanks.

**Comment by eMTee72** [comment]
You could do that by adapting the specific miner file. However that may require adapting multiple files (as multiple miners may support a specific algo), so your suggestion makes things easier indeed.

**Comment by tutulino** [comment]
This feature will be available soon.

MPM and MM code are 90% differents now.

**Comment by tutulino** [comment]
Check last master branch code, I have added a config option to select what algorithms are minables for each gpu type.

**Comment by 1001rapid** [comment]
@jrafaelmdo Can you explain to me why you needed this option in the configuration file?
