### ISSUE TITLE
GroupName: ordering

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#287]
Please use the same ordering (preferred: alphabetically) of the GroupName in the Profits (Overview) as in the Profits (Detailed).
![image](https://user-images.githubusercontent.com/32677058/35925409-e6e86fc8-0c25-11e8-9305-b9174214285f.png)

**Comment by tutulino** [comment]
Check last code, I think it is solved

**Comment by eMTee72** [comment]
Initial check looks fine!
