### ISSUE TITLE
Profability Calculation

### ISSUE THREAD

**Issue by DrRobotto** [tutulino/Megaminer#29]
I run all the benchmarks and it shows that the Lyra2Rev2 is the most profitable algoritm among NiceHash, Zpool anfmd MPH. However, if I run NiceHashMinerLegacy directly it runs DaggerSia, which is way more profitable.

Any thoughts? 12×1060 Rig

**Comment by tutulino** [comment]
See if Lyra2 benchmark is correct, Alexis ccminer has problem with this algo and sometimes set a extremely high bechmark

**Comment by DrRobotto** [comment]
I will reinstall the new release 3.1 and I will post some screenshotd

**Comment by DrRobotto** [comment]
In the new release everthing runs fine
