### ISSUE TITLE
overdriven issue (again)

### ISSUE THREAD

**Issue by yuzi-co** [tutulino/Megaminer#292]
outputs 16 devices with a single real card:

> 0,2254,3200,122736,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008A
> 1,2254,3200,122736,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&02A
> 2,2254,3200,122736,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&03A
> 3,2254,3200,122736,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&04A
> 4,2254,3200,122769,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&05A
> 5,2254,3200,122769,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&06A
> 6,2254,3200,122769,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&07A
> 7,2254,3200,122769,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&08A
> 8,2254,3200,122769,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&09A
> 9,2254,3200,122769,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&10A
> 10,2254,3200,122802,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&11A
> 11,2254,3200,122802,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&12A
> 12,2254,3200,122802,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&13A
> 13,2254,3200,122802,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&14A
> 14,2254,3200,122802,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&15A
> 15,2254,3200,122834,200000,100,77000,0,Radeon RX 580 Series,PCI_VEN_1002&DEV_67DF&SUBSYS_E3661DA2&REV_E7_4&30760922&0&0008&16A

**Comment by tutulino** [comment]
Fixed in master branch code
