### ISSUE TITLE
Claymore ver.11 dual mining is back with keccak & blake2s (upgrade)

### ISSUE THREAD

**Issue by mo35** [tutulino/Megaminer#293]
would be nice to get upgrade in next version

**Comment by 1001rapid** [comment]
@mo35 https://github.com/tutulino/Megaminer/blob/master/changelog.txt line 509
"*Moved Dual miners to additional miners folders due to low profit and high number of benchmarks"
I agree. It is so infinite.)

**Comment by tutulino** [comment]
I will add claymore v11 to next code upload and reactivate pascal. Miners will continue in additional miners folders

**Comment by tutulino** [comment]
check last code
