### ISSUE TITLE
Excavator hostname MPH issue

### ISSUE THREAD

**Issue by diown** [tutulino/Megaminer#294]
Hello,

I am having issues with Excavator and MPH using the latest release. My hashes are returning 0.0 when using the hostname Megaminer enters in the json file (europe.hub.miningpoolhub.com). However when I use the IP address from the hub instead it's working fine. I know MultipoolMiner is converting the hostname to an IP address in the json files. Is anyone else experiencing the same issue with the latest Megaminer release?

**Comment by bigheadprawn** [comment]
I changed the followings and problem resolved.

Line 3 of the pattern file to (single line):
`{"id":1,"method":"algorithm.add","params":["#ALGORITHMPARAMETERS#","#SERVERTOIP#:#PORT#","#LOGIN#:#PASSWORD#"]}`

And line 387 of core.ps1 to (single line):
`$ConfigFileArguments = $ConfigFileArguments -replace '#PORT#',$Pool.Port -replace '#SERVER#',$Pool.Host -replace '#SERVERTOIP#',([Net.DNS]::Resolve($Pool.Host).AddressList.IPAddressToString | Select-Object -First 1) -replace '#PROTOCOL#',$Pool.Protocol -replace '#LOGIN#',$Pool.user -replace '#PASSWORD#',$Pool.Pass -replace "#GpuPlatform#",$TypeGroup.GpuPlatform   -replace '#ALGORITHM#',$Algoname -replace '#ALGORITHMPARAMETERS#',$Algo.PSObject.Properties.Value -replace '#WORKERNAME#',$WorkerName2  -replace '#DEVICES#',$TypeGroup.Gpus -replace '#DEVICESCLAYMODE#',$TypeGroup.GpusClayMode  -replace '#DEVICESETHMODE#',$TypeGroup.GpusETHMode -replace '#GROUPNAME#',$TypeGroup.Groupname -replace "#ETHSTMODE#",$Pool.EthStMode -replace "#DEVICESNSGMODE#",$TypeGroup.GpusNsgMode`

**Comment by tutulino** [comment]
Good solution, I will add some similar to next code upload.

**Comment by tutulino** [comment]
check last code
