### ISSUE TITLE
MPH wallets is no longer supported?

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#295]
Haven't used them, thought that it has always been. Now, compared with version 5.0 - there is a balance of the MPH displayed, v6.0 - no

**Comment by tutulino** [comment]
It´s a bug, I take note.

**Comment by tutulino** [comment]
Check you have changed api field in config.txt from

@@APIKEY_MINING_POOL_HUB
to 
@@APIKEY_MININGPOOLHUB

This was my case.

**Comment by 1001rapid** [comment]
Yes, I already guessed, when closely read config file )
