### ISSUE TITLE
Nanopool PASC wellet also not available

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#296]
I use dual mining for unstable (active) 1050 Ti. ETH - MPH or NiceHash / PASC - Nanopool.
Works great ) And the withdrawal is typed quickly )

I saw in changelog.txt:
"... ver. 5.0 beta 2...
*Removed dual mining with Pascal (Pasc), reason: dead coin..."

I think this is not entirely correct. For me it is very good for dual mining )

In config file use PASC wallet, like link in pool "ID.Payment-ID".
I tried and so "Payment-ID" only, too. Not works (

**Comment by tutulino** [comment]
check last code

**Comment by 1001rapid** [comment]
I update from master (branch) and still nothing
I tried
@@WALLET_PASC=af14824dd486f06d
@@WALLET_PASC=86646.af14824dd486f06d (like URL https://pasc.nanopool.org/account/86646.af14824dd486f06d)
@@WALLET_PASC=af14824dd486f06d.86646

**Comment by 1001rapid** [comment]
I added a line in NAOPOOL.ps1 for enable mining PASCAL to Nanopool
105 `        $PrePools +=[pscustomobject]@{"coin" = "PASCAL";"algo"="PASCAL"; "symbol"= "PASC";"port"= "15555";"Fee"=0.02;"Divisor"=1000000;"protocol"="stratum+ssl"};
`
wallet balance is checking, but still no desplayed
https://api.nanopool.org/v1/pasc/balance/86646.af14824dd486f06d
