### ISSUE TITLE
"Next Interval" timecode screen bug

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#297]
When "Screen Buffer Size" = "Window Size" timecode not displayed.
If the width of the window is slightly reduced, the timecode is displayed. Only
 the tabulation of the display of basic information is confused. But if you change the tab, the screen is updated and everything becomes OK
![20180210_displ_bug_1](https://user-images.githubusercontent.com/34758417/36057816-d93330b0-0e24-11e8-8093-68816f626353.PNG)
![20180210_displ_bug_3](https://user-images.githubusercontent.com/34758417/36057824-e93f8076-0e24-11e8-8cdd-73c2934cfc29.PNG)
![20180210_displ_bug_2](https://user-images.githubusercontent.com/34758417/36057867-b0203da2-0e25-11e8-9450-bd6dff686849.PNG)
Win7 x64 PowerShell 5.1.14409.1005

**Comment by tutulino** [comment]
Powershell is a little tricky in screen painting. When you get bad screening press X key, that redraw and resize screen
