### ISSUE TITLE
ZergPool - Fix for new API - Pool relaunched... Working good now

### ISSUE THREAD

**Issue by reset77** [tutulino/Megaminer#299]
ZergPool Relaunched today with new improved and stable infrastructure... very good coins

They had problems this week they were hacked and attacked with DDOS, Chainsplits and other stuff
But the pool seems to be working good now

There is a new address for API and STRATUM so need to change the following lines on Zergpool.PS1

Lines 54-82-117-119 change "zergpool.com" for "api.zergpool.com:8080"

Line 153 change "zergpool.com" for "mine.zergpool.com"

Also recommend lowering the "minimum workers" to 10 or 5 on config.txt... since the pool is new and some algos dont have too much people but they are profitable right now

Thanks!!

**Comment by 1001rapid** [comment]
Like the truth
http://zergpool.com/site/api

**Comment by tutulino** [comment]
Changed in master code.

**Comment by reset77** [comment]
Thanks Tutulino!! new version of MM is great
