### ISSUE TITLE
Yiimp api banned?

### ISSUE THREAD

**Issue by CryptoMonzt0r** [tutulino/Megaminer#30]
Think something is flooding the Yiimp api and getting my ip banned as I could not use Yiimp yesterday reset my router today was ok for a little while now cannot access Yiimp unless use vpn

**Comment by tutulino** [comment]
I´m calling hundred of times to Yiimp api manual or automatic and no ban, Yiimp web and api is very unstable for two last days.

MM only makes an api call for each interval defined time

**Comment by CryptoMonzt0r** [comment]
Ok thanks must be something else my end just thought I should check as I am running on a few machines I thought maybe it was flooding running to many MM from my ip
