### ISSUE TITLE
Lyra2V2 on zergpool

### ISSUE THREAD

**Issue by Paul-Trasca** [tutulino/Megaminer#300]
I receive this error on Zergpool Lyra 2v2 algo
![zerg](https://user-images.githubusercontent.com/30908920/36075802-7e6b31e4-0f5c-11e8-9a04-7ad52662c231.jpg)
Miner is working, stats on zergpool site is ok
First screen is this
![zerg](https://user-images.githubusercontent.com/30908920/36075845-ecbd3052-0f5c-11e8-8668-41840397d6ba.jpg)

**Comment by tutulino** [comment]
Check last master branch code

**Comment by tutulino** [comment]
duplicated with #304
