### ISSUE TITLE
LAN Rig Monitoring utility

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#301]
Can you write a utility for monitoring rigs in a local network?
That it would be possible to monitor the rigs from one computer.
Let even through a log file, only that it would be accessible for interactive viewing, as in version 5.
Here, for example, I have two rigs with MM version 5.0b2 and I can monitor them through the console file manager. In interactive. But it would be much more convenient if there was one common log file on all the rigs on the network.
Animation 2 rig monitoring:
https://youtu.be/5tKwqa1eUIw
![20180212_mm50b2_monitoring](https://user-images.githubusercontent.com/34758417/36079801-29faccb4-0f98-11e8-8e33-ce6f48e58871.JPG)

**Comment by zeuz542** [comment]
this would be the best feature out there, do not know why not all miners implement it. it is probably not that hard and it would save people with multiple rigs alot of hassle

**Comment by Steality** [comment]
Im monitoring my rig using powershell on main computer, version 5 log is more like monitoring log which provide me live display, cant do it at version 6 since change to debug log. I hope you can bring back old log using version 5, or create both monitoring and debug log for selection.

**Comment by tutulino** [comment]
Included in latest master code (see changelog)
