### ISSUE TITLE
The program runs for a long time

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#302]
After the last changes, the start time of the program increased dramatically.
A message appears on the screen
`Coindesk api was responsive..........`
And all ... I have my own Watschdog to run the program and it has time to work, and this is 210 seconds at system start and 90 seconds when the program is restarted.
[2018-02-12_13-37-03.txt](https://github.com/tutulino/Megaminer/files/1716052/2018-02-12_13-37-03.txt)

**Comment by 1001rapid** [comment]
Perhaps this happened after I reduced the parameter @@minworkers to 5. Now I'll try to return to 20.

**Comment by 1001rapid** [comment]
No. All the same long. More than a minute. Earlier it took 10 seconds.
current log
[2018-02-12_13-59-24.txt](https://github.com/tutulino/Megaminer/files/1716069/2018-02-12_13-59-24.txt)
Log file a week ago
[2018-02-04_06-33-06.txt](https://github.com/tutulino/Megaminer/files/1716074/2018-02-04_06-33-06.txt)

**Comment by tutulino** [comment]
Problem is high number of combinations when you are mining in a coin level pool (example zergpool)

I have made some optimizations in generation loops, please, test master branch code

**Comment by 1001rapid** [comment]
No...
`02/13/2018 01:55:04...... Loading Pools Information.............`
`02/13/2018 01:55:20...... Pool HashRefinery was responsive....`
`02/13/2018 01:55:20...... Pool MiningPoolHub was responsive....`
`02/13/2018 01:55:20...... Pool Zergpool was responsive....`
`02/13/2018 01:55:20...... Pool NICEHASH was responsive....`
`02/13/2018 01:55:20...... Pool Zpool was responsive....`
`02/13/2018 01:55:20...... Pool NANOPOOL was responsive....`
`02/13/2018 01:55:20...... Detected 283 pools......`
`02/13/2018 01:55:20...... 216 pools left after min workers filter.....`
`02/13/2018 01:55:20...... Coindesk api was responsive..........`
`02/13/2018 01:56:31...... Miners/Pools combinations detected: 165.........`
time: 01:11
I tried switch off ZergPool
`02/13/2018 01:58:40...... Loading Pools Information.............`
`02/13/2018 01:58:46...... Pool HashRefinery was responsive....`
`02/13/2018 01:58:46...... Pool MiningPoolHub was responsive....`
`02/13/2018 01:58:46...... Pool NICEHASH was responsive....`
`02/13/2018 01:58:46...... Pool Zpool was responsive....`
`02/13/2018 01:58:46...... Pool NANOPOOL was responsive....`
`02/13/2018 01:58:46...... Detected 116 pools......`
`02/13/2018 01:58:46...... 104 pools left after min workers filter.....`
`02/13/2018 01:58:46...... Coindesk api was responsive..........`
`02/13/2018 01:59:27...... Miners/Pools combinations detected: 131.........`
time: 00:41
Faster, but not faster than a week ago.
There were 10 (!) Seconds.
Something happened to the code during this time.

**Comment by tutulino** [comment]
Problem is number of combinations, for each combination now MM is reading two files from disk (one for hashrate and one for stats). for that example 262 files

I optimize more that loop but I think is not enough, I have ssd on all rigs and time is high but aceptable, I think somebody with non ssd disk may have extremely high times.

Please check last code and tell me.

If time is high yet, I will have to redesign all stats system to use less files.

**Comment by 1001rapid** [comment]
43 seconds
I tried the old versions of the files (`core.ps1, Include.ps1, OverdriveN.exe`), that I got from the backup ...
And there's also about 40 seconds. I do not even know ... The only thing I can think of now is Powers Shell 5.1.
Now I will try to return 5.0
