### ISSUE TITLE
Error Message: op_Addition

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#304]
Error Message from Log:
02/12/2018 13:50:13...... ###### ERROR ##### Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'. at <ScriptBlock>, C:\Users\...\6.0\core.ps1: line 924
at <ScriptBlock>, C:\Users\...\6.0\core.ps1: line 891
at <ScriptBlock>, <No file>: line 1

**Comment by tutulino** [comment]
post log please

**Comment by eMTee72** [comment]
[2018-02-12_13-37-19.txt](https://github.com/tutulino/Megaminer/files/1716454/2018-02-12_13-37-19.txt)

**Comment by podlbo** [comment]
i have similar error - > here is also my log
[2018-02-13_06-55-16.txt](https://github.com/tutulino/Megaminer/files/1718873/2018-02-13_06-55-16.txt)

**Comment by podlbo** [comment]
simmilar problem... and my LOG file
[2018-02-13_07-39-38.txt](https://github.com/tutulino/Megaminer/files/1720000/2018-02-13_07-39-38.txt)

**Comment by tutulino** [comment]
Please, check last master code, if you get error activate @@debuglog in config.txt and upload log.

**Comment by podlbo** [comment]
error from last time is solved ;) Thanks ;)
Im getting now new one 
###### ERROR ##### The operation has timed out. at <ScriptBlock>, C:\Megaminer-master\pools\MiningPoolHub.ps1: line 73

[2018-02-14_08-29-38.txt](https://github.com/tutulino/Megaminer/files/1723039/2018-02-14_08-29-38.txt)

**Comment by eMTee72** [comment]
Not seeing the op_Addition error anymore.

@podlbo: would you mind creating a new 'Issue' to document your new error message? That makes it easier for tutulino for follow-up.
