### ISSUE TITLE
cmdlet WriteLog issue

### ISSUE THREAD

**Issue by geckah** [tutulino/Megaminer#305]
New interval starting.............
Loading Pools Information.............
Pool NICEHASH was responsive....
Pool AHASHPOOL was responsive....
Detected 55 pools......
41 pools left after min workers filter.....
Coindesk api was responsive..........

cmdlet WriteLog at command pipeline position 1
Supply values for the following parameters:
LogFile:

Megaminer stops here sometimes after a forced restart. I've tried clearing the log and stats files but it doesn't work. So far the only way i can reliably get MM to work again is a fresh install

**Comment by tutulino** [comment]
Check last code in master branch, I think that bug is solved.
