### ISSUE TITLE
ERROR -Method invocation failed

### ISSUE THREAD

**Issue by podlbo** [tutulino/Megaminer#308]
I get new eeror wit latest master. - i did attach also log file

###### ERROR ##### Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'. at <ScriptBlock>, C:\Megaminer-master\core.ps1: line 952
at <ScriptBlock>, C:\Megaminer-master\core.ps1: line 916
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Megaminer-master\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1

[2018-02-14_08-29-38.txt](https://github.com/tutulino/Megaminer/files/1723588/2018-02-14_08-29-38.txt)

**Comment by podlbo** [comment]
with fresh new master, new error appear to me:

###### ERROR ##### Cannot find a variable with the name 'Request'. at <ScriptBlock>, C:\Megaminer-master\pools\HashRefinery.ps1: line 65

[2018-02-16_14-44-30.txt](https://github.com/tutulino/Megaminer/files/1731530/2018-02-16_14-44-30.txt)

**Comment by tutulino** [comment]
Fixed in master branch code
