### ISSUE TITLE
Error Message: The property '...' cannot be found on this object

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#309]
02/14/2018 22:27:32...... ###### ERROR ##### The property 'BestTimes' cannot be found on this object. Verify that the property exists and can be set. at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\core.ps1: line 768
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1
02/14/2018 22:27:32...... ###### ERROR ##### The property 'LastTimeActive' cannot be found on this object. Verify that the property exists and can be set. at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\core.ps1: line 848
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1
02/14/2018 22:27:32...... ###### ERROR ##### The property 'ActivatedTimes' cannot be found on this object. Verify that the property exists and can be set. at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\core.ps1: line 838
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1
02/14/2018 22:27:32...... ###### ERROR ##### The property 'BestTimes' cannot be found on this object. Verify that the property exists and can be set. at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\core.ps1: line 768
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Users\Miner\Downloads\MegaMiner\6.0\Megaminer.ps1: line 193
at <ScriptBlock>, <No file>: line 1

**Comment by tutulino** [comment]
fixed in last release
