### ISSUE TITLE
Miners not closing

### ISSUE THREAD

**Issue by CryptoMonzt0r** [tutulino/Megaminer#31]
After leaving it running for a few hours had multiple miners running I think it is not killing the dual minerproperly and then this causes errors which stop ccminer closing aswell. 
Also keep getting an error wrapper 4068

Get-Content : Cannot find path 'D:\Downloads\Megaminer-master\Wrapper_4068.txt' because it does not exist.
At D:\Downloads\Megaminer-master\Include.ps1:384 char:33
+                     $HashRate = Get-Content ".\Wrapper_$Port.txt"
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Downloads\Me...rapper_4068.txt:String) [Get-Content], 
ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
Get-Content : Cannot find path 'D:\Downloads\Megaminer-master\Wrapper_4068.txt' because it does not exist.
At D:\Downloads\Megaminer-master\Include.ps1:384 char:33
+                     $HashRate = Get-Content ".\Wrapper_$Port.txt"

**Comment by tutulino** [comment]
Wrapper error is fixed on next release, I´m trying get no closed miners error to solve it.

**Comment by CryptoMonzt0r** [comment]
Thank you and very much appreciated your work hands down the best multi miner I have used :)

**Comment by coderasm** [comment]
I use this script as a watchdog.

[gpu_watchdog.zip](https://github.com/tutulino/Megaminer/files/1229061/gpu_watchdog.zip)

**Comment by tutulino** [comment]
I will study that script, has many posibilities, THXS
