### ISSUE TITLE
Possible to set BTC for ahashpool and LTC for zergpool?

### ISSUE THREAD

**Issue by romajc84** [tutulino/Megaminer#310]
Cannot figure out how to do this in the config

**Comment by tutulino** [comment]
Zergpool only pay in BTC.

**Comment by david0815** [comment]
no, zergpool gets paid in all currencies that are being mined. 
You could edit the zergpool.ps1

**Comment by tutulino** [comment]
true, not possible in config.txt but you can edit zergpool.ps1 and change

 Pass          = "c=$Currency,mc=$zerg_symbol,ID=#WorkerName#"

to 

 Pass          = "c=LTC,mc=$zerg_symbol,ID=#WorkerName#"
