### ISSUE TITLE
Phoenix miner

### ISSUE THREAD

**Issue by Steality** [tutulino/Megaminer#312]
Suggest adding Phoenixminer. 
Im not a fan of eth mining, but my friend said it is slightly better than claymore.

**Comment by Steality** [comment]
Reopen because I tested it with significant hashrate. gtx1070x6 use lower power limit and give significant hashrate. Only benefit for single mining though. Try adding to MM but api only show power value, hashrate missing.

**Comment by Steality** [comment]
I cant display hashrate, through MM because of missing "result" using webrequest, even though it is the same structure with claymore. 
I can overclock more and powerdown more with higher hashrate with this miner, even though it only optimize for eth mode only.

**Comment by tutulino** [comment]
I have tried and structure api returns is not like claymore api, I get a screen capture

**Comment by Steality** [comment]
yeah instead of "result", it is display screen capture.. weird that both phoenix and claymore can read by Ethman.exe

**Comment by tutulino** [comment]
Solved, api must by called by tcp, not http.

Available in latest master code (you need all release, not only miners files)
