### ISSUE TITLE
stats-page/Time  + BTC to mBTC ?

### ISSUE THREAD

**Issue by david0815** [tutulino/Megaminer#313]
Please correct the time column on the stats page.
maybe change BTC value to mBTC. I did it, it looks a lot better.
or additional info in @@ Currency

Great work, keep it up
![1](https://user-images.githubusercontent.com/36031244/36324262-1ddee428-1354-11e8-8de0-6c62a8e7ca71.PNG)

**Comment by 1001rapid** [comment]
BTC/day looks fine too (without "btc" in chart)
my costimize view for compact
![20180220_compact-v](https://user-images.githubusercontent.com/34758417/36429074-b0f2b63e-1662-11e8-8ad9-63316fe305a2.PNG)

**Comment by david0815** [comment]
I do not like the leading front zeros.
8.34 looks better than 0.000834. do not you think so?

**Comment by tutulino** [comment]
Changed to mtbc and fixed stats time bug in next code upload
