### ISSUE TITLE
 Time stat reporting too high

### ISSUE THREAD

**Issue by Kelarik** [tutulino/Megaminer#314]
Not quite sure exactly what the Stats for Time are trying to show, but it seems a little ambitious. Actual uptime on this is ~48 hours, running a single GPU so it's not counting time that way. Running a fresh copy of the latest Commit
![time](https://user-images.githubusercontent.com/648269/36358443-52ecf50c-1506-11e8-80c1-acd4791fc50d.png)

**Comment by 1001rapid** [comment]
@Kelarik This is important only for the first run of the program.
Then, during subsequent launches, the previous miner is not killed until a new one starts.

**Comment by tutulino** [comment]
Solved in master branch code
