### ISSUE TITLE
The dollar sign is displayed as "36".

### ISSUE THREAD

**Issue by 1001rapid** [tutulino/Megaminer#316]
Windows 7 x64 SP1 ENG (US)
PowerShell 5.1
![20180220_dollar_sign](https://user-images.githubusercontent.com/34758417/36405149-32af2c56-1600-11e8-8d4d-2b691595e718.PNG)

**Comment by Steality** [comment]
at core.ps1  there is slight typo

            'DOLLAR'     {$LocalSymbol=+[convert]::ToChar(36)  ; $localBTCvalue = [double]$CDKResponse.usd.rate}

remove the +

**Comment by 1001rapid** [comment]
@Steality Yeah! It,s work
I modified line 348 to
` 'DOLLAR'     {$LocalSymbol=" "+[convert]::ToChar(36)  ; $localBTCvalue = [double]$CDKResponse.usd.rate}
`
to ensure that in the list of profitability the dollar sign was repulsed by a space from the figures

And change in Line 1096 `" $LocalSymbol/W"` to `"$LocalSymbol/W"` for remove double space in main stat info

![20180220_dollar_sign_v](https://user-images.githubusercontent.com/34758417/36421512-be071d4c-1649-11e8-9a05-8eafce3e7bb0.PNG)

**Comment by tutulino** [comment]
Fixed next code upload
