### ISSUE TITLE
ahashpool upcoming change ! !

### ISSUE THREAD

**Issue by SerpentDrago** [tutulino/Megaminer#317]
Announcement: [2018-02-20 18:32 UTC] In a week, on 2018-03-01, We will be updating the units for scrypt to mBTC/Gh/day (from previously mBTC/Mh/day) to match other pools. This shows more significant figures/digits (less meaningless zeros) by shifting the decimal point, allowing more accurate calculations. In the near future, we may also do this for other algos that has gone ASIC, such as myr-gr, lbry, keccak and skein. Please make sure your scripts/programs have the correct factors/multipliers. If you are unsure of what this means, remove scrypt from your mining algos.

**Comment by tutulino** [comment]
Scrypt is not minable with MM (Asics domain)
