### ISSUE TITLE
Zergpool is scam pool,remove it pls!

### ISSUE THREAD

**Issue by czjlj** [tutulino/Megaminer#322]
Eat profits and no pay.
https://snag.gy/0F1h5c.jpg
https://snag.gy/2sy9oH.jpg

**Comment by Steality** [comment]
I mine recently zergpool got phi algo mining splitted chain, result in insanely higher profit. We are mining a wrong chain resulting in wasted hashpower with no payout. This issue is more common at hashrefinery and algo such as nist5, x17. I already issued this problem recently.

![capture](https://user-images.githubusercontent.com/33076514/36534746-62bc7e2c-1802-11e8-9525-fcac029e5d3d.JPG)

**Comment by Steality** [comment]
For now if a fork happen or you see some fishy insanely higher profitability on selected algo, just avoid the pool for awhile.

**Comment by czjlj** [comment]
Of course, I understand, forks, spoons, etc., but why the balance changed? This is what has already been confirmed, sent to the stock exchange, sold and returned back, in the form of BTC coin, or does this pool work differently and how could this happen?I mining some days but never paid to me.I will not believe Zergpool anymore.

**Comment by czjlj** [comment]
`Notice by matching your picture and mine and see the dropped payout at 20.00 hour`
It was cleared my balance not payout.The detail is http://zergpool.com/?address=1KschyWXnfrKnYb8dqZnsSA9YbUCibLQ3K

**Comment by 1001rapid** [comment]
sometimes pools steal money
for example, Supronova stole from me 1 XMR
on this principle, I can ask to exclude it from the program

**Comment by tutulino** [comment]
I lost some day profits also, but I dont think it is scam.

I think this is a new pool and have some bugs yet.

**Comment by Steality** [comment]
I agree, even this pool have problem in connectivity recently. Run fine for a while but always end mining with rejected share with "boo" all day long. Using excavator ends up shows 0 hashrate.

**Comment by 1001rapid** [comment]
OMG! I will be rich!
![20180225_zerg](https://user-images.githubusercontent.com/34758417/36645841-df3a21e6-1a7f-11e8-9409-15d1d2554227.PNG)

**Comment by Steality** [comment]
Opps,  Profit that high, wish it didnt orphaned. 

Anyway better switch to other algo before wasting your time and electricity.

**Comment by 1001rapid** [comment]
Strange pool
In start page: "Payouts for all other currencies are made automatically every 12 hours for all balances above 0.005 in BTC equivalent, or 0.0005 on Sunday."
I have 0.001 BTC a few day ago. There is still no payment.
