### ISSUE TITLE
op_Addition

### ISSUE THREAD

**Issue by podlbo** [tutulino/Megaminer#323]
with latest master i get this:
![slika](https://user-images.githubusercontent.com/33230718/36545117-7ed9393e-17e8-11e8-8b7a-2194093f99ec.png)

here is also LOG:
[2018-02-22_11-29-18.txt](https://github.com/tutulino/Megaminer/files/1748350/2018-02-22_11-29-18.txt)

**Comment by eMTee72** [comment]
Looks like the same error I had, see issue #304

**Comment by podlbo** [comment]
Yes :) did you solve it?

**Comment by eMTee72** [comment]
Actually, Tutulino did. I used the most recent code (not the 6.0b1 release, but this one: https://github.com/tutulino/Megaminer/archive/master.zip)

**Comment by podlbo** [comment]
in this case it is open for me --- i get this with latest master avalible to download.

**Comment by eMTee72** [comment]
your screenshot doesn't show the version. Are you saying that you're running version 6.03b?

**Comment by podlbo** [comment]
Yes im on latest version 6.03b. After couple of runs and pool switches error dissapere from main windov of MM. Maby MM can solve this problem by himself?

**Comment by tutulino** [comment]
Check last code

**Comment by podlbo** [comment]
For now no problem - i did update with last code avalible. For now all clear from errors - Thanks ;)
