### ISSUE TITLE
Cant add custom pool for whattomine virtual server

### ISSUE THREAD

**Issue by zorvalth** [tutulino/Megaminer#324]
I tried to make a custom ps1 file for mining GBX on Altminer (GBXAltminer.ps1) based on non api flypool.ps1 file.  I added whattominepoolorder=GBXAltminer, changed  the @@MINWORKERS to 0 just in case if the scripts is checking it, added GBX address too. When I start.bat select MAnual and GBXAltmienr is all fine, starts mining GBX on Altminer. But when I select AUTO or AUTO24 and choose Whattomine it sasy NO POOLS. 

I tested with your FLYPOOL.ps1 , added ZEC address and whattominepoolorder in the config and when i select AUTO or AUTO24 it starts mining it with no problem, so the problem should be in my modified GBXAltminer.ps1 file.

Tested on the freshly downloaded master and on the last release, same thing happens on both

[GBXAltminer.zip](https://github.com/tutulino/Megaminer/files/1751099/GBXAltminer.zip)

...

config and GBXaltminer.psq attached.

**Comment by tutulino** [comment]
Coin name is "gobyte" not "Gbxcoin"

Comparison between pools and WTM is made by coinname and algoname.

**Comment by zorvalth** [comment]
Great, it works now! I didnt think that coinname got any meaning. 

Regards!
