### ISSUE TITLE
Cant add Custom Pool coin which is not on the MAIN coins.json page

### ISSUE THREAD

**Issue by zorvalth** [tutulino/Megaminer#325]
After GBXAltminer works, I tried to add LUXAltminer but still doesnt show on Auto->whattomine 

I'm attaching the LUXAltminer.ps1 and the config

p.s. also the Interval on WTM is 0 (the PPS and PPLS intervals are not changed in the config...)

[LUXAltminer.zip](https://github.com/tutulino/Megaminer/files/1751505/LUXAltminer.zip)

**Comment by tutulino** [comment]
I will test, you can use same pool file for GBX and LUX, you dont need two
pool files

2018-02-23 12:45 GMT+01:00 zorvalth <notifications@github.com>:

**Comment by zorvalth** [comment]
I have only basic skills, for making them in the same file i will need template and probably very few people would be using this feature i dont want to ask you do it :)

btw on every interval refresh which is pretty much every few seconds appi of WTM is not accessible, probably something to do with their cloudfire. Maybe putting a small interval between WTM request will help...

**Comment by tutulino** [comment]
Add it to same file is easy, same way you have added three pools for one coin (one for each location), you can add more lines with diferents values in fields, different server, coin name, etc.
 
I see one problem is wtm algo is "phi1612" while mm calls that algo "phi", solved, but I have discovered that I need to change other things (I dont know yet if is possible) to calculate what numeric factor use for non main screen algos.

**Comment by tutulino** [comment]
if you want to add some algo with different name, you need add to this include.ps1 function

function get_algo_unified_name ([string]$Algo) {

    $Result=$Algo
    switch ($Algo){
            "sib" {$Result="x11gost"}
            "Blake (14r)" {$Result="Blake14r"} 
            "Blake (2b)" {$Result="Blake2b"} 
            "decred" {$Result="Blake14r"}
            "Lyra2RE2" {$Result="lyra2v2"}
            "Lyra2REv2" {$Result="lyra2v2"}
            "sia" {$Result="Blake2b"}
            "myr-gr" {$Result="Myriad-Groestl"}
            "myriadgroestl" {$Result="Myriad-Groestl"}
            "daggerhashimoto" {$Result="Ethash"}
            "dagger" {$Result="Ethash"}
            "hashimoto" {$Result="Ethash"}
            "skunkhash" {$Result="skunk"}
            "PHI1612" {$Result="Phi"}
            }        
     $Result       

}

**Comment by zorvalth** [comment]
Ok i wil ltry with different coins in the same file.  
I saw that in wtm is phi1612 and tried that too but still didnt work. 
The only way i see it to work is to get the id from calculators.json and use the particular coin json calc, for example LUx is id 212, and its json calc is:

https://whattomine.com/coins/212.json?utf8=%E2%9C%93&hr=18&p=0&fee=0.0&cost=0.0&hcost=0.0&commit=Calculate

but if you make many wtm requests you need a 1-2 sec between them because of the cloudfire protection.

**Comment by tutulino** [comment]
how do you get that json parameters?

"utf8=%E2%9C%93&hr=18&p=0&fee=0.0&cost=0.0&hcost=0.0&commit=Calculate"

I´m looking for that info

**Comment by tutulino** [comment]
I have asked wtm admin. While he answer me, also for add a new algo you must add wtm factor for that algo, this factor is default hashrate that appears in main/coin page 
```

function get_WhattomineFactor ([string]$Algo) {
    
   #WTM json is for 3xAMD 480 hashrate must adjust, 
   # to check result with WTM set WTM on "Difficulty for revenue" to "current diff" and "and sort by "current profit" set your algo hashrate from profits screen, WTM "Rev. BTC" and MM BTC/Day must be the same
            
            switch ($Algo)
                        {
                                "Ethash"{$WTMFactor=84000000}
                                "Groestl"{$WTMFactor=63900000}
                                "Myriad-Groestl"{$WTMFactor=79380000}
                                "X11Gost"{$WTMFactor=20100000}
                                "Cryptonight"{$WTMFactor=2190}
                                "equihash"{$WTMFactor=870}
                                "lyra2v2"{$WTMFactor=14700000}
                                "Neoscrypt"{$WTMFactor=1950000}
                                "Lbry"{$WTMFactor=315000000}
                                "Blake2b"{$WTMFactor=3450000000} 
                                "Blake14r"{$WTMFactor=5910000000}
                                "Pascal"{$WTMFactor=2100000000}
                                "skunk"{$WTMFactor=54000000}
                                "nist5"{$WTMFactor=57000000}
                                "Phi"{$WTMFactor=24000000}
                        }


              
         $WTMFactor       
    
    }
    
```

**Comment by tutulino** [comment]
I´m getting "forbidden" for _http://whattomine.com/calculators.json_ for a long time. banned or closed page?

**Comment by zorvalth** [comment]
It works on my end: https://vgy.me/fMVhDu.png

Ti get the info for particular coin in wtm in json, goto the coin calc

https://whattomine.com/coins/212-lux-phi1612

then, add your parameters like hash, watts, diff if needed and click calculate and you get something like this:

https://whattomine.com/coins/212-lux-phi1612?utf8=%E2%9C%93&hr=50&br_enabled=true&br=10.0&d_enabled=true&d=12810.705&p=400.0&fee=0.0&cost=0.1&hcost=0.0&commit=Calculate

Then add ".json" right before the "?utf8" and you get the json link:

https://whattomine.com/coins/212-lux-phi1612.json?utf8=%E2%9C%93&hr=50&br_enabled=true&br=10.0&d_enabled=true&d=12810.705&p=400.0&fee=0.0&cost=0.1&hcost=0.0&commit=Calculate

You can delete everything from the id to ".json" it doesnt change the result you get something like this:

https://whattomine.com/coins/212.json?utf8=%E2%9C%93&hr=50&br_enabled=true&br=10.0&d_enabled=true&d=12810.705&p=400.0&fee=0.0&cost=0.1&hcost=0.0&commit=Calculate

**Comment by tutulino** [comment]
Test last master code, I have made a lot of changes to WTM pool. Less api calls, more acurate data, etc.

**Comment by zorvalth** [comment]
LUX is working now, but it shows 0.00 USD/EUR

Screenshot:
https://vgy.me/GdDhNn.png

tried phi and phi1612 but it didnt make difference, do you get any value?

**Comment by tutulino** [comment]
In manual mode is normal data not shown.

In auto24h problem is that whattomine json for coins not in main page has not 24h value, I have uploaded a new file, data are shown in 24h mode, but data are "non 24h" data.

**Comment by zorvalth** [comment]
Ok, but if it doesnt use 24h diff to calculate the profit will fluctuate in big ranges on every refresh, because the current diff is highly inaccurate.

**Comment by tutulino** [comment]
True...but is only available info

**Comment by zorvalth** [comment]
Isnt it possible to get the info from the WTM specific coin calc json page?

**Comment by tutulino** [comment]
No, you can see, no 24h profit available

2018-03-02 11:46 GMT+01:00 zorvalth <notifications@github.com>:

**Comment by zorvalth** [comment]
Thats not true. See here: https://vgy.me/KCfDfy.png
the set difficulty is 18 369, you can see on the bottom that this value correspond to Difficulty 24h, and not the current Difficulty which is 28,832.778 from the screenshot. And when you click calculate it calcualtes with the Diff24h, and if you add .json in the link as i told you earlier and open the https://whattomine.com/coins/212.json?utf8=%E2%9C%93&hr=24&p=400.0&fee=0.0&cost=0.1&hcost=0.0&commit=Calculate it still calculates with Diff24h value :)

**Comment by tutulino** [comment]
MM dont use difficulty field , use profit field based on 24h difficulty,
you cant get it from that page.

2018-03-02 12:28 GMT+01:00 zorvalth <notifications@github.com>:

**Comment by zorvalth** [comment]
Ok, so the safest way is to use coins from the main page only, right?
