### ISSUE TITLE
N-PalginNeoWrap showing too high revenue?

### ISSUE THREAD

**Issue by VukaKun** [tutulino/Megaminer#326]
This can't be right, I'm mining on a 1080Ti, look at those Rev./Day values. Megaminer is basically stuck on neoscrypt because of this.

![capture](https://user-images.githubusercontent.com/27901969/36621065-7d6457be-18f6-11e8-9b54-5a79d3723b79.PNG)

**Comment by tutulino** [comment]
Delete stats files for that miner/algo

If you have @@LiveSpeedUpdate enabled in config.txt and your active miners section shows real speed it will be corrected automatically

**Comment by VukaKun** [comment]
That did nothing, why close the issue without any feedback?

**Comment by tutulino** [comment]
what speed do you get in active miners section?

I close issue when I think is solved to see only pending task, I dont get feedback for a lot of people and issue stays open for long time.

You can reopen issue if you want.

**Comment by VukaKun** [comment]
@tutulino No problem, buddy :) I figured it out, it's reporting MH/s instead of kH/s.

**Comment by tutulino** [comment]
I have added Palgin miner fork by just-a-miner, works a lot better than PalginNeoWrap and speed is at least the same.

**Comment by VukaKun** [comment]
Alright, that'll do!
