### ISSUE TITLE
Disconnects

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#33]
This is on ALL rigs at exactly the same time. All rigs are running 3.2
For now I removed Ethminer and am mining ETH with Gateless.

Please see pic here

https://s28.postimg.org/tcb1t2g3h/ethminer_fail.jpg

Thanks for looking into this.

**Comment by tutulino** [comment]
When miner is launched I have no control over it, It seems a problem of ethminer. Definitive test is launch in a batch file same command MM launch and see if same result happens

**Comment by Imaminer** [comment]
Running tests now. I will let you know changes if successful
