### ISSUE TITLE
Error on 6.0 config 

### ISSUE THREAD

**Issue by Firstishe** [tutulino/Megaminer#330]
@@ALGORITHMS_NVIDIA=bitcore,blake2s,blakecoin,c11,cryptonight,Equihash,Ethas**h,,Et**hash_Blake2b,Ethash_Blake14r,Ethash_Keccak,Ethash_blake2s,Ethash_pascal,Ethash_Lbry,groestl,hsr,jha,Keccak,keccakc,lbry,lyra2v2,lyra2z,Myriad-Groestl,Neoscrypt,nist5,pascal,phi,polytimos,sib,skein,skunk,timetravel,tribus,veltor,whirpool,x11evo,x11gost,x14,x16r,x17,xevan

**Comment by tutulino** [comment]
I see it after release, is fixed in master branch.

I think it dont affect working.
