### ISSUE TITLE
Error Message DUPLICATED ALGO ETHASH ETHASH ETHASH ETHASH ETHASH ETHASH ETHASH ON N-ClayDual N-ClayDual N-ClayDual N-ClayDual N-ClayDual N-ClayDual N-ClayDual

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#331]
Error occured as of version 6.0 (released yesterday).

**Comment by tutulino** [comment]
Have you made clean install?

I think you are using N-claydual from old releases.

**Comment by eMTee72** [comment]
No clean install and indeed had an N-ClayDual miner in the Miners folder, so I tend to agree with you.
I'm fine with closing this one (will create a new Issue if reoccurs), however I'm also thinking for some time now that there's a need to change the miners approach. Something like:
1. Miners require a minimal version of MM (and/or vice versa)
2. The Bin folder has a sub-folder per MM version. Eg: .\Bin\MM5.2\N-ClayDual and .\Bin\MM6.0\A-GatelessGate.

If you think that would make sense, let me know and I log it as a new topic?

**Comment by trillhc** [comment]
I have identical issue also with clean install running Nicehash and ahashpool...i commented out line 634 in core.ps1 and it seems to working fine for now, still bench marking though.

**Comment by tutulino** [comment]
@trillhc N-claydual is not included as default in miners folder, are you sure is same error?

**Comment by tutulino** [comment]
@eMTee72 your ideas is good, but there is a ton of pending task and is not usually I change miners structure.

**Comment by tutulino** [comment]
@eMTee72 dont´worry, I usually need help for:

- Beta testing
- Config/readme explanations in native english.
