### ISSUE TITLE
KECCAK on ZergPool: profit too high?

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#332]
Just to be sure: is MM keeping in mind that KECCAK is in mBTC/GH/day?
Quote (from ZergPool website): values in mBTC/Mh/day (mBTC/GH/day for sha256, **keccakc**, scrypt, qubit, blake, x11 algos, Kh for yescrypt, kS for equihash)

It seems the estimates for KECCAK 5MaxCoin) is a bit on the high end as of today / yesterday...

**Comment by tutulino** [comment]
keccakc and keccak are different algos....

Kekkakc is considered as mBTC but keccak not.

**Comment by eMTee72** [comment]
If different algo's: N-CcminerTpruvot.json mentions

Algorithms": [
                {"skunk":"-a skunk"},
                {"jha":"-a jha"},
                {"Tribus":"-a tribus"},
                {"lyra2z" : "-a lyra2z" },
                {"lyra2v2" : "-a lyra2v2" },
                {"whirpool":"-a whirl"},
                {"phi":"-a phi"},
                {"polytimos": "-a polytimos"},
                {"keccakc":"-a keccakc"},
                **{"keccak":"-a keccakc"}**
                ]

So that last line is then not correct?

**Comment by tutulino** [comment]
true, it´s not correct, must be

{"keccak":"-a keccak"}
