### ISSUE TITLE
LAN rig monitoring using older MM 5 log

### ISSUE THREAD

**Issue by Steality** [tutulino/Megaminer#334]
Im monitoring my rig using powershell on main computer on local network, version 5 log is more like monitoring log format which provide me "live" display, but in version 6 it has change to debug log. I hope you can bring back version 5 old log format, perhaps in additional folder. 
Since this feature is purely cosmetic, I am asking too much already, since you are busy fix bug and performance right now.

**Comment by 1001rapid** [comment]
why did you open a new issue?
The author also wrote that he will deal with this issue - https://github.com/tutulino/Megaminer/issues/301

**Comment by Steality** [comment]
My bad, I am sorry closing now

**Comment by 1001rapid** [comment]
@Steality You can add a comment there. That it would be seen how this function is needed.)
