### ISSUE TITLE
Version 6 Error and Crash

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#335]
Latest version. 
![error](https://user-images.githubusercontent.com/30805282/36650391-210c4978-1a71-11e8-874e-4e95f69537d2.JPG)

**Comment by Imaminer** [comment]
Tried again...crashed again. This time was Xevan but happens with random algo's

02/26/2018 11:03:59...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:03:59...... Loading Pools Information.............
02/26/2018 11:04:06...... Pool Zergpool was responsive....
02/26/2018 11:04:06...... Detected 168 pools......
02/26/2018 11:04:06...... 96 pools left after min workers filter.....
02/26/2018 11:04:06...... Coindesk api was responsive..........
02/26/2018 11:04:07...... Miners/Pools combinations detected: 64.........
02/26/2018 11:04:07...... Active Miners-pools: 64.........
02/26/2018 11:04:07...... Pending benchmarks: 8.........
02/26/2018 11:04:07...... Detected more than 3 fails,cancelling combination  for A-SgminerXevan/XEVAN/solaris with Power Limit 0 (id 61-0) for group AMD
02/26/2018 11:04:07...... No detected any valid candidate for gpu group AMD
02/26/2018 11:04:12...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:17...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:22...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:28...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:33...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:38...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:43...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:48...... ###### ERROR ##### Index operation failed; the array index evaluated to null. at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 949
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:50...... Detected miner error A-SgminerXevan/XEVAN (id 61-0) --> C:\Megaminer-6.0\Bin\AMD-sgminerXevan\sgminer.exe --api-listen -o stratum+tcp://mine.zergpool.com:3739 -u 1EPzDdtzWxAX3f7Ta7ZcA4Ub8sukAmquoB -p c=BTC,mc=XLR,ID=Rig2 --device 0,1,2,3 --api-port #APIPORT# --gpu-platform 0 -k xevan-mod --intensity 15
02/26/2018 11:04:50...... System.Diagnostics.Process (sgminer),True,100,1929
02/26/2018 11:04:54...... New interval starting.............
02/26/2018 11:04:54...... "AverageCpu = 0 % | MemoryUsage = 40.25 % | VirtualMemoryUsage = 18.89 % |  PercentCFree = 64.41 % | Processes = 105 | Connections = 65"
02/26/2018 11:04:54...... ###### ERROR ##### Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4028" at Invoke_TcpRequest, C:\Megaminer-6.0\Include.ps1: line 648
at Get_Live_HashRate, C:\Megaminer-6.0\Include.ps1: line 741
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 955
at <ScriptBlock>, C:\Megaminer-6.0\core.ps1: line 938
at <ScriptBlock>, <No file>: line 1
02/26/2018 11:04:54...... Loading Pools Information.............
02/26/2018 11:05:01...... Pool Zergpool was responsive....
02/26/2018 11:05:01...... Detected 168 pools......
02/26/2018 11:05:01...... 81 pools left after min workers filter.....
02/26/2018 11:05:01...... Coindesk api was responsive..........
02/26/2018 11:05:02...... Miners/Pools combinations detected: 59.........
02/26/2018 11:05:02...... Active Miners-pools: 64.........
02/26/2018 11:05:02...... Pending benchmarks: 8.........
02/26/2018 11:05:02...... Detected more than 3 fails,cancelling combination  for A-SgminerXevan/XEVAN/solaris with Power Limit 0 (id 61-0) for group AMD
02/26/2018 11:05:02...... No detected any valid candidate for gpu group AMD

**Comment by tutulino** [comment]
Please, set @@debuglog=ENABLED in config.txt and upload a log file with error

**Comment by Imaminer** [comment]
Ok set it. Letting it run now until the next crash..

**Comment by Imaminer** [comment]
Ok it crashed again - here is log with debug=enabled
errors and crash are about 3/4 of the way down the file
I am now using your version from 2.13.18 and it runs with no issues.
Thanks

[2018-02-26_15-54-01.txt](https://github.com/tutulino/Megaminer/files/1762324/2018-02-26_15-54-01.txt)

**Comment by tutulino** [comment]
I see where problem is, MM is not able to get your gpu activity and watchdog marks all miners as "fail"

I have made some changes to master code but I think is not enough.

What gpus do you have?

Please, get last code and run gpulist.bat, post result.

**Comment by Imaminer** [comment]
Rig 1-5
RX 470 (3)
RX 480 (3)
RX 570 (5)
390 (2)
RX 580 (2)

All other rigs are NV....

**Comment by tutulino** [comment]
Please, get last code and run gpulist.bat, post result.

**Comment by Imaminer** [comment]
Rig 2 - No results. Just get "press key to continue"
Rig 1 -
![rig1](https://user-images.githubusercontent.com/30805282/36811979-a9117d56-1c9d-11e8-9c4a-1e1c4f1a382a.JPG)
Rig 3 - No results. Just get "press key to continue"
Rig 5 - 
![rig 5](https://user-images.githubusercontent.com/30805282/36812163-35e6a1c0-1c9e-11e8-91cb-7343cc6ff552.JPG)

**Comment by tutulino** [comment]
We must choose one rig to study, for example Rig 2. What cards it has?

**Comment by tutulino** [comment]
Strange, I can understand MM dont detect R9 cards, but I dont understand why is not detecting RX series.

I need teamviewer access to debug and see, if you want, I need change language to english before (I think you are from Rusia)

**Comment by Imaminer** [comment]
I am in USA. East coast time. EST.
Lets do this Monday ok? I will send you a PM on Bitcoin Talk forum Monday.
Thanks

**Comment by Imaminer** [comment]
Ok Rig2 is setup for you now. Please see my PM on Bitcointalk forum.

**Comment by tutulino** [comment]
We will continue in #351 to join various threads
