### ISSUE TITLE
Rig name not passed to BlazePool

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#337]
My rig names never show up on Blaze. Just the miner name. 
![image](https://user-images.githubusercontent.com/30805282/36728132-b83b17da-1b8d-11e8-8acb-8a2a64bdca59.png)
![blaze2](https://user-images.githubusercontent.com/30805282/36728328-62a1944c-1b8e-11e8-959f-b27a3d3d812a.JPG)

**Comment by 1001rapid** [comment]
I confirm
and I found why
if you look at the address http://api.blazepool.com/wallet/[your_wallet] you can see empty ID
`"miners":[{"version":"ccminer/alexis-1.1_palginmod","password":"c=btc,Id=F3x980Ti3","ID":""`

**Comment by Imaminer** [comment]
Looking at Blazepool.ps1 I see this -
 $Result+=[PSCustomObject]@{
                                            
                                            Pass          = "c=btc,Id=#Workername#"
                                            

I wonder if it should be this -
 $Result+=[PSCustomObject]@{
                                            
                                            Pass          = "c=btc"
                                            ID             ="Id=#Workername#"

**Comment by Steality** [comment]
I think it is the website problem, MM pass the value same with ahashpool yet ahashpool shows the rig name.

**Comment by Steality** [comment]
Sorry nothing wrong with the website, tested and worker name shown if using the order:
 Pass=   "Id=#Workername#,c=btc"

**Comment by tutulino** [comment]
Changed, it will be available next code upload
