### ISSUE TITLE
countdown freezes

### ISSUE THREAD

**Issue by cherso** [tutulino/Megaminer#339]
I was experiencing countdown freezes so I debugged the code and find out that a single click inside the main powershell window will freeze the code, so no countdown updates and no algo switching

I dunno if that is a standard behaviour but for sure someone can stop by mistake the countdown by simply switch between miner window and powershell window

you may want to take a look at that

thank you

**Comment by Steality** [comment]
You should run MM using cmd with quick edit mode disabled

**Comment by tutulino** [comment]
This is how powershell works in windows, you can also disable quick edit mode in window tittle with right button/properties/
