### ISSUE TITLE
latest

### ISSUE THREAD

**Issue by ALLMINER** [tutulino/Megaminer#342]
\Whattomine.ps1: строка 119
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-6.0\pools\Whattomine.ps1: строка 112
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-6.0\Include.ps1: строка 1052
в Get_Pools, C:\Users\аагнрошло\Desktop\Megaminer-6.0\Include.ps1: строка 1045
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-6.0\core.ps1: строка 306
в <ScriptBlock>, <Нет файла>: строка 1
в <ScriptBlock>, C:\Users\аагнрошло\Desktop\Megaminer-6.0\Megaminer.ps1: строка 193
в <ScriptBlock>, <Нет файла>: строка 1
03/01/2018 14:36:16...... DUPLICATED ALGO ETHASH ETHASH ON A-ClayDual A-ClayDual

**Comment by ALLMINER** [comment]
https://github.com/krnlx/ccminer-xevan/releases/download/0.1/ccminer_x86.exe  
need zip

**Comment by ALLMINER** [comment]
find solved

**Comment by 1001rapid** [comment]
Думаешь лог на русском ему поможет? )

**Comment by ALLMINER** [comment]
тут без языка понятно ) проблема в пулах
