### ISSUE TITLE
Remove ZERGPOOL --- Unusable, Always have problems

### ISSUE THREAD

**Issue by reset77** [tutulino/Megaminer#345]
Hi Tutulino

Consider Removing ZergPool from MM

right now stratums are not working... several days with same problem
dont know if other MM users noticed their rigs IDLE for hours loosing money

i followed this pool since launched, this pool had so much potential but instead it has been a pain over and over again... 
its been an extreme waste of time and money

everything cause of bad configured DDoS protection... several weeks and still the same problem
also lots of chainsplits
the pool operator seems very unprofessional
no other pool has this problems...

Does other users experienced this?

thanks!!

**Comment by Imaminer** [comment]
I have some issues but not many. Everyone in a while a miner will get the dreaded stratum disconnect.

**Comment by tutulino** [comment]
I like that pool, but I´m not minning on it due to unstability. Each one can choose use or not.
