### ISSUE TITLE
Constantly downloading ccminer?

### ISSUE THREAD

**Issue by scavern** [tutulino/Megaminer#346]
Megaminer seems to be constantly downloading cc_miner_cuda9 and cc_miner_x86. This happens after every interval change.

I am on version 6. Is this a known issue?

**Comment by tutulino** [comment]
yes, is known, you can download master code where it is fixed.

**Comment by scavern** [comment]
Can same config file be used?

**Comment by tutulino** [comment]
Check changelog, always has that info

2018-03-05 11:55 GMT+01:00 scavern <notifications@github.com>:
