### ISSUE TITLE
Version 6.1 Blazepool

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#349]
Testing it now.
Rig name still not passed to Blaze. Now its the algo...
Check second name. Thats new version. Neo instead of Rig2.

![workers](https://user-images.githubusercontent.com/30805282/36992648-8fdef0fe-2079-11e8-8981-6ef8d2c5ebdb.JPG)

**Comment by tutulino** [comment]
I have undone change in any upload, I have upload new blazepool file with changes again.
