### ISSUE TITLE
Where is eth wallet in config?

### ISSUE THREAD

**Issue by maxbaluev** [tutulino/Megaminer#35]

**Comment by MikeBuzz** [comment]
ETH would not be in the config as this is mainly for yiimp which does not mine ETH, all other pools either use your BTC address or you create a account with them.

**Comment by tutulino** [comment]
You can add all wallets you want to config txt, pattern is @@WALLET_XXX (XXX=currency symbol)

You can mine being paid on ETH on Zpool or HR if you set @@currency=ETH and add a @@WALLET_ETH

**Comment by MikeBuzz** [comment]
Would not work as they state the following

"You can also use any valid wallet address from any of the coins we mine"

**Comment by tutulino** [comment]
@@currency and its asociated wallet is only used on anonymous pools with auto exchange (zpool and HR) for Yiimp always is used wallet of coin you are mining.
MPH, Suprnova an BF use @@username
