### ISSUE TITLE
Version 6.1 Monitor

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#350]
What exactly are we supposed to see?
I get this first - 
![auth](https://user-images.githubusercontent.com/30805282/36992853-313a0060-207a-11e8-9658-9e3b8fff2917.JPG)

Then i get basically a list of configs.
Like this - 

![inkedapi_li](https://user-images.githubusercontent.com/30805282/36993148-095fe090-207b-11e8-8547-4239df047444.jpg)

**Comment by tutulino** [comment]
Fill new config.txt fields, Use start.bat, option 3.

You can only monitorize rigs with this release at least

![image](https://user-images.githubusercontent.com/29943663/36994376-36f30d4e-20b1-11e8-9062-dd7dd89c2912.png)

**Comment by Imaminer** [comment]
Duh....I didn't remove the --
Ok now I have farm monitor on screen of rig but if I access it remotely I get the same config screen.
In other words if I use browser on different pc to 10.0.0233:9999 I do not get farm monitor. I get same pic I posted earlier.

**Comment by tutulino** [comment]
New feature is api for other apps integration and farm monitor screen, not web page.

When you use browser to connect you are getting api result json, same as pools api for example

**Comment by Imaminer** [comment]
Gotcha thanks
