### ISSUE TITLE
Keeps downloading phoenix miner every interval.

### ISSUE THREAD

**Issue by or1g1na1** [tutulino/Megaminer#352]
Just downloaded today's release, every interval it says it's downloading phoenix miner, then cannot download.

<img width="960" alt="error" src="https://user-images.githubusercontent.com/36935195/37058403-66d1a2bc-2158-11e8-9e5d-7d57d9b13579.png">

**Comment by Deeferdawg** [comment]
I'm having the same problem

**Comment by tutulino** [comment]
Fixed
