### ISSUE TITLE
Dual mining pointing to wrong algorithm

### ISSUE THREAD

**Issue by coderasm** [tutulino/Megaminer#36]
The dual miner is being launched with blake algo instead of sia algo.
![dual_miner_bug](https://user-images.githubusercontent.com/446396/29428760-32eeafc0-8343-11e7-8264-91d1e7290d46.PNG)
![wrong_endpoint_dual_miner](https://user-images.githubusercontent.com/446396/29428761-32eefea8-8343-11e7-9415-4586ca721297.PNG)

**Comment by tutulino** [comment]
check some claymore dual file on miners folder, must say

     {"Ethash_Blake2b":" -dcoin sc"},
                {"Ethash_Blake14r":" -dcoin dcr"},
                {"Ethash_Pascal":" -dcoin pasc"},
                {"Ethash_Lbry":" -dcoin lbc"}

**Comment by coderasm** [comment]
The dual120 file had:
`"Algorithms": [
                {"Ethash_Blake2s":" -dcoin sc"},
                {"Ethash_Blake14r":" -dcoin dcr"},
                {"Ethash_Pascal":" -dcoin pasc"},
                {"Ethash_Lbry":" -dcoin lbc"}
              ]
}`

**Comment by tutulino** [comment]
replace blake2s for blake2b
