### ISSUE TITLE
Tried power limits on Nvidia - Asking for permissions & can't run as Admin

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#360]
First time I tried power limit feature on NV rig. 
Had to disable it. Asked over and over and over and over (5 cards) repeatedly for permission on OverdriveN
and actually never set anything and never ran.
Your instructions are to run as Administrator and turn off UAC. Both done. When i ran "start" or my own .bat as admin I get this -

![admin](https://user-images.githubusercontent.com/30805282/37214907-7d319f16-2384-11e8-9ed8-6234c36ac4b4.JPG)

**Comment by Firstishe** [comment]
+1 See this truble too

**Comment by 1001rapid** [comment]
Try to use admin account, not "Run aas administrator"

**Comment by tutulino** [comment]
when you launch a batch file as admin, actual folder is changed to admin´s home, and core.ps1 is not found there.

You can run in normal mode if your user has admin rights. If you want run as admin with right click you must add this to return to MM folder at batch file (at start).  


cd %~dp0


I have added this to batch examples.
