### ISSUE TITLE
Trying to download Phoenix...which I already have

### ISSUE THREAD

**Issue by Nickduino** [tutulino/Megaminer#361]
Every time I start MegaMiner, it tries to download Phoenix (or, at least, displays the text message) but It's already there in the /Bin/:

![There](https://image.ibb.co/gBBEv7/Phoenix.png)

**Comment by Steality** [comment]
link is fine, the path is the problem
"Path" : ".\\Bin\\NA-Phoenix\\PhoenixMiner_2.5d\\Phoenixminer.exe",

**Comment by Nickduino** [comment]
Ok, so I changed it to _"Path" : ".\\Bin\\NA-Phoenix\\PhoenixMiner_2.7c\\Phoenixminer.exe",_ in _\Miners\N-Phoenix.json_

**Comment by tutulino** [comment]
Fixed
