### ISSUE TITLE
DELAYCLOSEMINERS with more than one gpu group

### ISSUE THREAD

**Issue by baktery** [tutulino/Megaminer#363]
It seems like with more than 1 gpu group some miner instances are never stopped.

The value of DELAYCLOSEMINERS was set at 10 seconds. I'll try to reproduce the issue to get more info.

**Comment by or1g1na1** [comment]
I do not use gpu groups but occasionally old miner doesn't close on switch, very rare.
Sometimes causes shutdown and sometimes both mine half speed.

**Comment by baktery** [comment]
So or1g1na1, are you using DELAYCLOSEMINERS?

I thought that it was related to using more than 1 gpu group but maybe it is an independent issue not related with more than 1 gpu group.

**Comment by or1g1na1** [comment]
Yes, I use delaycloseminers, I love it.  May just be a freak thing that happens sometimes.

**Comment by tutulino** [comment]
I have added more retries to killing process and log to see if problem is that process cant be killed or if problem is process id is lost for execution.
