### ISSUE TITLE
6.1 issues

### ISSUE THREAD

**Issue by baktery** [tutulino/Megaminer#366]
New ApiListener is great, very useful!

I know that 6.1 is WIP, but just to help if this info is useful, two issues I found:

- Nicehash.ps1, from the wallet query I had to comment the following line, otherwise got an error

`# $Request = $Request |Select-Object -ExpandProperty result  |Select-Object -ExpandProperty stats 
`

- core.ps1. If some miner fails, then the line 1066 is executed and an invalid argument error appears:

`                            writelog ([string]$ActiveMiners[$_.IdF].Process+','+[string]$ActiveMiners[$_.IdF].Process.HasExited+','+$GpuActivityAverage+','+$TimeSinceStartInterval) $logfile $false
`

**Comment by tutulino** [comment]
- Nicehash.ps1 --> I´m testing and no problem, get the wallet, and json returned by hicehash api sends all data in stats property.

- core.ps1 --> Deleted, was testing line
