### ISSUE TITLE
Is there a way to turn off an algo/miner for a specific GPU group?

### ISSUE THREAD

**Issue by VukaKun** [tutulino/Megaminer#368]
I'm mining with a 1080Ti and a 750Ti. Not surprisingly, 1080Ti can handle everything without any problems, but the 750Ti doesn't have enough GDDR for a couple of algo/miner combinations. Is there a way to disable them **only** for 750Ti?

**Comment by tutulino** [comment]
No, there is no way if they are same brand.

**Comment by VukaKun** [comment]
Alrighty then. I found a workaround, though, if anyone ever faces a similar issue. You can simply run two instances of Megaminer from different locations and then point both of them to the same resource folders to avoid unnecessary duplication.
