### ISSUE TITLE
Here is how to fix Blazepool Rig name issue

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#373]
It was very simple. Changle blazepool.ps1 Id = to
ID=
Yep just capitalize both letters and then you get this - Not sure why it still says neo with the rig name but hey who cares right!
![rig2](https://user-images.githubusercontent.com/30805282/37311629-621a88a4-261e-11e8-86d9-a9c8ab69fbfa.JPG)

**Comment by tutulino** [comment]
Changes uploaded 
Thanks
