### ISSUE TITLE
[SUGGESTION] Variable benchmarking duration

### ISSUE THREAD

**Issue by Nickduino** [tutulino/Megaminer#374]
> *Added Palgin Neoscrypt miner (via wrapper) to additional miners folders - **THIS MINER NEEDS A MINIMUM OF 600s-900s** BENCHMARK TIME TO WORK, IF YOU ONLY HAVE ONE NVIDIA GPU GROUP USE API VERSION

Would it be possible to change the benchmarking duration with the miner or algo? Set it to 4-5 min normally but 10-15 on some others?

Or better, modulate it automatically: stop benchmarking once value has stopped raising (or decreasing) and has been stable for some time (two minutes?).

**Comment by tutulino** [comment]
I recommend use N-PalginNeoJust, it has no problem with shoter intervals

**Comment by Nickduino** [comment]
I know, but you need only one nvidia group.

But rather than benchmarking everything for 600 sec, why not benchmark for 200 sec of **stable** hashrate?

**Comment by Nickduino** [comment]
Or stop the benchmark if the first results are really shitty?
Or benchmark twelve algos at a time (if you have twelve identical cards)?

**Comment by tutulino** [comment]
N-PalginNeoJust, works with more than one nvidia group.

Default benchmark time is 300 (600 is recommend only if powerlimit feature is used), I have seen included config.txt has 600 at default, changed to 300.

- Identical cards can have different hashrate, (brand, overclock, port) etc. it´s too risky benchmark one algo in each one.

- Some miners or algos have shitty first results but after that they get good hashrate, also too risky I think

- Stable hashrate seems more acurated aproximation, I will test, if I get good results it will be included at future releases

**Comment by Nickduino** [comment]
Good plan
