### ISSUE TITLE
Nicehash pool fee

### ISSUE THREAD

**Issue by baktery** [tutulino/Megaminer#375]
Nicehash is not 4% fee for external wallets, it seems like it was an old scheme.

Currently external wallets are 5% for balance less than 0.1

Reference: https://www.nicehash.com/help/fees

**Comment by tutulino** [comment]
That 4% is average between 5% for balances less than 0.1 and 3% for greater than or equal to 0.1.

If you know that your average pay is greater or lesser than 0.1 you can change that fee editing /pool/nicehash.ps1 file
