### ISSUE TITLE
Automatic Start

### ISSUE THREAD

**Issue by Deeferdawg** [tutulino/Megaminer#377]
My computer, which is running Windows 10, keeps on shutting down on me. I can start MegaMiner automatically through startup but can I write somewhere in the config file to choose my mining options also? Would like to mine auto and ahashpool and zpool.

Thanks!

**Comment by eMTee72** [comment]
Did you check the provided examples? You can find them in the MegaMiner folder.
Look for a file called: "AutoStart Example - Two pools on Auto.bat"
