### ISSUE TITLE
New miner for you

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#379]
Your app cannot get the MEGA files so you will need to grab it and RAR it like you did for PHI. I have tested this version on x16r and x17 seems to be working ok.

{
"Path" : ".\\Bin\\NVIDIA-CcminerX16R-enemy\\ccminer.exe",
"ExtractionPath" : ".\\Bin\\NVIDIA-CcminerX16R-enemy\\",
"Uri" : "https://mega.nz/#!DHJjiRTT!Wf-dFlcrNkDpJLuSftoT6-DU-txZ-TWZrC7_4Njlk2Q",
"Types" : ["NVIDIA"],
"Arguments" : "-o #PROTOCOL#://#SERVER#:#PORT# -u #LOGIN# -p #PASSWORD# -R 5 -N 1 -b #APIPORT# -d #DEVICES# #ALGORITHMPARAMETERS# ",
"API" : "Ccminer",
"Dualmining":false,
"APIPort" : 4068,
"PrelaunchCommand":"",
"Algorithms": [
                {"x16r":"-a x16r  "},
                {"x17":"-a x17  "}
              ]
}

**Comment by tutulino** [comment]
There is an X16r miner included in latest release.

For anti scam security I only add miners that I can get source link page. Can you post source for this one?

**Comment by podlbo** [comment]
Sources.
http://www.helenabitcoinmining.com/2018/03/04/ccminer-enemy-1-03-fork-for-raven-rvn-mining-now-available/

and here-
http://cryptomining-blog.com/9507-ccminer-enemy-1-03-fork-for-raven-rvn-mining-now-available/

And blog_:
https://bitcointalk.org/index.php?topic=2752467.1940

**Comment by tutulino** [comment]
I have uploaded new tpruvot code, can you check which is faster?

**Comment by podlbo** [comment]
enemy is FASTER ---

![slika](https://user-images.githubusercontent.com/33230718/38268720-1fe991d8-377f-11e8-99bb-f17a09c65943.png)

![slika](https://user-images.githubusercontent.com/33230718/38268749-2b6cf1e4-377f-11e8-8b6b-9b38875fd485.png)

**Comment by tutulino** [comment]
Added in master branch code replacing ccminerX16r
