### ISSUE TITLE
[SUGGESTION] Luck based auto switching

### ISSUE THREAD

**Issue by rinkal26783** [tutulino/Megaminer#387]
hello tutulino,
I like to see auto switching based on coin luck %
For Example I want to mine some good quality coins on bsod.pw 
Bulwark, Luxcoin, GoByte, Denarius, Bitcore, Ravencoin
But mining is based on luck. Some time we get 10 blocks in hour and next hour there is no block. But, we still submitting shares unless new block is found. which makes wastage of mining shares.
So, You can make new miner which will select the most lucky coin by lowest luck %. And when luck gets hard it will look for another coin. 
User can set luck % when they want to switch new coin.

**Comment by tutulino** [comment]
It is no possible, pools haven´t available luck atribute in API
