### ISSUE TITLE
Too much benchmarking...

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#390]
Any reason why benchmarks are done against multiple Pools or for multiple Coins?
Shouldn't the Miner + Algo be sufficient?

Examples of CPU miner:
![image](https://user-images.githubusercontent.com/32677058/38275098-0e274b90-3791-11e8-94c3-f1bbafbf6f59.png)

Example of GPU (AMD) miner:
![image](https://user-images.githubusercontent.com/32677058/38275136-2fd74862-3791-11e8-830e-426a180f3834.png)
at next interval:
![image](https://user-images.githubusercontent.com/32677058/38275359-eb199512-3791-11e8-9fa6-2232c6037022.png)

**Comment by yuzi-co** [comment]
They are done only once for each algo-miner combination. Don't let the display fool you

**Comment by tutulino** [comment]
Display is indicating that profit for that coin cant be shown until benchmark for that algo is finished, It is not indicating that a benchmark will be done for each coin.
