### ISSUE TITLE
x16r error

### ISSUE THREAD

**Issue by dethknite** [tutulino/Megaminer#394]
DUPLICATED MINER X16R X16R ON N-CcminerX16r N-CcminerX16r
![x16r](https://user-images.githubusercontent.com/965431/39075529-c77286be-44bb-11e8-8773-eb15e095badc.png)

**Comment by dethknite** [comment]
I was able to temporarily fix this issue by moving the N-CcminerX16r.json into the Archived Miners folder...

**Comment by Kelarik** [comment]
Better temporary fix I've found is to simply edit line 13 of N-CcminerX16r.json so that it reads "x16s":"-a x16s", since that seems that it's just a typo causing a double-algo detection

**Comment by dethknite** [comment]
Submitted a pull request for fix.
