### ISSUE TITLE
AMD Testing

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#4]
Just started. Will list issues as they come up. Testing ONLY to MPH right now.

1) Although I changed type in config to AMD program is downloading unnecessary Nvidia miners.
2) After running start.bat and entering my choices your program should write a new start with those choices.
3) Config file when opened with NotePad is a mess. Unreadable. I had to go thru and find each "--" and create a line. Fix readability of file please.
4) The first bench marking started before all the miners were downloaded thus making the first miner hang (in my case it was SGminer). Bench marking should wait until all downloads have finished. I had to stop program and restart it.
5) Unclear on how to add or remove algo's. No idea...
6) 6 mins in now and so far no mining. SGminer won't start. They DO run on MultiPoolMiner btw...
**Note ok I think I see why SGminer isnt working. Heres your batch going to Asia and not US. 

   Bin\AMD-NiceHash\sgminer.exe -o                                             stratum+tcp://asia.hub.miningpoolhub.com:20527 -u xxx.Rig3 -p x
                                               --gpu-platform 0 -k skeincoin --gpu-threads 2 --worksize 256
                                               --intensity d
Just rechecked my config file and confirmed I have set US. Tested again and this time got Europe.

Looking forward to the testing and hope it works out.

**Comment by tutulino** [comment]
Thank for testing.

1. Fixed on 2.0.2 next release 
2. Fixed on 2.0.2 next release 
3 I see ok, must be characters set (what is your language?)
4. First start for AMD must benchmark claymore (included) while download other miners.
5. You can edit algorithms.txt or use core parameter  -Algorithm Algo1,Algo2,Algo3

**Comment by Imaminer** [comment]
2) I did edit config.txt first. All I am saying is that for convenience your start.bat should remember the choices we pick and create a new batch file so we don't have to create our own. 
3) USA. its not that it was in a unreadable language, the config file does not have any formatting. All lines are being displayed as one huge giant continuous line.

Fix number 6 and I will test again

**Comment by tutulino** [comment]
Menus are designed to allow fast launch, not for always choose same options, for this at this moment you mus create a batch file (see examples.bat), I will add to next features auto creation of batchs.

It´s basic....but in notepad exists an option (Menu Format /Line Adjust), have you try this?

MiningPoolHub is doing some strange things (see closed issue), can read on pools thread too, Stratum errors, no pools on api return, I think is no program problem, I have tested ten times now with US location and always return US pools.

**Comment by Imaminer** [comment]
And I have tried twice and gotten Asia and Europe.  Good luck resolving it. I have had zero issues with MPH and MultiPoolMiner . You have some cool features. Hope you get it worked out.

**Comment by tutulino** [comment]
One time I get same behaviour, I found it....XD

Solved on 2.0.3 release. You only need download and replace core.ps1 file

**Comment by Imaminer** [comment]
Awesome. Fired it up again and immediately got US server.   I can already tell you sgminer is using wrong algo.
First bench mark is skeincoin.
This is sgminer -
[13:36:37] Started sgminer 5.6.1-nicehash-51
[13:36:37] * using Jansson 2.7
[13:36:39] Probing for an alive pool
[13:36:41] us-east.hub.miningpoolhub.com difficulty changed to 8
[13:36:41] Startup GPU initialization... Using settings from pool us-east.hub.miningpoolhub.com.
[13:36:41] Startup Pool No = 0
[13:36:41] us-east.hub.miningpoolhub.com difficulty changed to 1.400
[13:36:42] Initialising kernel ckolivas.cl with nfactor 10, n 1024
[13:36:42] Initialising kernel ckolivas.cl with nfactor 10, n 1024
[13:36:42] Building binary ckolivasHawaiigw256l4lg2tc32320nf10.bin
[13:36:56] Initialising kernel ckolivas.cl with nfactor 10, n 1024
[13:36:56] Initialising kernel ckolivas.cl with nfactor 10, n 1024
[13:36:56] Initialising kernel ckolivas.cl with nfactor 10, n 1024
[13:36:56] Initialising kernel ckolivas.cl with nfactor 10, n 1024

**Comment by tutulino** [comment]
Sorry, I never use before Sgminer (All my rig are NVIDIA), where do you see
it is using wrong algo?.

All configuration for sgminer is on sgminer* files on miners folder, there
you can see with miner and parameters use MM for each algo

2017-08-09 19:41 GMT+02:00 Imaminer <notifications@github.com>:

**Comment by Imaminer** [comment]
The kernel for skeincoin is not ckolivas. Whenever something is passed to sgminer it doesnt understand it defaults to ckolivas and of course fails.

**Comment by Imaminer** [comment]
I suggest buying or borrowing a RX AMD card for testing. I'm sure if you had the card you could resolve all issues quickly

**Comment by tutulino** [comment]
I´m doing this as a hobby, not for profit, also in Spain find a RX is
imposible mission.

Thanks for your help, again.





2017-08-09 21:22 GMT+02:00 Imaminer <notifications@github.com>:

**Comment by Imaminer** [comment]
Possible wrong port. Your script is pointing skeincoin at 20527
Can't check right now but that sounds wrong.

**Comment by Imaminer** [comment]
Testing continues. Trying to fix skein. Making some progress. I will let you know if I solve it.

**Comment by Imaminer** [comment]
Ok I solved the mystery. The folder you have provided for AMD_Skein does not contain the skeincoin algo.
This version written by MPH does have it - 
https://github.com/miningpoolhub/sgminer/releases

So I changed to this and tested and tested an and tested. I can connect to the port and even once mining started for 2 seconds but that's about it. 

For me if I decide to use your program I will have to remove all skein which is a shame because DBG is a good coin to mine. (But on the other hand AMD is not the most profitable card for Skein).

So....removing skein and continuing testing

**Comment by Imaminer** [comment]
Although I edited the algorithms file and removed both skein's, when starting program sgminer is trying to bench mark skein. The reason is it is hard coded in sgminer.json
This file should pull code from the algoriths file instead maybe?
For now I removed skein from sgminer.json

{"Myr-gr":"-k myriadcoin-groestl --gpu-threads 2 --worksize 64 --intensity d"},
                {"Groestl":"-k groestlcoin --gpu-threads 2 --worksize 128 --intensity d"},
                {"blake":"-k blake"},
                {"vanilla":"-k vanilla --intensity d"},
                {"decred":"-k decred"},
                {"Keccak":"-k maxcoin"},
                {"lbry":"-k lbry"},
                {"neoscrypt":"-k neoscrypt --gpu-threads 1 --worksize 64 --intensity 11 --thread-concurrency 64"},
                {"pascal":"-k pascal"},
                {"Qubit":"-k qubitcoin --gpu-threads 2 --worksize 128 --intensity d"},
                {"Scrypt":"-k zuikkis"},
                {"sia":"-k sia"},
                {"Skein":"-k skeincoin --gpu-threads 2 --worksize 256 --intensity d"},
                {"darkcoin-mod":"-k darkcoin-mod --gpu-threads 2 --worksize 128 --intensity d"},
                {"yescrypt":"-k yescrypt --worksize 4 --rawintensity 256"},
                {"lyra2v2":"-k lyra2rev2 --gpu-threads 2 --worksize 128 --intensity d"}

**Comment by tutulino** [comment]
what sgminer did you use before?

I will remove skein for next release until we have a solution.

2017-08-10 18:14 GMT+02:00 Imaminer <notifications@github.com>:

**Comment by Imaminer** [comment]
I actually tried every version I could find. Only the very very old one from MPH even tried to work...but it didn't.

**Comment by Imaminer** [comment]
Working on AMD / MPH - Will edit as they finish
Sgminer - yescrypt (13 minute benchmark)
Sgminer - lyra2z (18 minutes so far)

**Comment by Imaminer** [comment]
Error with sgminer and  lyra2v2


sgminer 5.6.1-nicehash-51 - Started: [2017-08-11 07:17:13] - [0 days 00:05:14]
--------------------------------------------------------------------------------
(5s):29.89M (avg):25.10Mh/s | A:0  R:0  HW:260  WU:0.000/m
ST: 1  SS: 0  NB: 3  LW: 569  GF: 0  RF: 0
Connected to mine.zpool.ca (stratum) diff 8.000 as user xxxxxxxxxxxxxxxxx
Block: f0b0be2b...  Diff:9.53K  Started: [07:19:34]  Best share: 0
--------------------------------------------------------------------------------
[P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit
GPU 0:  76.0C 2609RPM | 9.633M/8.192Mh/s | R:  0.0% HW:  0 WU:0.000/m I:16
GPU 1:  80.0C 1386RPM | 9.904M/8.670Mh/s | R:  0.0% HW:256 WU:0.000/m I:16
GPU 2:  70.0C 1125RPM | 10.08M/8.605Mh/s | R:  0.0% HW:  4 WU:0.000/m I:16
--------------------------------------------------------------------------------
[07:16:49] Started sgminer 5.6.1-nicehash-51
[07:16:49] * using Jansson 2.7
[07:16:50] Probing for an alive pool
[07:16:51] Startup GPU initialization... Using settings from pool mine.zpool.ca.
[07:16:51] Startup Pool No = 0
[07:16:51] mine.zpool.ca difficulty changed to 8
[07:16:52] Building binary lyra2rev2Ellesmeregw128l4lgtc128.bin
[07:17:01] Initialising kernel lyra2rev2.cl with nfactor 10, n 1024
[07:17:02] Initialising kernel lyra2rev2.cl with nfactor 10, n 1024
[07:17:02] Building binary lyra2rev2Hawaiigw128l4lgtc128.bin
[07:17:12] Initialising kernel lyra2rev2.cl with nfactor 10, n 1024
[07:17:12] Initialising kernel lyra2rev2.cl with nfactor 10, n 1024
[07:17:13] Initialising kernel lyra2rev2.cl with nfactor 10, n 1024
[07:17:13] Initialising kernel lyra2rev2.cl with nfactor 10, n 1024
[07:17:35] GPU2: invalid nonce count - HW error
[07:19:02] GPU1: invalid nonce count - HW error
[07:21:49] GPU2: invalid nonce count - HW error

**Comment by Imaminer** [comment]
During testing I noticed speeds where wrong and not being displayed.
[https://s27.postimg.org/tnhr69rlv/speed.jpg](url)

**Comment by Imaminer** [comment]
Clsoing this as we are now several versions ahead. Retesting on new version.
