### ISSUE TITLE
Alexis78 miners

### ISSUE THREAD

**Issue by Chapster85** [tutulino/Megaminer#40]
I know you are just including it with your program, but I wanted to report that Alexis78's miners cause my computer to crash with a blue screen of death.
It uses Windows 10, x64, 8 x GTX 1070 video cards.
This happens even without any overclocking.

Nothing else causes this computer to crash. It could be on mining for a week and no issue whatsoever. As soon as one of the Alexis78 miners is run, the miner crashes with some yellow messages and right away the whole computer.

**Comment by tutulino** [comment]
I know some people have problem with alexis, but others not and it is fastest on some algos. You can delete file on miner folder and reasignate algos to others miners.
