### ISSUE TITLE
Neoscrypt pools on uniminig not work

### ISSUE THREAD

**Issue by 23fero3** [tutulino/Megaminer#401]
when you are connected to unimining pool on neoscrypt algo not working.problem is show you connection on port 4233 but uniminig using different ports.when you mining automatic mode is not work.you need to define pool with different port.

**Comment by tutulino** [comment]
Unimining API is returning wrong data, I have hardcoded ports until unimining admin solve this one.

**Comment by 23fero3** [comment]
THX
