### ISSUE TITLE
How to filter coins/algo

### ISSUE THREAD

**Issue by Paul-Trasca** [tutulino/Megaminer#405]
Hi. Quick question. I mine on auto/blazepool
How can i filter coins that i mine?
For example, on x17 - only verge; on x16r only ravencoin... etc
Thx

**Comment by Rimplestilhskin** [comment]
Start megaminer, select option 2, select blazepool, select coin if and when the coin shows, if not restart megaminer and do the same and usually 2nd time it shows up.

You can also modify the start script to only use a coin or a Algo or a pool or all 3 and run that.
I have had few consistent experiences with Blazepool so it is the 1st action after downloading MegaMIner to delete BlazePool in pools folder.

Unimining is stable, zergpool is hit or miss for paying out or using bitcoin c=BTC ... type options and it ends up for a bitcoin address as LTC on zergpool, zpool is extremely unstable and never pays with the same zergpool type algo errors.

**Comment by Rimplestilhskin** [comment]
See the .bat files with examples.

AutoStart Example - Auto with coin filter.bat

AutoStart Example - one coin manual.bat

AutoStart Example - Two pools on Auto.bat
