### ISSUE TITLE
Recently bought a AMD 2400g, How to disable it?

### ISSUE THREAD

**Issue by Ruber249** [tutulino/Megaminer#407]
I recently got a AMD2400g and want to disable it,    

I use Nvidias in my Rig but its always trying to benchmark the GPU on the CPU and I need to disable it.

I tried to play around with the GPUGROUPS and can't figure it out.

When I start the miner I see my Nvidia and amd gpu.    What line should I use to disable that AMD?

**Comment by tutulino** [comment]
you must configure GPUGROUPS, you must set one NVIDIA type group only  and set all nvidia id. For example if you have 3 nvidia cards.


if you want to use automatic powerlimit feature
@@GPUGROUPS=[{"GroupName" : "NvidiaCards","Type":"NVIDIA","Gpus":"0,1,2","PowerLimits":"100,90,80,70,60"}]


if you dont want to use automatic powerlimit feature

@@GPUGROUPS=[{"GroupName" : "NvidiaCards","Type":"NVIDIA","Gpus":"0,1,2","PowerLimits":"0"}]
