### ISSUE TITLE
Unimining.net port errors

### ISSUE THREAD

**Issue by Rimplestilhskin** [tutulino/Megaminer#409]
Standard port used is 3636 vs new port layout for each crypto , It seems 3636 has been disabled ?
With or without VPN or alternative DNS ... etc ... / 3x other internet ISP I get the same results below.

3637 & 3638 for x16r
Similar changes for other algo's

 Starting on stratum+tcp://pool.unimining.net:3636
[INFO   ] 18/05/11 09:50:29 GPU monitoring enabled (NVAPI).
[INFO   ] 18/05/11 09:50:29 Mining 'x16r' with 1 thread.
[X16    ] 18/05/11 09:50:29 Hashorder algorithm legend: Slow Medium Fast
[ERROR  ] 18/05/11 09:50:50 Stratum connection failed: Failed to connect to pool.unimining.net port 3636: Timed out
[ERROR  ] 18/05/11 09:50:50 ...retry after 10 seconds

**Comment by rinkal26783** [comment]
I also have error with unimining port. It looks like they have changed their ports and stratum host URL.

**Comment by tutulino** [comment]
Problem is they have changed ports but api is returning old 3636 port yet.

I have hardcoded ports until api returns right port, I will upload today a new pool file
