### ISSUE TITLE
Running a program before the actual miner

### ISSUE THREAD

**Issue by Chapster85** [tutulino/Megaminer#42]
Hello,

Is it possible to run a program before the actual miner?
Some algorithms have different needs. Some of them are favored by memory overclocking while others prefer core overclocking.
I would like to be able to send a command to MSI Afterburner to change the profile according to the program or algorithm being run.

**Comment by maxbaluev** [comment]
And we need knowledge exchange about that inside miner.

**Comment by tutulino** [comment]
Not posible directly,  but you could edit miner.json for each miner and replace path to call a batch file that call Afterburner and after that call miner. I think it works.
