### ISSUE TITLE
Ahashpool changed units for some algorithms

### ISSUE THREAD

**Issue by Kelarik** [tutulino/Megaminer#422]
From their site: "changed the units of keccak, keccakc, nist5, lbry, skein to mBTC/Gh/day"
Was wondering why my rig was suddenly reporting over €1000/day per 1080Ti

**Comment by Mpx1** [comment]
You can update AHASHPOOL.ps1 file - between lines

$Divisor = (Get_Algo_Divisor $Aha_Algorithm) / 1000

$Result+=[PSCustomObject]@{

                   
insert following code:

                                switch ($Aha_Algorithm){
                                    "keccak"{$Divisor *= 1000}
                                    "keccakc"{$Divisor *= 1000}
                                    "nist5"{$Divisor *= 1000}
                                    "lbry"{$Divisor *= 1000}
                                    "skein"{$Divisor *= 1000}
                                    }

**Comment by tutulino** [comment]
Test master branch code
