### ISSUE TITLE
Miner API

### ISSUE THREAD

**Issue by maxbaluev** [tutulino/Megaminer#44]
I need to get stats and current status of miner programatically. What you think about that? Are you need some help?

**Comment by tutulino** [comment]
I´have planned add a rest Api, I can add a File on log folder with a json structure that always content actual info.

**Comment by maxbaluev** [comment]
any updates? deadline?

**Comment by tutulino** [comment]
At this moment main objective is fix bugs and some little features, I cant say a deadline.

**Comment by tutulino** [comment]
Included in latest master code (see changelog)
