### ISSUE TITLE
4.0 error

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#45]
You have been busy! Nice work.
NH worker names is fixed!

Hey see this screenshot please. Lots red errors during benchmarking.  Timer not displaying.

https://s2.postimg.org/vvp81e8q1/4.1_error.jpg

**Comment by Imaminer** [comment]
This error is not allowing benchmarking to work. Been on the first one for 10 mins now.
Switching back to version 3 for now...

**Comment by tutulino** [comment]
What pool are you running?

**Comment by Imaminer** [comment]
NiceHash
Auto

**Comment by tutulino** [comment]
Have you made clean install?, dont copy stats, bin or any folder.

I just try clean install and set type to amd and no error.

**Comment by Imaminer** [comment]
Yes clean. I copied nothing.
All I did was edit sgminer some to take out some algos that I dont want on the AMD rigs.
Same as I did for Version 3.

**Comment by Imaminer** [comment]
[2017-08-21_06-56-33.txt](https://github.com/tutulino/Megaminer/files/1239640/2017-08-21_06-56-33.txt)

**Comment by tutulino** [comment]
It seems if no variable @@INTERVAL found on config.txt. 

Try one thing, donwload and use config.txt without editing and see if error.

Some people have problem if edit config.txt with notepad.

**Comment by Imaminer** [comment]
Solved. I had moved old config file over and forgot. 
Thanks
