### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Chapster85** [tutulino/Megaminer#46]
Hello,

It seems there is a memory leak somewhere. I left your program running for about 8 hours and when I came back, Windows was complaining about low memory (89% of memory was used).
The culprit ended up being your program (through Powershell) with about 6GB of RAM.

I restarted it and it went back to less than 200MB. It has been running for a few hours and it is once again approaching 1GB and increasing every few minutes. 

Any ideas?

**Comment by Chapster85** [comment]
Forgot to mention that I'm using version 4.0

**Comment by MikeBuzz** [comment]
i am seeing the same increase in memory usage

**Comment by tutulino** [comment]
what pools and mode are you running?, after 48h on my rig memory occuped is 70Mb only.

**Comment by Chapster85** [comment]
I'm using automatic mode.
Yesterday I was using 99 (all pools).
Last night I left it running with the following pools: HashRefinery, NiceHash, Zpool, MPH.
After running for 8 hours, memory usage is about 3GB and increasing.

**Comment by tutulino** [comment]
I will test this nigth with my rig, I´m only running one pool.

4.0 has a command added to force clean memory, but something is not working well, powershell memory utilization is automatic, could be any miner?

**Comment by Chapster85** [comment]
Hello,
The memory is being hogged by Powershell. I just had to restart your application because it was using so much memory that the miners couldn't even start.

**Comment by Chapster85** [comment]
After running for about 4 hours, memory usage is at 1241.6MB and rapidly increasing.

**Comment by alexrogers** [comment]
same issue here, memory usage of 8GB+ after 2 days. Running with
```
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\core.ps1 -MiningMode Automatic24h -PoolsName Mining_Pool_Hub,Zpool
```

**Comment by MikeBuzz** [comment]
![image](https://user-images.githubusercontent.com/941624/29657246-f3bf51d0-88ae-11e7-940d-b00806e67652.png)

after 1 day for running

**Comment by tutulino** [comment]
I´m getting same behaviour when all pools running, I'm trying to find where is problem but Powershell is a hell for that.

**Comment by Chapster85** [comment]
Any luck regarding this?
I had to stop using Megaminer because of this. I had to babysit it every 12 hours or it would consume enough RAM to make the system unstable or unable to launch some miners.

**Comment by tutulino** [comment]
I´m working on it, but powershell dont have any clue of where is the leak, its a try/error work.

Last test shows me (can be an illusion) than only happens when profit screen is selected, but I´m running a release with a lot of changes to avoid memory leaks, and can have different behaivour.

**Comment by Chapster85** [comment]
Thanks for your reply.

Would this help?
https://unhandled.wordpress.com/2016/08/22/troubleshooting-powershell-memory-leaks-with-visual-studio/

**Comment by tutulino** [comment]
That´s the first I do, but nothing useful inside, Object has memory assigned is something called ConcurrentDictionary but this object is not used directly on sourcecode.

I

**Comment by tutulino** [comment]
I think 4.1 resolves bug, please try it.

**Comment by tutulino** [comment]
I discover 4.1 has bug yet if you let profit screen selected.

**Comment by tutulino** [comment]
solved
