### ISSUE TITLE
Being temporarily banned by Yiimp

### ISSUE THREAD

**Issue by Chapster85** [tutulino/Megaminer#47]
Hello,

Whenever your program is running, my IP gets banned by Yiimp (yiimp.ccminer.org)
Is it perhaps sending too many or too frequent requests to Yiimp?

**Comment by Chapster85** [comment]
I applied a local fix:

1) Added an user agent to the request to Yiimp and added the -URI switch in front of the URL

2) Stored the returned value to an intermediary variable and then json converted it and stored into $Yiimp_Request.
No idea why this one is required but for some reason, the way you had it wasn't properly parsing the json string.

**Comment by tutulino** [comment]
Yiimp Api is very unstable, I think no ban.
Test if with your fix never get error again, if afirmative send me source code.

Only one call to yiimp api each interval (default 10 minutes)

**Comment by Chapster85** [comment]
With the modifications I mentioned, I haven't been banned.
Before them, I would be instantly banned after running your program and would have to close it and wait up to 1 hour for the ban to go away.

**Comment by tutulino** [comment]
send me sourcecode and I will test it.

**Comment by Chapster85** [comment]
Hello,

This is what I am using, starting from line 61 of YIIMP.ps1.
Keep in mind that I have never programmed anything in PS. I was just testing the lines directly on powershell until it seemed to do what you intended:

```
                        try {
							 WRITE-HOST "Trying to read Yiimp API. Attempt: $retries"
                             # $Yiimp_Request = Invoke-WebRequest -URI "http://yiimp.ccminer.org/api/currencies" -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36" -UseBasicParsing -timeout 5 | ConvertFrom-Json 
                             #$Zpool_Request=get-content "..\zpool_request.json" | ConvertFrom-Json
							 $Yiimp_Request1 = Invoke-WebRequest -URI "http://yiimp.ccminer.org/api/currencies" -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36" -UseBasicParsing -timeout 5
							 $Yiimp_Request = Write-Output "$Yiimp_Request1" | ConvertFrom-Json
                        }
```

**Comment by tutulino** [comment]
I think reasignation of response has no effect, but useragent indentification can be the real difference. I´m testing

**Comment by tutulino** [comment]
After a minutes I have same error, api not responding. I let it in sourcecode, it can not make damage.

**Comment by tutulino** [comment]
Next release Yiimp will lose his api integration due to this one.
