### ISSUE TITLE
X11 megaminer and nemosminer

### ISSUE THREAD

**Issue by danik-guitar** [tutulino/Megaminer#5]
profit X11 megaminer and nemosminer are very diffrent ! 
it is very strange.
megaminer 0.011 BTC\day    -     nemos 0.00021  BTC\day

![qip shot - screen 2017 08 10 13-41-13](https://user-images.githubusercontent.com/30734827/29167068-a83c6fa0-7dd1-11e7-9556-ed407e0f205b.jpg)
![qip shot - screen 2017 08 10 13-40-25](https://user-images.githubusercontent.com/30734827/29167069-a841e0e8-7dd1-11e7-91ab-097a3a68c8b8.jpg)
![qip shot - screen 2017 08 10 13-58-30](https://user-images.githubusercontent.com/30734827/29167685-110367bc-7dd4-11e7-9780-b6b3d548f02d.jpg)

**Comment by tutulino** [comment]
Nemosminer makes this api call --> http://www.zpool.ca/api/status
Megaminer makes this api call --> http://www.zpool.ca/api/currencies

This Allow megaminer knows what coin is mining (see column pool)

I see bad data are coming from api at level currencies, there is a coin called Hiro reporting 50000 times more than X11 algo on status api.

I am going to contact crakfoo (zpool admin), while I wil make a release
