### ISSUE TITLE
Still getting errors on screen

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#52]
Exception setting "cursorposition": "Cannot process the operation because
the supplied coordinate is not valid. Specify a coordinate within the
buffer area of 77,9001.
Parameter name: value.X
Actual value was 95."
At C:\mega4\Include.ps1:504 char:9
+         $host.ui.rawui.cursorposition=$position
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationExcep
   tion
    + FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by tutulino** [comment]
What is your screen resolution?

**Comment by Imaminer** [comment]
I am closing this. I have determined the error is caused by a stupid tiny screen from TeamViewer.
All other rigs are fine.
