### ISSUE TITLE
Megaminer how to use guide

### ISSUE THREAD

**Issue by imrecsoka** [tutulino/Megaminer#53]
Hi, i dont understand how to actually use this?
I was excited to see this but i dont have an understanding what to do?
Source code? where is the compiled stuff?

**Comment by tutulino** [comment]
---- INSTRUCTIONS ----------------------------------------------

Download latest Release from github

Edit CONFIG.TXT file before mining

Firt time, software will be donwloaded from miners github repositories.

Exec start.bat for manual selection or edit AutoStartExample.bat for automatic boot without user prompt
