### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#54]
Testing 4.1 now on AMD / MPH
So far the only hiccup was SGminer failing to start on Neoscrypt. I deleted that line and everything else seems fine so far.

**Comment by imrecsoka** [comment]
mine to , i have AMD , and neoscrypt hangs, also prospector runs but it hangs mid way.... i can hear my hard drive going mad but i cant get task manager , so something is weird with that miner.

**Comment by tutulino** [comment]
I have deleted neoscrypt from sgminer in next release.
