### ISSUE TITLE
Missing commands in batch

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#55]
For AMD rigs these commands MUST be in the batch file

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

**Comment by tutulino** [comment]
added next release
