### ISSUE TITLE
ccminer always getting error 

### ISSUE THREAD

**Issue by shtse8** [tutulino/Megaminer#57]
![ccminer-erro](https://user-images.githubusercontent.com/8020099/29780461-6f45065a-8c48-11e7-9846-5cf898851301.png)

**Comment by shtse8** [comment]
I have removed `ccminerAlexis78.json` to avoid error occur. But what can I do to solve this problem?

**Comment by tutulino** [comment]
Need translation to english of error screen

**Comment by shtse8** [comment]
Just a common error screen what windows always throw. no specific message inside. 
*ccminer has stopped working*
https://bitcointalk.org/index.php?topic=2061955.0

**Comment by shtse8** [comment]
![image](https://user-images.githubusercontent.com/8020099/29786019-2d57dc5e-8c5c-11e7-9a8d-ae60feee3bc4.png)

**Comment by tutulino** [comment]
Can you try launch same command MM launch on a batch file and see if same result?

**Comment by shtse8** [comment]
![ccminer](https://user-images.githubusercontent.com/8020099/29789523-e5107c78-8c68-11e7-8011-b0671da20ac6.jpg)
Yes, it seems their miner problem. But this error always block Megaminer to keep running. I have to manually switch it off every update.

**Comment by shtse8** [comment]
I have to set ASIA, but why nicehash still using EU but not HK in the command?

**Comment by shwuhk** [comment]
![image](https://user-images.githubusercontent.com/10464157/29854693-35455bb6-8d7a-11e7-8c53-c0d65195c7c1.png)
I am getting the same error too.

**Comment by shtse8** [comment]
![image](https://user-images.githubusercontent.com/8020099/29857093-6da415ce-8d89-11e7-9baf-5316f42d4a97.png)
