### ISSUE TITLE
Another AMD Prospector error

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#58]
I think Prospector is starting CPU even tho you have it set to false.
Says not starting CPU but its calling GPU 3 as the CPU
This rig has ONLY GPU0 GPU1 GPU2
No 3,4,5,6,7,etc.....

![prospector](https://user-images.githubusercontent.com/30805282/29781574-a17c4252-8be7-11e7-8c46-f3ca33847704.JPG)

**Comment by tutulino** [comment]
Please run prospector.exe and post generated config.toml file

As workaround you can edit miner file and delete gpu from 3 to 8

**Comment by Imaminer** [comment]
Ok I removed GPU 3-7 and now it is running good.
I will fix that on all rigs
