### ISSUE TITLE
Request for new miner

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#59]
there I see you have had access to AMD cards.
Can you try to implement Excavator?
It is a tricky one. Will need Admin rights to execute Excavator.
I hate Claymore and Excavator runs faster with no fees.
Try it from the Github NiceHash site

**Comment by tutulino** [comment]
No, I haven´t amd card, prospector run on nvidia also.
Excavator for Nvidia is not useful, is useful on AMD?

**Comment by imrecsoka** [comment]
do i just download https://github.com/tutulino/Megaminer/archive/master.zip ?

**Comment by Imaminer** [comment]
Excavator seems a good replacement for Claymore on AMD.
@tutulino If you want to TeamView into one of my AMD rigs for work on any AMD stuff let me know

**Comment by tutulino** [comment]
Added in next release
