### ISSUE TITLE
Tweaked Gateless For Better Performance

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#61]
"Algorithms": [
            {"neoscrypt":"-k neoscrypt --gpu-threads 1 --worksize 256 --intensity 13"},
            {"ethash":"-k ethash-new --gpu-threads 2 --worksize 192 --xintensity 4608"},
            {"cryptonight":"-k cryptonight --gpu-threads 1 --worksize 4 --rawintensity 720"},
            {"equihash":"-k equihash --gpu-threads 2 --worksize 256"}

**Comment by tutulino** [comment]
Added to next release
