### ISSUE TITLE
Gateless AMD alternate tweak

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#62]
The xintensity setting was good for a lot of cards but some got HW errors
Try this instead.
{"ethash":"-k ethash-new --gpu-threads 2 --worksize 192 --intensity 19"},

Gives me same speed (faster then Claymore) and hardly any HW errors. 
I am using it now on all rigs.
All rigs beat Claymore speeds for ETH in benchmarking :)

**Comment by tutulino** [comment]
added
