### ISSUE TITLE
Is there a fail safe mining option?

### ISSUE THREAD

**Issue by imrecsoka** [tutulino/Megaminer#63]
I mean like a simple option to use to test?
When my stuff benchmarks my machine hangs.
Nicehashminer and Mpm doesnt do this.
Maybe i am selecting ugly options?

**Comment by tutulino** [comment]
No test mode, if machine hang you can lower intensity of miners playing with -i parameter. Usually alexis is more problematic miner.

**Comment by imrecsoka** [comment]
config.txt is the only file i know?
which files are we allowed to edit ?

**Comment by tutulino** [comment]
miner folder files, this files defines what miner is used for each algorithm, editing each one you can add parameters or reasign algorithm to other miner
