### ISSUE TITLE
Wrong ZDASH supernova host

### ISSUE THREAD

**Issue by shtse8** [tutulino/Megaminer#68]
as https://zdash.suprnova.cc/ stated that their host is
```
stratum+tcp://hush.suprnova.cc:4048 Nicehash: 4049
```

While Megaminer is trying to connect 
```
stratum+tcp://zdash.suprnova.cc:4048
```

**Comment by shtse8** [comment]
![image](https://user-images.githubusercontent.com/8020099/29910468-a92ca4f2-8e5c-11e7-8a7a-e41b89dca187.png)

**Comment by tutulino** [comment]
Hush pool Adress has changed recently, solved next release
