### ISSUE TITLE
Wrong HashRate of Dual Miner.

### ISSUE THREAD

**Issue by shtse8** [tutulino/Megaminer#70]
For dual mining, I noticed that the hashrate of primary algo is recorded at its max .
https://github.com/tutulino/Megaminer/blob/master/core.ps1#L785

My Actual Rate:
```
24.81 MH/s|132.01 MH/s
```

But Resulting in:
```
ETHASH|BLAKE2B  ethereum|siacoin AMD-ClayDual5  26.81 MH/s|134.01 MH/s 0.00043   2.058 MPH|MPH
ETHASH|PASCAL   ethereum|pascal  AMD-ClayDual5  26.81 MH/s|133.56 MH/s 0.00043   2.058 MPH|NH
ETHASH|BLAKE2B  ethereum|siacoin AMD-ClayDual7  26.80 MH/s|186.82 MH/s 0.00043   2.056 MPH|MPH
ETHASH|PASCAL   ethereum|pascal  AMD-ClayDual7  26.80 MH/s|185.17 MH/s 0.00043   2.056 MPH|NH
```

The hashrate is wrong as it is just the hashrate of primary algo while the dual pool is being connected.
Example:
```
Algo1: 30MHs, Algo2: Connecting  (Algo1 hashrate is recorded, as it is the max)
Algo1: 20MHs, Algo2: 500MHs  (Never update the Algo1 Hashrate because it is always lower than the max.
....
```

**Comment by shtse8** [comment]
I have fixed this bug. Please review. 
https://github.com/tutulino/Megaminer/pull/71

**Comment by shtse8** [comment]
Also, I noticed the hashrate of primary algo with the same `-dcri 7` are different in different second algo.
We can't store the `AMD-ClayDual7_ETHASH_HashRate.txt` separately for all, but should store the hashrate independently inside each miner stats.

**Comment by shtse8** [comment]
We should store like:

Example:
*AMD-ClayDual70_ETHASH_LBRY_HashRate.txt*
```
19271258.139534883
51340080.952380955
```

instead of two files.

**Comment by tutulino** [comment]
True, I have changed and I´m testing now. Thx

I think next release will be out today, but memory leak issue testing is long

**Comment by shtse8** [comment]
Discovered Some typo mistake. Fixed.
As different algo combination, the primary hashrate maybe different, I have updated the `Get-Hashrate` and `Set-Hashrate` to support saving dual hashrate for more accuracy.  
https://github.com/tutulino/Megaminer/pull/71/commits/e0892f1a01a0eb554bbd77987aa0c1c2f793c594
https://github.com/tutulino/Megaminer/pull/71/commits/2c2d40bd70f660fd0ecd7f7b1d4eeddacf6b2059

Hope to help this project developing the part of  AMD and dual mining.

**Comment by tutulino** [comment]
There is a lot of conflicts with my local version, i was working alone and not commit usually, i will make more comitts in future to,avoid this.

My local version has this issue resolved, i have not any amd card, help to test that is greatly apreciated. Thanks
