### ISSUE TITLE
All rigs crashed overnight Powershell errors

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#72]
Woke this morning losing money!
All rigs crashed. 
Serious memory leak.
Please investigate.
![powershell crash](https://user-images.githubusercontent.com/30805282/29968950-f7c3f4e6-8eeb-11e7-8a74-e6baf69b2b86.JPG)

**Comment by tutulino** [comment]
Sorry hear that, is a known bug, i think is resolved in my develop release, but testing now.

I supose you let MM on profits screen, there is a warning on last release about this.

**Comment by Imaminer** [comment]
*Fixed partial: memory usage extremely high, dont let profit screen selected to avoid memory waste
I didnt even see that. I don't download the zips. I git clone code
