### ISSUE TITLE
Neoscrypt of SGMiner is broken.

### ISSUE THREAD

**Issue by shtse8** [tutulino/Megaminer#75]
This error makes Megaminer stop forever once it tries to mine Neoscrypt using SGMiner. Please remove it until the miner is fixed.

```
Error in hsa_operand section, at offset 3552:
Address offset exceeds variable size
LLVM ERROR:
Brig container validation has failed in BRIGAsmPrinter.cpp
```

Reference:
https://github.com/nicehash/NiceHashMiner/issues/676

**Comment by shtse8** [comment]
Gatelessgate Pascal is also failed to start. blank black screen is shown. but for other algos, it works well.

**Comment by tutulino** [comment]
removed both
