### ISSUE TITLE
4.1 Prospector Errors

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#76]
If the .toml has more gpu's listed then then the rig has it tried to use a CPU as a GPU. So the toml had 7 GPU's and my rig has 5 so I removed 2. Even though I set the number of GPU's correct as you can see in log it STILL is trying to use CPU.
Next issue see screen shots and log.
You are very close to getting this one! 
If you need a AMD rig to mess with message me. I can let you TeamView into one of mine.

[02_09_17 12;27;10.txt](https://github.com/tutulino/Megaminer/files/1272158/02_09_17.12.27.10.txt)

![pros1error](https://user-images.githubusercontent.com/30805282/29995534-4d646ec6-8fb9-11e7-922e-f3b2f21b1b6e.JPG)
![pros2error](https://user-images.githubusercontent.com/30805282/29995535-4fddf8c0-8fb9-11e7-8d38-e6dfb479d5c8.JPG)

**Comment by tutulino** [comment]
Prospector is Alpha version yet, I think is a problem with miner, report on miner thread.

**Comment by yuzi-co** [comment]
i believe that could be caused by drivers. have you tried the crimson beta blockchain workloads driver?
