### ISSUE TITLE
4.1 Excavator Issue

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#77]
Excavator attempts to start but immediately fails. If I remember right Excavator need Admin privileges to run. Maybe the issue?

![xcav](https://user-images.githubusercontent.com/30805282/29995560-1b550ac0-8fba-11e7-9f99-6a88aa73c0df.JPG)

**Comment by Imaminer** [comment]
I gave Excavator admin rights and it started to run but never got any hashs. After a few minutes it opened a second cmd wind and that one failed right away because that one did not have Admin rights.
About 1 minute later it crashed my rig ..

**Comment by tutulino** [comment]
Excavator is a little "strange". Try it with nicehash, for example for me, lyra2v2 getting same result (zero) on MPH but works on NH.

**Comment by Imaminer** [comment]
For AMD it needs admin rights because it accesses the bios of the cards.  I don't know how to give it admin rights without it asking each time to accept. It has to get rights without a prompt somehow or will never work for auto-switching

**Comment by yuzi-co** [comment]
for admin privileges can try running the start.bat as administrator
but add the following line at start of the bat file, because by default admin session starts running in c:\windows\system32

cd /d %~dp0

this will switch to the script directory

although in my case, excavator is too buggy and locks up the system often, so i ended up disabling it

**Comment by shtse8** [comment]
![image](https://user-images.githubusercontent.com/8020099/29997763-6cbe1304-904e-11e7-908f-26f0dbfbc505.png)
Same situation here. No active miner, but Excavator is running.

**Comment by tutulino** [comment]
I think MPH and excavator are not good friends.

I don´t like excavator (for Nvidia), but I see is worse for AMD

**Comment by Imaminer** [comment]
Yea I guess just remove it but keep an eye on it for further development

**Comment by scavern** [comment]
fyi... Nicehash no longer support Nicehash2 ie. excavator on AMD, so it's probably a good idea to just remove it from AMD profile altogether
