### ISSUE TITLE
4.1 Ethminer MH/s wrong

### ISSUE THREAD

**Issue by Imaminer** [tutulino/Megaminer#78]
As much as I wish this was right it;s not and this will mess up the which miner the auto switch uses.
These numbers are way to high. This 5 card rig can hit about 120-140 max on ETH and thats only if I push it to the brink of crashing.

![ethminer](https://user-images.githubusercontent.com/30805282/29995624-d4d03514-8fbb-11e7-864a-25e08d2a4a33.JPG)

**Comment by tutulino** [comment]
have you run benchmark more than one time and always get the same?,  what speed is reporting miner?
