### ISSUE TITLE
Suggest to merge all same dual miner into one

### ISSUE THREAD

**Issue by shtse8** [tutulino/Megaminer#79]
At the moment, we need to create same miner config file for different `dcri`. I would like to suggest to merge all into one and then using a array to specific different `dcri`.

For example, 
Merge `AMD-ClayDual5.json`, `AMD-ClayDual7.json`, `AMD-ClayDual9.json`, `AMD-ClayDual11.json` and `ClaymoreETH.json` into `ClaymoreETH.json`
```json
{
"Path" : ".\\Bin\\Ethash-Claymore\\EthDcrMiner64.exe",
"ExtractionPath" : ".\\Bin\\Ethash-Claymore\\",
"Uri" : "https://github.com/tutulino/Claymore-Dual/releases/download/10.0/Claymore-Dual10.zip",
"Types" : ["AMD"],
"Arguments" : "-epool #SERVER#:#PORT# -ewal #LOGIN# -epsw #PASSWORD# -esm 3 -allpools 1 -dpool #SERVERDUAL#:#PORTDUAL# -dwal #LOGINDUAL#  -dpsw #PASSWORDDUAL#  -dcri #INTENSITYDUAL# #ALGORITHMPARAMETERS#",
"API" : "Claymore",
"APIPort" : 3333,
"Wrap" : false,
"DualMining": true,
"DualMiningMainCoin": "Ethereum",
"DualIntensity": [5, 7, 9, 11],
"Algorithms": [
                {"Ethash_Blake2b":" -dcoin sc"},
                {"Ethash_Blake14r":" -dcoin dcr"},
                {"Ethash_Pascal":" -dcoin pasc"},
                {"Ethash_Lbry":" -dcoin lbc"}
              ]

}
```

will result as a single mining `ethash` and all dual mining with all combination of different second algo with different intensity.

**Comment by tutulino** [comment]
I thought on it this morning, I think easiest and future-proof way is allow same algo more than one time with diferent parameters,

                {"Ethash_Blake2b":" -dcoin sc -dcri 10"},
                {"Ethash_Blake2b":" -dcoin sc -dcri 20"},
                {"Ethash_Blake2b":" -dcoin sc -dcri 30"},

This one has some problems like names, duplicates, etc. but I think is easiest way

**Comment by shtse8** [comment]
Why don't adding one more value to do this as we can add one more loop here https://github.com/tutulino/Megaminer/blob/master/core.ps1#L220 . It just like looping the argument instead of looping the files. adding it into the algo list will make the algo list longer multiple times and some miners can support dozens of algos (like ccminer). Some people like me would like to customize the dual mining intensity like adding 5,10,15,20,25,30,35,...,80,85,95. I don't care the benchmarking time because it just run once, but would like to find the highest profitable combination automatically and long lasting (managing more than 100 computers and maybe one day ETH price is dropped).

**Comment by tutulino** [comment]
I dont like program has parametrization for a miner inside core, dcri loop is only valid for claymore dual, my solution also allow for example add different solvers for ewbf or different workers for excavator, etc.

**Comment by yuzi-co** [comment]
1. I believe AMD-ClayDual*.json and Nvidia-ClayDual*.json can be merged into one with "Types" : ["AMD","NVIDIA"] setting

2. I have done a big testing of possible values for AMD processors and I believe it might be logical to create 
a parameter for a tunable (perhaps not as "DualIntensity", but as a generic "TunableParameter")

As of right now, the logical scale for AMD -dcri parameters would be from 10 to 70 in steps of 5, but that depends on the price of ETH.

If other ETH/Alts ratio price ratio changes, it might be logical to extend the parameter up to 1000 for lbry and 500 (current limitations) for the others 

Personally, I have added 10-70 (steps of 5),  70-100 (steps of 10),  150, 200, 500 and 1000 (lbry only)
With the extreme parameters or 500/1000, claymore actually give higher hash rate than sgminer or prospector for the 2nd algos

Anyway, with such a large amount of possible parameters, it would be logical to add a new variable to loop through.

**Comment by tutulino** [comment]
Test 5.0 release
