### ISSUE TITLE
Claymore cryptonote for Cryptonight algo?

### ISSUE THREAD

**Issue by scavern** [tutulino/Megaminer#80]
Any chance to add to add Claymore cryptonote for cryptonight algo? I get higher numbers with claymore than sgminer etc.

**Comment by yuzi-co** [comment]
Try that one:
[ClaymoreXMR.json.txt](https://github.com/tutulino/Megaminer/files/1272729/ClaymoreXMR.json.txt)

**Comment by tutulino** [comment]
Added to next release
