### ISSUE TITLE
zen.suprnova.cc wrong port number

### ISSUE THREAD

**Issue by NobodysPal** [tutulino/Megaminer#81]
SUPRNOVA.ps1:Line 86: 
`$Pools +=[pscustomobject]@{"coin" = "ZENCASH";"algo"="Equihash"; "symbol"= "ZEN";"server"="zen.suprnova.cc"; "port"= "3618";"location"="US"};
`

Also adding '--pec' reveals card efficiency <<--- cant take credit for that one

Cheers!

**Comment by tutulino** [comment]
Solved next release, thx

Added parameter to ewbf
