### ISSUE TITLE
Claymore Dual 10.0 does not terminate at benchmarking

### ISSUE THREAD

**Issue by DrRobotto** [tutulino/Megaminer#82]
I have a rig with 8*1060 3GB and it does not terminate at the benchmark process while running claymore dual algorithms even if the bechmark time interval ends.

**Comment by ylpkm** [comment]
same issue here. newest nvidia driver. Tried ending interval early. changing config times doesnt fix it.

**Comment by tutulino** [comment]
it shows speed on active miner section while benchmarking?

I tested on two rigs with last drivers and works for me.

**Comment by DrRobotto** [comment]
It shows the speed but it does not terminate when the interval ends and just runs forever

**Comment by sypher9** [comment]
I am experiencing the same issue.

powershell -version 5.0 -noexit -executionpolicy bypass -command "&.\core.ps1 -MiningMode AUTOMATIC -PoolsName Mining_Pool_Hub,Zpool,Hash_Refinery

127.17 MH/s|4.24 GH/s Benchmarking Benchmarking ETHASH|BLAKE14R ethereum| Nvidia-ClayDual100 MPH|ZPOOL

**Comment by coderasm** [comment]
Same exact problem here too.
