### ISSUE TITLE
YIIMP hacked. Probably should remove.

### ISSUE THREAD

**Issue by Hypheonix** [tutulino/Megaminer#84]
https://www.reddit.com/r/gpumining/comments/6yyz2x/warning_on_httpyiimpeu_the_pool_was_hacked/
http://yiimp.ccminer.org
Confirmed that mining to this pool will not yield payouts.

**Comment by tutulino** [comment]
Zpool and HR are also affected, I recommed move this pools files to other folder while pools admins find a solution
