### ISSUE TITLE
Option to disable dual mining

### ISSUE THREAD

**Issue by scavern** [tutulino/Megaminer#87]
Can you add an option in config file to disable dual mining?

**Comment by yuzi-co** [comment]
Just remove the AMD-ClayDual*.json or Nvidia-ClayDual*.json from the miners folder

**Comment by scavern** [comment]
Yes I know, but it would be cleaner to have it configured in the config.

**Comment by tutulino** [comment]
Maybe a config full of options is not easy for noobs. I will think about it.
