### ISSUE TITLE
Not downloading CCminer 

### ISSUE THREAD

**Issue by Atroci** [tutulino/Megaminer#92]
It says it doesnt run on windows, my setup have 6 amd and 6 nvidia cards, I gets stuck not downloading this and showing error messages

**Comment by Atroci** [comment]
nvidia alexis78/ccminer-alexis78-ms2013/cuda7.5/MSVCR120.dll wasnt projected to run on windows.

**Comment by tutulino** [comment]
Post a screen capture please.
