### ISSUE TITLE
ZPool favored?

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#94]
When using Automatic24h, I noticed that ZPool seems to be favored against other pools. I focused on comparing against H.Ref (to avoid over-complicating stuff). Also, I believe this also applies to the 'Automatic' mode.
This is what I did: I ran side-by-side 2 instances of MegaMiner (cfr. on the same box --> so same config), in one only selecting HRef while the other combined HRef with ZPool. As soon as both of them ran, I used 'E' in both windows simultaneously. This is the output (only the lines I believe are interesting):

HRef only:
------------------------------------------------ACTIVE MINERS----------------------------------------------------------

    Speed BTC/Day EUR/Day Algorithm Coin Miner           Pool   Location PoolWorkers
    ----- ------- ------- --------- ---- -----           ----   -------- -----------
50.15 MHs 0.00180 7.46    X17            ccminerAlexis78 H.RFRY US                27

----------------------------------------------------PROFITS------------------------------------------------------------
(B)est Miners/All       (T)op 40/All

Algorithm Coin Miner                Speed       BTC/Day EUR/Day Pool   Location
--------- ---- -----                -----       ------- ------- ----   --------
X17            ccminerAlexis78      88.50 MH/s  0.00292   12.08 H.RFRY US
NEOSCRYPT      CcminerKlaust        6.62 MH/s   0.00205    8.47 H.RFRY US

=-=-=--=-=-=-

HRef + ZPool:
------------------------------------------------ACTIVE MINERS----------------------------------------------------------

    Speed BTC/Day EUR/Day Algorithm Coin Miner           Pool  Location PoolWorkers
    ----- ------- ------- --------- ---- -----           ----  -------- -----------
49.25 MHs 0.00000 0.02    BLAKE2S        ccminerAlexis78 ZPOOL US              1117

----------------------------------------------------PROFITS------------------------------------------------------------
(B)est Miners/All       (T)op 40/All

Algorithm      Coin Miner                Speed       BTC/Day EUR/Day Pool   Location
---------      ---- -----                -----       ------- ------- ----   --------
BLAKE2S             ccminerAlexis78      32.57 GH/s  0.00272   11.23 ZPOOL  US
X17                 ccminerAlexis78      88.50 MH/s  0.00265   10.95 ZPOOL  US
C11                 ccminerAlexis78      137.38 MH/s 0.00250   10.36 ZPOOL  US
VELTOR              ccminerAlexis78      261.75 MH/s 0.00224    9.25 ZPOOL  US
LYRA2V2             ccminerAlexis78      302.66 MH/s 0.00216    8.94 ZPOOL  US
NEOSCRYPT           CcminerKlaust        6.62 MH/s   0.00205    8.47 H.RFRY US

Some thoughts on this:
1. HRef only select X17 for a 0.00292 BTC/Day value. When combined with ZPool Blake2S suddenly becomes preferred for a (lower) value of 0.00272 BTC/Day value
2. In the HRef + ZPool: HRef is only coming on the 6th place (for a value of 0.00205 BTC/Day value.

**Comment by tutulino** [comment]
Ufff....hard to understand and find the bug. I´m testing solution now and seems to work, solved in next release.

Thanks

**Comment by eMTee72** [comment]
Thanks for taking the time to look into it!! I realize this must have been complicated as the values are changing all the time.
