### ISSUE TITLE
Miner URL incorrect (4.5)

### ISSUE THREAD

**Issue by eMTee72** [tutulino/Megaminer#96]
From Log:

Downloading....https://github.com/KlausT/ccminer/releases/download/8.14beta/ccminer-814beta-x64-cuda9.zip
PS>TerminatingError(Invoke-WebRequest): "The request was aborted: The connection was closed unexpectedly."
>> TerminatingError(Invoke-WebRequest): "The request was aborted: The connection was closed unexpectedly."

Other miner downloads work fine though.

**Comment by eMTee72** [comment]
Correct URL should be:
https://github.com/KlausT/ccminer/releases/download/8.14/ccminer-814-cuda8-x64.zip

**Comment by tutulino** [comment]
true, it will be changed next release. Thanks.
