### ISSUE TITLE
Sometimes AMD-sgminer hangs then i have to restart megaminer

### ISSUE THREAD

**Issue by tatsumakisen** [tutulino/Megaminer#97]
Using mix rig nvidia, amd

Sometimes AMD-sgminer hangs then i have to restart megaminer

**Comment by tatsumakisen** [comment]
Using mix rig nvidia, amd

Sometimes AMD-sgminer hangs then i have to restart megaminer

**Comment by tutulino** [comment]
MM is only a launcher check if parameters are ok in History screen.

Check your overclock settings also
