### ISSUE TITLE
ccminerAlexis78-hsr miner is constantly closing on the message "Pool asked your stats"

### ISSUE THREAD

**Issue by MonaxDK** [tutulino/Megaminer#98]
![alexis-hsr](https://user-images.githubusercontent.com/29005588/32745945-e9109d4a-c8bc-11e7-8acc-31ad87a81794.png)
This happens on zpool, I do not know how on the others.
It seems that the miner can not process such a request ...
I'm using megaminer 4.5

**Comment by MikeBuzz** [comment]
remove the stats option from the zpool file

**Comment by MikeBuzz** [comment]
https://github.com/tutulino/Megaminer/blob/master/Pools/Zpool.ps1

change
Pass          = "c=$Currency,$WorkerName,stats"
to
Pass          = "c=$Currency,$WorkerName"

**Comment by MonaxDK** [comment]
Thank you! That helped
